begin;
insert into topic_contents (topic_id, summary, content_md, example_question) values ('d36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'Gerçek, mecaz, yan ve terim anlam ile eş anlam, zıt anlam, sesteşlik ve deyimlerin cümle içindeki kullanımını örneklerle işleyen sözcükte anlam konusu.', '## Gerçek (Temel) Anlam ve Mecaz Anlam
Bir kelimenin ilk akla gelen, sözlükteki asıl anlamına gerçek (temel) anlam denir: ''Bu çanta çok ağırdı.'' Kelimenin benzetme yoluyla kazandığı, gerçek anlamından uzaklaşmış anlamına ise mecaz anlam denir: ''Sınav soruları oldukça ağırdı.'' (zor anlamında)

## Yan Anlam ve Terim Anlam
Bir kelimenin temel anlamıyla ilgili fakat ondan biraz uzaklaşmış anlamına yan anlam denir: ''Masanın ayağı kırıldı.'' Bir bilim, sanat veya meslek dalına özgü kavramı karşılayan anlama ise terim anlam denir: ''Bu cümlenin öznesini bulun.'' veya ''Kelimenin kökünü belirleyin.''

## Eş Anlam (Anlamdaş) ve Zıt Anlam (Karşıt)
Yazılışları farklı, anlamları aynı veya çok yakın olan kelimelere eş anlamlı (anlamdaş) denir: ''kara-siyah, misafir-konuk.'' Birbirinin karşıtı olan kelimelere ise zıt anlamlı (karşıt) denir: ''büyük-küçük, sıcak-soğuk.''

## Eş Sesli (Sesteş) Kelimeler
Yazılışları aynı, anlamları farklı kelimelere sesteş (eş sesli) denir: ''Yüzünde bir gülümseme vardı.'' (yüz=çehre) ile ''Denizde saatlerce yüzdü.'' (yüz=yüzmek eylemi) cümlelerindeki ''yüz'' kelimeleri sesteştir.

## Deyimler
İki veya daha fazla kelimeden oluşan, çoğunlukla mecazlı anlam taşıyan kalıplaşmış söz gruplarına deyim denir: ''eli kulağında'' (bir işin bitmesine az kalmış olması), ''içi kararmak'' (çok üzülmek). Deyimler, cümle içinde kalıplaşmış anlamlarıyla ve bu anlama uygun bağlamda kullanılmalıdır; anlamına ters düşen bir bağlamda kullanılması anlatım bozukluğuna yol açar.', '''Eli kulağında'' deyimi aşağıdaki cümlelerin hangisinde doğru kullanılmıştır?') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('0795d713-db0e-4468-9e84-0bc3deb45ff6', 'd36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde ''ağır'' sözcüğü mecaz anlamda kullanılmıştır?', 'Gerçek anlam ile mecaz anlamı ayırt eder.', 'İkinci cümlede ''ağır'' sözcüğü fiziksel bir ağırlığı değil, ''zor, çetin'' anlamını karşıladığı için mecaz anlamda kullanılmıştır. Diğer cümlelerde ''ağır'' sözcüğü nesnenin gerçek fiziksel ağırlığını belirtir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0795d713-db0e-4468-9e84-0bc3deb45ff6', 'Bu çanta gerçekten çok ağırdı.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0795d713-db0e-4468-9e84-0bc3deb45ff6', 'Sınav soruları oldukça ağırdı.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0795d713-db0e-4468-9e84-0bc3deb45ff6', 'Valizi taşırken sırtım ağrıdı, çünkü çok ağırdı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0795d713-db0e-4468-9e84-0bc3deb45ff6', 'Demir, ağır bir madendir.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('bdd3a383-6a62-407e-b95a-9100cae1f16f', 'd36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'kolay'::difficulty_level, 'Aşağıdaki kelime çiftlerinden hangisi eş anlamlıdır (anlamdaştır)?', 'Eş anlamlı (anlamdaş) kelimeleri tanır.', '''Kara'' ve ''siyah'' kelimeleri aynı rengi karşıladığı için eş anlamlıdır. Diğer seçeneklerdeki kelime çiftleri ise birbirinin zıt anlamlısıdır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('bdd3a383-6a62-407e-b95a-9100cae1f16f', 'kara - siyah', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('bdd3a383-6a62-407e-b95a-9100cae1f16f', 'büyük - küçük', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('bdd3a383-6a62-407e-b95a-9100cae1f16f', 'sıcak - soğuk', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('bdd3a383-6a62-407e-b95a-9100cae1f16f', 'ışık - karanlık', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('9ea4593a-800e-4762-8461-d68417b848c9', 'd36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'orta'::difficulty_level, '''Eli kulağında'' deyimi aşağıdaki cümlelerin hangisinde doğru kullanılmıştır?', 'Deyimlerin cümle içindeki uygun kullanımını değerlendirir.', '''Eli kulağında'' deyimi bir işin bitmesine çok az kaldığını anlatır; birinci cümlede projenin yakında tamamlanacağı belirtildiği için deyim doğru bağlamda kullanılmıştır. Diğer cümlelerde deyimin anlamıyla cümlenin geri kalanı çelişmektedir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9ea4593a-800e-4762-8461-d68417b848c9', 'Proje eli kulağında, birkaç güne kadar tamamlanmış olacak.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9ea4593a-800e-4762-8461-d68417b848c9', 'Bu iş eli kulağında, çünkü daha yeni başladık.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9ea4593a-800e-4762-8461-d68417b848c9', 'O her zaman eli kulağında biriydi.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9ea4593a-800e-4762-8461-d68417b848c9', 'Param eli kulağında bittiği için borç almak zorunda kaldım.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('b440292a-29b7-4b81-a2c0-44e35af73468', 'd36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde ''yüz'' sözcüğü diğerlerinden farklı bir anlamda (sesteş olarak) kullanılmıştır?', 'Sesteş (eş sesli) kelimeleri cümle bağlamında ayırt eder.', 'İkinci cümlede ''yüzdü'', ''yüzmek'' eyleminden gelir ve suda hareket etmeyi ifade eder; diğer cümlelerdeki ''yüz'' ise ''çehre, surat'' anlamındaki isimdir. Yazılışları aynı fakat anlamları farklı olduğu için bu kelimeler sesteştir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b440292a-29b7-4b81-a2c0-44e35af73468', 'Yüzünde güzel bir gülümseme vardı.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b440292a-29b7-4b81-a2c0-44e35af73468', 'Denizde saatlerce yüzdü.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b440292a-29b7-4b81-a2c0-44e35af73468', 'Yüzü hafif kızarmıştı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b440292a-29b7-4b81-a2c0-44e35af73468', 'Onun yüzüne bakamadım.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('82b36052-73e0-4ffc-81d8-d2a76a0946e8', 'd36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'zor'::difficulty_level, '''Kök'' sözcüğü aşağıdaki cümlelerin hangisinde terim anlamda (dil bilgisi terimi olarak) kullanılmıştır?', 'Terim anlamı gerçek ve mecaz anlamdan ayırt eder.', 'İkinci cümlede ''kök'', bir kelimenin anlam taşıyan en küçük parçasını belirten dil bilgisi terimi olarak kullanılmıştır. Diğer cümlelerde ''kök'' sözcüğü sırasıyla gerçek anlamda (bitki kökü) ve mecaz anlamda (kaynak, köken) kullanılmıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('82b36052-73e0-4ffc-81d8-d2a76a0946e8', 'Bahçedeki ağacın kökü çok derinlere inmişti.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('82b36052-73e0-4ffc-81d8-d2a76a0946e8', 'Bu kelimenin kökü Arapçadır.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('82b36052-73e0-4ffc-81d8-d2a76a0946e8', 'Sorunun kökünü araştırmalıyız.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('82b36052-73e0-4ffc-81d8-d2a76a0946e8', 'Bu ailenin kökleri çok eskiye dayanıyor.', false, 3);
insert into topic_contents (topic_id, summary, content_md, example_question) values ('eb6df17f-05d4-49df-b626-ba5d585672a9', 'Anlatım bozukluğu türlerini (gereksiz sözcük, çelişki, mantık hatası, tamlama yanlışlığı), öznel-nesnel yargı ayrımını ve cümle tamamlamayı örneklerle açıklayan konu.', '## Anlatım Bozukluğu Türleri
Anlatım bozukluğu, bir cümlede anlam veya dil bilgisi açısından ortaya çıkan hatalardır. Başlıca türleri:
- **Gereksiz sözcük kullanımı:** Aynı anlama gelen iki kelimenin bir arada kullanılması. ''Bu haber beni hem çok sevindirdi hem de mutlu etti.'' (sevindirmek ve mutlu etmek eş anlamlıdır, biri gereksizdir.)
- **Çelişki:** Cümledeki iki ifadenin birbiriyle çelişmesi. ''Belki de bu sınavı kesinlikle kazanacak.'' (''belki'' ihtimal, ''kesinlikle'' kesinlik bildirir; bir arada kullanılamaz.)
- **Mantık (neden-sonuç) hatası:** Cümledeki neden ile sonucun birbiriyle uyuşmaması. ''Param olmadığı için kitabı alamadım ama yine de aldım.''
- **Tamlama yanlışlığı:** Ortak kullanılan bir öğeye ait ekin eksik bırakılması. ''Ali ve babasının arabası kaza yaptı.'' cümlesinde ''Ali'' kelimesinden sonra ''-nin'' tamlayan eki eksiktir; doğrusu ''Ali''nin ve babasının arabası'' olmalıdır.

## Öznel Yargı ve Nesnel Yargı
Nesnel yargı, kişiden kişiye değişmeyen, kanıtlanabilir, gözlemlenebilir bilgi içeren yargıdır: ''Roman 320 sayfadan oluşmaktadır.'' Öznel yargı ise kişisel görüş, beğeni ya da yorum içerir ve kişiden kişiye değişebilir: ''Bence bu roman çok sıkıcıydı.'' ''En, en güzel, bence, bana göre, sanırım'' gibi ifadeler genellikle öznelliğin işaretidir.

## Cümle Tamamlama
Bir cümlenin ya da paragrafın bağlamına en uygun ifadeyi seçmek, cümledeki anlam bütünlüğünü ve mantıksal akışı bozmayan seçeneği bulmayı gerektirir. Doğru seçenek, metinde verilen bilgilerle çelişmemeli ve konu dışına çıkmamalıdır.', '''Belki de bu sınavı kesinlikle kazanacak.'' cümlesindeki anlatım bozukluğunun türünü belirtiniz.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('55380dbf-5554-4bed-b96b-68de47743b6c', 'eb6df17f-05d4-49df-b626-ba5d585672a9', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisi nesnel bir yargı bildirmektedir?', 'Öznel yargı ile nesnel yargıyı ayırt eder.', 'Birinci cümlede sayfa sayısı, kişiden kişiye değişmeyen, kanıtlanabilir bir bilgi olduğu için nesneldir. Diğer cümleler kişisel görüş ve beğeni içerdiğinden özneldir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('55380dbf-5554-4bed-b96b-68de47743b6c', 'Roman, 320 sayfadan oluşmaktadır.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('55380dbf-5554-4bed-b96b-68de47743b6c', 'Bence bu roman çok sıkıcıydı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('55380dbf-5554-4bed-b96b-68de47743b6c', 'Yazarın en başarılı eseri budur.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('55380dbf-5554-4bed-b96b-68de47743b6c', 'Bu film gelmiş geçmiş en iyi yapımdı.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('4830d69f-8d8c-4322-b5f1-d8b8d94e757c', 'eb6df17f-05d4-49df-b626-ba5d585672a9', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir anlatım bozukluğu vardır?', 'Gereksiz sözcük kullanımından kaynaklanan anlatım bozukluğunu fark eder.', '''Sevindirmek'' ve ''mutlu etmek'' aynı anlama geldiği için bu iki ifadenin bir arada kullanılması gereksiz tekrara, dolayısıyla anlatım bozukluğuna yol açmıştır. Diğer cümlelerde böyle bir tekrar yoktur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4830d69f-8d8c-4322-b5f1-d8b8d94e757c', 'Bu haber beni hem çok sevindirdi hem de mutlu etti.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4830d69f-8d8c-4322-b5f1-d8b8d94e757c', 'Öğrenciler sınava iyi hazırlandı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4830d69f-8d8c-4322-b5f1-d8b8d94e757c', 'Kitabı okuyup arkadaşına anlattı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4830d69f-8d8c-4322-b5f1-d8b8d94e757c', 'Yağmur yağınca sokaklar ıslandı.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('5328392f-cca6-4ec6-b191-57016dbf0465', 'eb6df17f-05d4-49df-b626-ba5d585672a9', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir anlatım bozukluğu vardır?', 'Çelişkiden kaynaklanan anlatım bozukluğunu tespit eder.', '''Belki'' ihtimal, ''kesinlikle'' ise kesinlik bildirir; bu iki ifade anlamca birbiriyle çeliştiği için cümlede anlatım bozukluğu vardır. Diğer cümlelerde böyle bir çelişki bulunmamaktadır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('5328392f-cca6-4ec6-b191-57016dbf0465', 'Belki de bu sınavı kesinlikle kazanacak.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('5328392f-cca6-4ec6-b191-57016dbf0465', 'Öğretmen konuyu tekrar anlattı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('5328392f-cca6-4ec6-b191-57016dbf0465', 'Sabah erkenden yola çıktık.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('5328392f-cca6-4ec6-b191-57016dbf0465', 'Kitapları düzenli bir şekilde raflara yerleştirdi.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('03e85f88-3b18-4ec7-8cca-81516ec12923', 'eb6df17f-05d4-49df-b626-ba5d585672a9', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir anlatım bozukluğu vardır?', 'Neden-sonuç ilişkisindeki mantık hatasını fark eder.', 'Cümlede önce parası olmadığı için kitabı alamadığı söylenmiş, ardından yine de aldığı belirtilerek çelişkili bir mantık hatası oluşturulmuştur. Diğer cümlelerde neden ile sonuç arasında tutarlı bir ilişki vardır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('03e85f88-3b18-4ec7-8cca-81516ec12923', 'Param olmadığı için kitabı alamadım ama yine de aldım.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('03e85f88-3b18-4ec7-8cca-81516ec12923', 'Erken kalktığım için derse zamanında yetiştim.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('03e85f88-3b18-4ec7-8cca-81516ec12923', 'Yorgun olduğu için erken yattı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('03e85f88-3b18-4ec7-8cca-81516ec12923', 'Kitabı bitirince bana geri verdi.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('1a58e075-3dbb-4bc1-a1a1-6f2831c360aa', 'eb6df17f-05d4-49df-b626-ba5d585672a9', 'zor'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir anlatım bozukluğu vardır?', 'Tamlama yanlışlığından kaynaklanan anlatım bozukluğunu ileri düzeyde tespit eder.', '''Ali'' kelimesinden sonra tamlayan eki ''-nin'' eksik bırakıldığı için cümlede tamlama yanlışlığı vardır; doğrusu ''Ali''nin ve babasının arabası'' biçiminde olmalıdır. Diğer cümlelerde böyle bir ek eksikliği yoktur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1a58e075-3dbb-4bc1-a1a1-6f2831c360aa', 'Ali ve babasının arabası kaza yaptı.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1a58e075-3dbb-4bc1-a1a1-6f2831c360aa', 'Ali''nin ve babasının arabası kaza yaptı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1a58e075-3dbb-4bc1-a1a1-6f2831c360aa', 'Öğrenciler sınıfa girdi ve yerlerine oturdu.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1a58e075-3dbb-4bc1-a1a1-6f2831c360aa', 'Yağmur dinince hep birlikte dışarı çıktık.', false, 3);
insert into topic_contents (topic_id, summary, content_md, example_question) values ('f884a167-9e40-4c5c-bc29-810eb13f200e', 'Paragrafta ana düşünce ve yardımcı düşünceyi ayırt etme, paragraf tamamlama ve metinden çıkarılabilecek/çıkarılamayacak yargıları belirleme becerilerini işleyen konu.', '## Konu ve Ana Düşünce
Bir paragrafın neyle ilgili olduğunu belirten kavrama konu denir; yazarın bu konu hakkında okura iletmek istediği asıl mesaja ise ana düşünce denir. Ana düşünce genellikle paragrafın son cümlesinde, bazen de ilk cümlesinde yer alır ve paragraftaki tüm cümleleri kapsayan bir yargı niteliğindedir.

## Yardımcı Düşünce
Ana düşünceyi destekleyen, açıklayan veya örnekleyen düşüncelere yardımcı düşünce denir. Bir paragrafta birden fazla yardımcı düşünce bulunabilir, ancak ana düşünce tektir.

## Paragraf Tamamlama
Paragrafın başına, ortasına ya da sonuna getirilecek cümle; paragrafın anlam bütünlüğünü, konu akışını ve mantık örgüsünü bozmamalıdır. Başa gelecek cümle genellikle konuyu tanıtır; sona gelecek cümle ise paragrafta anlatılanların bir sonucu, genellemesi ya da tamamlayıcısı niteliğinde olmalıdır. Doğru seçenek metindeki bilgilerle çelişmemeli ve konu dışına çıkmamalıdır.

## Metinden Çıkarılabilecek Yargılar
''Bu parçadan hangi yargıya ulaşılabilir/ulaşılamaz'' tipi sorularda, seçeneklerin metinde açıkça ifade edilen ya da metinden mantıksal olarak çıkarılabilen bilgilerle örtüşüp örtüşmediğine bakılır. Metinde yer almayan, aşırı genelleme içeren ya da metinle çelişen seçenekler yanlıştır.

## Anlatım Biçimleri
Paragraflarda yazarın öznel ya da nesnel bir bakış açısıyla yazıp yazmadığı; örnekleme, tanık gösterme, karşılaştırma gibi düşünceyi geliştirme yollarının kullanılıp kullanılmadığı da sıkça sorulur.', 'Aşağıdaki paragrafın ana düşüncesi ne olabilir? ''Kitap okumak, insanın hayal gücünü geliştirir, kelime dağarcığını zenginleştirir...''') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('8c4343f2-6679-4a1a-bf13-3a9603a4d61c', 'f884a167-9e40-4c5c-bc29-810eb13f200e', 'kolay'::difficulty_level, '''İnsanlar günlük hayatlarında birçok karar verir. Bu kararların bazıları küçük, bazıları ise hayatı derinden etkileyecek kadar büyüktür. Küçük kararlar genellikle anlık düşünülüp hızla alınırken büyük kararlar için uzun süre düşünülür, çevredeki insanların fikirleri alınır. Çünkü büyük kararların sonuçları, kişinin hayatını uzun yıllar etkileyebilir.'' Bu parçanın ana düşüncesi aşağıdakilerden hangisidir?', 'Paragrafın ana düşüncesini belirler.', 'Parça, büyük kararların uzun süre düşünülerek ve başkalarının görüşü alınarak verilmesi gerektiğini, çünkü sonuçlarının kalıcı olduğunu vurgulamaktadır. Diğer seçenekler ya parçanın yalnızca bir kısmını yansıtır ya da metinde yer almayan aşırı bir genelleme içerir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8c4343f2-6679-4a1a-bf13-3a9603a4d61c', 'İnsanlar hayatları boyunca sürekli karar alma durumundadır.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8c4343f2-6679-4a1a-bf13-3a9603a4d61c', 'Büyük kararlar, sonuçlarının kalıcı etkisi nedeniyle daha dikkatli ve uzun düşünülerek alınmalıdır.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8c4343f2-6679-4a1a-bf13-3a9603a4d61c', 'Küçük kararlar hızlı alındığı için önemsizdir.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8c4343f2-6679-4a1a-bf13-3a9603a4d61c', 'Çevredeki insanların fikirleri her zaman doğru kararlar verdirir.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('0e326fc3-3273-4770-b311-3819fa74bb04', 'f884a167-9e40-4c5c-bc29-810eb13f200e', 'kolay'::difficulty_level, '''Kitap okumak, insanın hayal gücünü geliştirir, kelime dağarcığını zenginleştirir ve empati kurma becerisini artırır. Ayrıca düzenli kitap okuyan bireylerin analitik düşünme yetenekleri de gelişir. Bu nedenle ______'' Bu parçada boş bırakılan yere aşağıdakilerden hangisi getirilmelidir?', 'Paragrafın anlam akışına uygun tamamlama cümlesini seçer.', 'Parçada kitap okumanın sağladığı faydalar sıralandığı için mantıksal sonuç, bu alışkanlığın erken yaşta kazandırılması gerektiğidir. Diğer seçenekler parçanın konusuyla ilgisizdir ya da metinde değinilmeyen konulara değinir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0e326fc3-3273-4770-b311-3819fa74bb04', 'televizyon izlemek de kitap okumak kadar faydalıdır.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0e326fc3-3273-4770-b311-3819fa74bb04', 'çocuklara küçük yaştan itibaren kitap okuma alışkanlığı kazandırılmalıdır.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0e326fc3-3273-4770-b311-3819fa74bb04', 'kitap okumanın hiçbir zararı yoktur.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0e326fc3-3273-4770-b311-3819fa74bb04', 'herkesin aynı türde kitap okuması gerekir.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('e9bc37d9-d918-4c60-8b78-809052d71989', 'f884a167-9e40-4c5c-bc29-810eb13f200e', 'orta'::difficulty_level, '''Şehirlerin hızla büyümesiyle birlikte yeşil alanlar giderek azalmaktadır. Betonlaşan kentlerde hava kalitesi düşmekte, sıcaklık artışları daha belirgin hissedilmektedir. Bununla birlikte bazı belediyeler, çatı bahçeleri ve dikey ormanlar gibi projelerle bu soruna çözüm aramaktadır. Ancak bu çabalar, kaybedilen yeşil alanların yerini tam olarak dolduramamaktadır.'' Bu parçanın ana düşüncesi aşağıdakilerden hangisidir?', 'Paragrafta ana düşünce ile yardımcı düşünceleri ayırt eder.', 'Parça, kentleşmeyle azalan yeşil alanlar için belediyelerin çözüm aradığını ama bu çabaların yeterli olmadığını vurgulamaktadır. Diğer seçenekler metinle çelişir ya da metinde yapılmayan bir karşılaştırma veya aşırı genelleme içerir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e9bc37d9-d918-4c60-8b78-809052d71989', 'Belediyeler çevre sorunlarına duyarsız kalmaktadır.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e9bc37d9-d918-4c60-8b78-809052d71989', 'Kentleşmeyle azalan yeşil alanların yerini, alınan önlemler yeterince dolduramamaktadır.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e9bc37d9-d918-4c60-8b78-809052d71989', 'Çatı bahçeleri, dikey ormanlardan daha etkilidir.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e9bc37d9-d918-4c60-8b78-809052d71989', 'Hava kalitesi yalnızca sıcaklıkla ilgilidir.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('8c2b1a20-fd4b-4e94-894d-080ccfe08aa3', 'f884a167-9e40-4c5c-bc29-810eb13f200e', 'orta'::difficulty_level, '''______ Bu tür kitaplar, karmaşık bilimsel kavramları sade bir dille anlatarak okurun ilgisini çeker. Yazar, günlük hayattan örnekler kullanarak konuyu somutlaştırır. Böylece bilim, sadece uzmanların değil herkesin anlayabileceği bir alan hâline gelir.'' Bu parçanın başına aşağıdaki cümlelerden hangisi getirilmelidir?', 'Paragrafın başına gelecek en uygun giriş cümlesini belirler.', 'Parçanın devamında ''bu tür kitaplar'' ifadesiyle atıf yapılan konu, ancak popüler bilim kitaplarını tanıtan birinci seçenekle uyumludur. Diğer seçenekler parçanın konusuyla ilgisizdir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8c2b1a20-fd4b-4e94-894d-080ccfe08aa3', 'Popüler bilim kitapları, bilimi geniş kitlelere ulaştırmayı amaçlayan eserlerdir.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8c2b1a20-fd4b-4e94-894d-080ccfe08aa3', 'Bilim insanları genellikle yalnız çalışmayı tercih eder.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8c2b1a20-fd4b-4e94-894d-080ccfe08aa3', 'Roman yazarları hayal gücünü kullanarak eser üretir.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8c2b1a20-fd4b-4e94-894d-080ccfe08aa3', 'Her kitap mutlaka bir amaç taşımalıdır.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('87bab34d-3b9e-40cf-b229-0c2863631d76', 'f884a167-9e40-4c5c-bc29-810eb13f200e', 'zor'::difficulty_level, '''Bir sanat eserinin değeri, yalnızca teknik ustalıkla ölçülemez. Tuval üzerine ustaca işlenmiş bir tablo, izleyicide hiçbir duygu uyandırmıyorsa amacına ulaşamamış demektir. Oysa bazen çok basit çizgilerle oluşturulmuş bir eser, izleyicisini derinden etkileyebilir, onu düşünmeye sevk edebilir. Bu nedenle sanatı değerlendirirken teknik beceri kadar, eserin izleyicide bıraktığı etkiye de bakmak gerekir.'' Bu parçadan aşağıdaki yargılardan hangisine ulaşılamaz?', 'Paragraftan çıkarılabilecek ve çıkarılamayacak yargıları ayırt eder.', 'Parçada sanatçının ününden hiç söz edilmediği için dördüncü seçenekteki yargıya metinden ulaşılamaz. Diğer seçenekler parçada doğrudan ya da dolaylı olarak ifade edilmiştir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('87bab34d-3b9e-40cf-b229-0c2863631d76', 'Teknik açıdan kusursuz bir eser, izleyicide duygu uyandırmayabilir.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('87bab34d-3b9e-40cf-b229-0c2863631d76', 'Basit görünen eserler de izleyici üzerinde güçlü bir etki bırakabilir.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('87bab34d-3b9e-40cf-b229-0c2863631d76', 'Bir sanat eserini değerlendirirken hem teknik beceri hem de duygusal etki göz önünde bulundurulmalıdır.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('87bab34d-3b9e-40cf-b229-0c2863631d76', 'Sanat eserlerinin değeri, yalnızca sanatçının ününe göre belirlenir.', true, 3);
commit;
