begin;
insert into topic_contents (topic_id, summary, content_md, example_question) values ('ffe5c195-5fea-45a3-9030-58f122e0e1ee', 'Ünlü ve ünsüz uyumu, ünsüz yumuşaması/sertleşmesi, ünlü düşmesi ve kaynaştırma ünsüzleri gibi ses olaylarını kapsayan bu konu, Türkçenin ses bilgisi kurallarını örneklerle açıklar.', '## Büyük Ünlü Uyumu (Kalınlık-İncelik Uyumu)
Türkçe kökenli bir kelimenin ilk hecesinde kalın ünlü (a, ı, o, u) varsa sonraki hecelerde de kalın ünlü bulunur; ilk hecede ince ünlü (e, i, ö, ü) varsa sonraki hecelerde de ince ünlü bulunur. Örneğin ''kalemlik'' kelimesindeki ''kalem'' kökü Arapça kökenli olduğu için bu kurala aykırıdır (a-e). ''Kalem, hangi, elma, anne'' gibi bazı yabancı kökenli ya da kalıplaşmış kelimeler bu kuralın istisnasıdır.

## Küçük Ünlü Uyumu (Düzlük-Yuvarlaklık Uyumu)
Düz ünlülerden (a, e, ı, i) sonra düz ünlü gelir. Yuvarlak ünlülerden (o, ö, u, ü) sonra ise ya düz-geniş (a, e) ya da dar-yuvarlak (u, ü) ünlü gelir. ''Doktor, otobüs, radyo'' gibi yabancı kökenli kelimeler bu kurala da aykırıdır çünkü yuvarlak bir ünlüden sonra yine geniş-yuvarlak (o, ö) bir ünlü gelmiştir.

## Ünsüz Benzeşmesi (Sertleşme)
Sert ünsüzle (ç, f, h, k, p, s, ş, t = ''fıstıkçı şahap'') biten bir kelimeye yumuşak ünsüzle başlayan bir ek gelirse, ekin başındaki ünsüz sertleşir: kitap+cı → kitapçı, ağaç+da → ağaçta, iş+ci → işçi.

## Ünsüz Yumuşaması
p, ç, t, k ile biten bir kelime ünlüyle başlayan bir ek aldığında bu ünsüzler yumuşayarak sırasıyla b, c, d, ğ/g''ye dönüşür: kitap→kitabı, ağaç→ağacı, at→adı, çocuk→çocuğu.

## Ünlü Düşmesi (Hece Düşmesi)
İkinci hecesinde dar ünlü (ı, i, u, ü) bulunan bazı iki heceli kelimeler ünlüyle başlayan bir ek aldığında bu dar ünlü düşer: burun→burnu, ağız→ağzı, akıl→aklı, oğul→oğlu, şehir→şehri.

## Kaynaştırma Ünsüzleri
Ünlüyle biten bir kelime ünlüyle başlayan bir ek aldığında, iki ünlünün yan yana gelmesini önlemek için araya ''y, ş, s, n'' kaynaştırma ünsüzlerinden biri girer: kapı+ı→kapıyı, iki+er→ikişer, araba+ın→arabasının, kapı+ın→kapının.', 'Örnek: ''Ağacın gölgesinde otururken kitabını okudu.'' cümlesinde hangi kelimede ünsüz yumuşaması görülür?') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('e9fdb675-f729-47d1-bbe5-047d3406e6ec', 'ffe5c195-5fea-45a3-9030-58f122e0e1ee', 'kolay'::difficulty_level, 'Aşağıdaki kelimelerden hangisi büyük ünlü uyumuna (kalınlık-incelik uyumuna) aykırıdır?', 'Büyük ünlü uyumu kuralını kelimeler üzerinde uygular.', '''Kalem'' kökü Arapça kökenli olup ilk hecesinde kalın ünlü (a), ikinci hecesinde ince ünlü (e) bulunur; bu nedenle kelime büyük ünlü uyumuna aykırıdır. Diğer seçeneklerdeki kelimelerin tüm heceleri ya kalın ya da ince ünlülerden oluşur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e9fdb675-f729-47d1-bbe5-047d3406e6ec', 'kalemlik', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e9fdb675-f729-47d1-bbe5-047d3406e6ec', 'yapraklar', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e9fdb675-f729-47d1-bbe5-047d3406e6ec', 'sevgili', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e9fdb675-f729-47d1-bbe5-047d3406e6ec', 'doğrular', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('f744278c-84a8-4419-a9d8-6c69c733e255', 'ffe5c195-5fea-45a3-9030-58f122e0e1ee', 'kolay'::difficulty_level, 'Aşağıdaki kelimelerin hangisinde ünsüz yumuşaması (p, ç, t, k seslerinin yumuşaması) görülür?', 'Ünsüz yumuşaması kuralını örneklerde tespit eder.', '''Ağaç'' kökündeki sert ünsüz ''ç'', ünlüyle başlayan iyelik eki ''-ı'' aldığında yumuşayarak ''c''ye dönüşmüş ve ''ağacı'' biçimini almıştır. Diğer seçeneklerde ünsüzle başlayan ekler geldiği için yumuşama gerçekleşmez.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f744278c-84a8-4419-a9d8-6c69c733e255', 'kitaptan', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f744278c-84a8-4419-a9d8-6c69c733e255', 'ağacı', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f744278c-84a8-4419-a9d8-6c69c733e255', 'sokakta', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f744278c-84a8-4419-a9d8-6c69c733e255', 'çocuktan', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('ab315d8b-0a48-4cdc-9f81-e85cc3a5ae69', 'ffe5c195-5fea-45a3-9030-58f122e0e1ee', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde ünlü düşmesi (hece düşmesi) örneği vardır?', 'Ünlü düşmesi kuralının işlediği kelimeleri cümlede belirler.', '''Burun'' kelimesi ünlüyle başlayan iyelik eki ''-u'' aldığında ikinci hecesindeki dar ünlü ''u'' düşerek ''burnu'' biçimini almıştır. Diğer cümlelerdeki kelimelerde böyle bir ses düşmesi yoktur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ab315d8b-0a48-4cdc-9f81-e85cc3a5ae69', 'Burnu kanayan çocuğu hemen hastaneye götürdüler.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ab315d8b-0a48-4cdc-9f81-e85cc3a5ae69', 'Bahçedeki güller sabaha karşı açmıştı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ab315d8b-0a48-4cdc-9f81-e85cc3a5ae69', 'Kitapları düzenli bir şekilde masaya bıraktı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ab315d8b-0a48-4cdc-9f81-e85cc3a5ae69', 'Sınavdan beklediğinden yüksek bir not aldı.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('5ec0d4c4-9a8c-4ec2-85bc-c086b0a9cabc', 'ffe5c195-5fea-45a3-9030-58f122e0e1ee', 'orta'::difficulty_level, 'Aşağıdaki kelimelerin hangisinde kaynaştırma ünsüzü kullanılmıştır?', 'Kaynaştırma ünsüzlerinin kullanıldığı kelimeleri ayırt eder.', 'Ünlüyle biten ''kapı'' kelimesi ünlüyle başlayan ''-ı'' ekini aldığında iki ünlünün yan yana gelmesini önlemek için araya ''y'' kaynaştırma ünsüzü girmiş ve ''kapıyı'' biçimi oluşmuştur. Diğer seçeneklerdeki ekler ünsüzle başladığı için kaynaştırma ünsüzüne gerek yoktur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('5ec0d4c4-9a8c-4ec2-85bc-c086b0a9cabc', 'kapıyı', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('5ec0d4c4-9a8c-4ec2-85bc-c086b0a9cabc', 'evden', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('5ec0d4c4-9a8c-4ec2-85bc-c086b0a9cabc', 'kitaplar', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('5ec0d4c4-9a8c-4ec2-85bc-c086b0a9cabc', 'sokakta', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('d3de15ed-b24b-4b2d-90e1-5ba7856525af', 'ffe5c195-5fea-45a3-9030-58f122e0e1ee', 'zor'::difficulty_level, 'Aşağıdaki kelimelerden hangisi küçük ünlü uyumuna (düzlük-yuvarlaklık uyumuna) aykırıdır?', 'Küçük ünlü uyumu kuralını ileri düzeyde uygular.', 'Yuvarlak bir ünlüden (o) sonra ancak düz-geniş (a, e) ya da dar-yuvarlak (u, ü) bir ünlü gelebilir; ''doktor'' kelimesinde ise yuvarlak ''o'' ünlüsünden sonra yine geniş-yuvarlak ''o'' geldiği için kural bozulmuştur. Diğer kelimelerin tamamı küçük ünlü uyumuna uygundur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('d3de15ed-b24b-4b2d-90e1-5ba7856525af', 'doktor', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('d3de15ed-b24b-4b2d-90e1-5ba7856525af', 'kuzu', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('d3de15ed-b24b-4b2d-90e1-5ba7856525af', 'çocuk', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('d3de15ed-b24b-4b2d-90e1-5ba7856525af', 'balık', false, 3);
insert into topic_contents (topic_id, summary, content_md, example_question) values ('9683464a-e0ce-493b-ae60-58c924e2ae5c', 'Bu konu; ''de/da'' bağlacı ile hâl eki, ''ki'' bağlacı ile ''-ki'' eki, ''mi'' soru eki ve büyük harf kullanımı gibi en sık karıştırılan yazım kurallarını örneklerle ele alır.', '## ''de/da'' Bağlacı ve Hâl Eki
Bağlaç olan ''de/da'' her zaman ayrı yazılır ve sertleşerek ''te/ta'' biçimini almaz: ''O da bizimle geldi.'' Cümleden çıkarıldığında anlam bütünlüğü bozulmuyorsa bağlaçtır. Bulunma hâli eki olan ''-de/-da'' ise bitişik yazılır ve sert ünsüzden sonra ''-te/-ta'' biçimine sertleşebilir: ''Evde kimse yoktu.'', ''Kitapta ilginç bilgiler vardı.''

## ''mi'' Soru Eki
Soru eki ''mi/mı/mu/mü'' her zaman kendinden önceki kelimeden ayrı yazılır; kendisinden sonra gelen ekler ise bitişik yazılır: ''Geliyor musun?'', ''Bu doğru mudur?''

## ''ki'' Bağlacı ve ''-ki'' Eki
Bağlaç olan ''ki'' ayrı yazılır: ''Biliyordum ki bu iş kolay olmayacak.'' Sıfat yapan ilgi eki ''-ki'' ise bitişik yazılır: ''Sokaktaki çocuklar, benimki, yarınki toplantı.'' ''Hâlbuki, mademki, oysaki, sanki, belki'' gibi kalıplaşmış sözcükler bitişik yazılır; bunlar artık bağlaç ''ki'' olarak değil, tek bir kelime olarak kabul edilir.

## Büyük Harf Kullanımı
Özel adlar (kişi, yer, kurum adları), unvanlardan sonra veya önce gelen özel adlar (Ahmet Bey, Doktor Ayşe), belirli bir tarih bildiren gün ve ay adları (29 Ekim Cumhuriyet Bayramı) büyük harfle başlar. Ancak mevsim adları (ilkbahar, yaz, sonbahar, kış) hiçbir zaman büyük harfle yazılmaz; genel ifadelerde kullanılan gün ve ay adları da (''Her ay toplanırız.'') küçük harfle yazılır.

## Bitişik Yazılan Bazı Yapılar
Anlam kayması olan kalıcı birleşik kelimeler (gecekondu, hanımeli) bitişik yazılır. Yazım kuralları çoğunlukla bir ''çıkarma testi'' ile denetlenir: kelime cümleden çıkarıldığında anlam bozuluyorsa genellikle bir ektir ve bitişik yazılır; anlam bozulmuyorsa genellikle bir bağlaçtır ve ayrı yazılır.', 'Örnek: ''Sen de mi bu işe karıştın?'' cümlesindeki yazım kurallarını değerlendiriniz.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('4fae2e1f-eb50-46df-a94c-90b4fc97acfe', '9683464a-e0ce-493b-ae60-58c924e2ae5c', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde ''de'' bağlaç olarak kullanılmış, bu nedenle ayrı yazılmıştır?', 'Bağlaç olan ''de/da'' ile hâl eki olan ''-de/-da''yı ayırt eder.', 'İkinci cümledeki ''da'', ''O bizimle gelmek istedi.'' cümlesinden çıkarıldığında anlam bütünlüğü bozulmadığı için bağlaçtır ve ayrı yazılır. Diğer cümlelerdeki ''-de'' ekleri isme bulunma hâli katan bir ek olduğu için bitişik yazılmıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4fae2e1f-eb50-46df-a94c-90b4fc97acfe', 'Sende kalan kitabımı getirir misin?', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4fae2e1f-eb50-46df-a94c-90b4fc97acfe', 'O da bizimle gelmek istedi.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4fae2e1f-eb50-46df-a94c-90b4fc97acfe', 'Evde kimse yoktu.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4fae2e1f-eb50-46df-a94c-90b4fc97acfe', 'Bahçede oynayan çocukları gördüm.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('9f55315e-eb8e-4d6a-a157-2a737840506d', '9683464a-e0ce-493b-ae60-58c924e2ae5c', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde ''ki'' bağlaç olarak kullanılmış ve bu nedenle ayrı yazılmıştır?', 'Bağlaç ''ki'' ile sıfat yapan ''-ki'' ekini ayırt eder.', 'İkinci cümlede ''ki'', iki cümleyi birbirine bağlayan bir bağlaçtır ve ayrı yazılır. Diğer cümlelerde ''-ki'', isme sıfat ya da ilgi zamiri işlevi kazandıran bir ek olduğu için bitişik yazılmıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9f55315e-eb8e-4d6a-a157-2a737840506d', 'Sokaktaki çocuklar top oynuyordu.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9f55315e-eb8e-4d6a-a157-2a737840506d', 'Biliyordum ki bu iş kolay olmayacaktı.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9f55315e-eb8e-4d6a-a157-2a737840506d', 'Benimki masanın üzerinde duruyor.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9f55315e-eb8e-4d6a-a157-2a737840506d', 'Yarınki toplantıya katılamayacağım.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('8d3b10e5-76d1-4a24-8954-9c3fd76b0e50', '9683464a-e0ce-493b-ae60-58c924e2ae5c', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir yazım yanlışı vardır?', '''-ki'' ekinin bitişik yazılması gereken durumları fark eder.', '''Yarın'' kelimesine gelen sıfat yapan ''-ki'' eki bitişik yazılmalıdır; doğru yazım ''yarınki'' biçimindedir. Diğer cümlelerdeki yazımlar kurallara uygundur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8d3b10e5-76d1-4a24-8954-9c3fd76b0e50', 'Yarın ki sınava çalışmalıyım.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8d3b10e5-76d1-4a24-8954-9c3fd76b0e50', 'Sokaktaki köpek durmadan havlıyordu.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8d3b10e5-76d1-4a24-8954-9c3fd76b0e50', 'O da toplantıya katılacağını söyledi.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8d3b10e5-76d1-4a24-8954-9c3fd76b0e50', 'Kitaptaki resimleri çok beğendim.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('7ff5297e-38ac-4dd0-90b8-7d5cf0bb037d', '9683464a-e0ce-493b-ae60-58c924e2ae5c', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde büyük harf kullanımıyla ilgili bir yanlışlık vardır?', 'Mevsim adlarının büyük harfle yazılmadığı kuralını uygular.', 'Mevsim adları hiçbir zaman büyük harfle başlamaz; bu nedenle ''ilkbahar'' kelimesi küçük harfle yazılmalıdır. Diğer cümlelerdeki büyük harf kullanımları (unvan, özel gün adı, dil adı) doğrudur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('7ff5297e-38ac-4dd0-90b8-7d5cf0bb037d', 'Bu yıl İlkbahar çok erken geldi.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('7ff5297e-38ac-4dd0-90b8-7d5cf0bb037d', 'Ahmet Bey toplantıya geç kaldı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('7ff5297e-38ac-4dd0-90b8-7d5cf0bb037d', '29 Ekim Cumhuriyet Bayramı''nı coşkuyla kutladık.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('7ff5297e-38ac-4dd0-90b8-7d5cf0bb037d', 'Türkçe dersinde güzel bir şiir okuduk.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('70a7a661-b3e9-4c6e-9908-3d6d210de2bc', '9683464a-e0ce-493b-ae60-58c924e2ae5c', 'zor'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir yazım yanlışı yoktur?', 'Birden fazla yazım kuralını bir arada değerlendirerek doğru cümleyi belirler.', 'İkinci cümlede bağlaç olan ''de'' doğru biçimde ayrı, soru eki ''mi'' de kurala uygun olarak ayrı yazılmıştır. Diğer cümlelerde sırasıyla ''kitapta'' yerine ''kitapda'', ''yarınki'' yerine ''yarın ki'' ve ''onunki'' yerine ''onun ki'' kullanılarak yazım yanlışı yapılmıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('70a7a661-b3e9-4c6e-9908-3d6d210de2bc', 'Kitapda ne yazdığını çok merak ediyorum.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('70a7a661-b3e9-4c6e-9908-3d6d210de2bc', 'Sen de mi bu işe karıştın?', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('70a7a661-b3e9-4c6e-9908-3d6d210de2bc', 'Yarın ki toplantıyı sakın unutma.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('70a7a661-b3e9-4c6e-9908-3d6d210de2bc', 'Herkes onun ki kadar başarılı olamadı.', false, 3);
insert into topic_contents (topic_id, summary, content_md, example_question) values ('4d4e66fa-6b06-4194-a222-0ed30c0edd1b', 'Virgül, iki nokta, noktalı virgül, kesme işareti, üç nokta ve ünlem işaretinin doğru kullanım kurallarını örneklerle açıklayan bu konu, noktalama hatalarını ayırt etmeyi hedefler.', '## Virgül (,)
Eş görevli kelime veya kelime gruplarını sıralarken kullanılır: ''Çarşıdan elma, armut, muz ve şeftali aldı.'' Sıralı cümleleri, ara sözleri ve hitap sözlerini ayırmak için de virgül konur. ''Ve'' bağlacından hemen önce genellikle virgül kullanılmaz.

## İki Nokta (:)
Kendisinden sonra örnek verilecek, açıklama yapılacak ya da bir liste sıralanacak cümlenin sonuna konur: ''Kırtasiyeden şunları aldım: kalem, silgi, defter.'' Ayrıca alıntı sözlerden önce de kullanılır: ''Öğretmenimiz: ''Yarın sınav var.'' dedi.''

## Noktalı Virgül (;)
Virgüllerle ayrılmış öğe gruplarını birbirinden ayırmak için ya da bağlaç kullanılmadan birbirine bağlı cümleleri ayırmak için kullanılır: ''Sınıfta Ali, Veli, Ayşe; bahçede ise Mehmet, Fatma vardı.''

## Kesme İşareti ('')
Özel isimlere getirilen çekim eklerini ayırmak için kullanılır: ''İstanbul''da, Ahmet''in, Türkiye''ye.'' Cins (tür bildiren) isimlere gelen ekler kesme işaretiyle ayrılmaz: ''kalemi, öğretmene, kitabı'' gibi.

## Üç Nokta (...)
Tamamlanmamış cümlelerin sonuna, sözün bir yerde kesildiğini göstermek için ya da kaba sayılan sözlerin yerine kullanılır.

## Ünlem İşareti (!)
Sevinç, kızgınlık, korku, şaşkınlık gibi güçlü duyguları anlatan cümlelerin ve seslenme sözlerinin sonuna konur: ''Ne güzel bir manzara!''

Doğru noktalama, hem okunabilirliği artırır hem de cümlenin anlamını netleştirir; bu nedenle KPSS''de noktalama işaretlerinin yerinde kullanılıp kullanılmadığı sıkça sorulur.', 'Örnek: ''Öğretmenimiz Yarın sınav var dedi.'' cümlesinde hangi noktalama işaretleri eksiktir?') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('cfe4766a-995c-479b-9dbc-ab6a1f01784d', '4d4e66fa-6b06-4194-a222-0ed30c0edd1b', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde kesme işareti ('') doğru kullanılmıştır?', 'Kesme işaretinin özel isimlere gelen eklerde kullanıldığını kavrar.', '''Ahmet'' bir özel isim olduğu için aldığı ''-in'' eki kesme işaretiyle ayrılmıştır. Diğer seçeneklerdeki ''kalem, öğretmen, kitap'' cins isim olduğundan aldıkları ekler kesme işaretiyle ayrılmaz.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('cfe4766a-995c-479b-9dbc-ab6a1f01784d', 'Ahmet''in kitabını dün akşam okudum.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('cfe4766a-995c-479b-9dbc-ab6a1f01784d', 'Kalem''imi masanın üstünde unuttum.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('cfe4766a-995c-479b-9dbc-ab6a1f01784d', 'Öğretmen''e ödevimi teslim ettim.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('cfe4766a-995c-479b-9dbc-ab6a1f01784d', 'Kitab''ı çantama koydum.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('9d38f7dc-0de1-4785-8c5f-98319e6503ad', '4d4e66fa-6b06-4194-a222-0ed30c0edd1b', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde virgül (,) doğru bir yerde kullanılmıştır?', 'Sıralama bildiren cümlelerde virgülün doğru kullanımını uygular.', 'Eş görevli kelimeler olan ''elma, armut, muz'' birbirinden virgülle ayrılmış, son öğeden önce ''ve'' bağlacı kullanıldığı için virgüle gerek duyulmamıştır. Diğer seçeneklerde virgüller anlamsız ya da gereksiz yerlere konmuştur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9d38f7dc-0de1-4785-8c5f-98319e6503ad', 'Çarşıdan elma, armut, muz ve şeftali aldı.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9d38f7dc-0de1-4785-8c5f-98319e6503ad', 'Çarşıdan, elma armut muz ve şeftali aldı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9d38f7dc-0de1-4785-8c5f-98319e6503ad', 'Çarşıdan elma armut, muz ve, şeftali aldı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9d38f7dc-0de1-4785-8c5f-98319e6503ad', 'Çarşıdan elma armut muz, ve şeftali, aldı.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('4dd6a8ba-8bb4-4594-bd2b-5ce1855546f2', '4d4e66fa-6b06-4194-a222-0ed30c0edd1b', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde iki nokta (:) doğru kullanılmıştır?', 'İki noktanın örnek/liste verme işlevini kavrar.', 'Birinci cümlede iki nokta, kendisinden sonra bir liste (örnek) sıralanacağını haber verdiği için doğru kullanılmıştır. Diğer cümlelerde iki noktayı gerektiren bir açıklama ya da örnekleme durumu yoktur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4dd6a8ba-8bb4-4594-bd2b-5ce1855546f2', 'Kırtasiyeden şunları aldım: kalem, silgi, defter.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4dd6a8ba-8bb4-4594-bd2b-5ce1855546f2', 'Yarın: erken kalkıp işe gideceğim.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4dd6a8ba-8bb4-4594-bd2b-5ce1855546f2', 'Bahçede: çiçekler yeni açmıştı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4dd6a8ba-8bb4-4594-bd2b-5ce1855546f2', 'O gün: eve oldukça geç geldi.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('cdc7b08d-5cec-4ebe-a618-f5faee9f0331', '4d4e66fa-6b06-4194-a222-0ed30c0edd1b', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde noktalı virgül (;) doğru kullanılmıştır?', 'Noktalı virgülün virgüllerle ayrılmış öğe gruplarını ayırma işlevini uygular.', 'Birinci cümlede virgüllerle ayrılmış iki farklı kişi grubu (''Ali, Veli, Ayşe'' ve ''Mehmet, Fatma'') noktalı virgülle birbirinden ayrılmıştır. Diğer cümlelerde noktalı virgül gereksiz yere, herhangi bir öğe grubunu ayırmadan kullanılmıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('cdc7b08d-5cec-4ebe-a618-f5faee9f0331', 'Sınıfta Ali, Veli, Ayşe; bahçede ise Mehmet, Fatma vardı.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('cdc7b08d-5cec-4ebe-a618-f5faee9f0331', 'Bu kitabı; okuyup çok beğendim.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('cdc7b08d-5cec-4ebe-a618-f5faee9f0331', 'Yarın; erkenden okula gideceğim.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('cdc7b08d-5cec-4ebe-a618-f5faee9f0331', 'Akşam; ailecek yemek yedik.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('95bcc103-0280-415a-bab1-59613765dece', '4d4e66fa-6b06-4194-a222-0ed30c0edd1b', 'zor'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde noktalama işaretlerinin tamamı doğru kullanılmıştır?', 'Birden fazla noktalama kuralını bir arada değerlendirerek doğru cümleyi seçer.', 'İkinci cümlede iki nokta, kendisinden sonra gelen alıntı sözden önce doğru biçimde kullanılmış, tırnak içindeki alıntı da doğru noktalanmıştır. Diğer cümlelerde noktalı virgül gereksiz yere kullanılmış ya da ''masadaki'' kelimesine yanlışlıkla kesme işareti eklenmiştir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('95bcc103-0280-415a-bab1-59613765dece', 'Ahmet''e, İstanbul''dan gelen; mektubu hemen verdim.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('95bcc103-0280-415a-bab1-59613765dece', 'Öğretmenimiz: ''Yarın sınav var.'' dedi.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('95bcc103-0280-415a-bab1-59613765dece', 'Masada''ki kitapları, düzenle dedi.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('95bcc103-0280-415a-bab1-59613765dece', 'Çarşıya gidip; elma, armut aldım.', false, 3);
commit;
