begin;
insert into topic_contents (topic_id, summary, content_md, example_question) values ('9683464a-e0ce-493b-ae60-58c924e2ae5c', 'Bu konu; ''de/da'' bağlacı ile hâl eki, ''ki'' bağlacı ile ''-ki'' eki, ''mi'' soru eki ve büyük harf kullanımı gibi en sık karıştırılan yazım kurallarını örneklerle ele alır.', '## ''de/da'' Bağlacı ve Hâl Eki
Bağlaç olan ''de/da'' her zaman ayrı yazılır ve sertleşerek ''te/ta'' biçimini almaz: ''O da bizimle geldi.'' Cümleden çıkarıldığında anlam bütünlüğü bozulmuyorsa bağlaçtır. Bulunma hâli eki olan ''-de/-da'' ise bitişik yazılır ve sert ünsüzden sonra ''-te/-ta'' biçimine sertleşebilir: ''Evde kimse yoktu.'', ''Kitapta ilginç bilgiler vardı.''

## ''mi'' Soru Eki
Soru eki ''mi/mı/mu/mü'' her zaman kendinden önceki kelimeden ayrı yazılır; kendisinden sonra gelen ekler ise bitişik yazılır: ''Geliyor musun?'', ''Bu doğru mudur?''

## ''ki'' Bağlacı ve ''-ki'' Eki
Bağlaç olan ''ki'' ayrı yazılır: ''Biliyordum ki bu iş kolay olmayacak.'' Sıfat yapan ilgi eki ''-ki'' ise bitişik yazılır: ''Sokaktaki çocuklar, benimki, yarınki toplantı.'' ''Hâlbuki, mademki, oysaki, sanki, belki'' gibi kalıplaşmış sözcükler bitişik yazılır; bunlar artık bağlaç ''ki'' olarak değil, tek bir kelime olarak kabul edilir.

## Büyük Harf Kullanımı
Özel adlar (kişi, yer, kurum adları), unvanlardan sonra veya önce gelen özel adlar (Ahmet Bey, Doktor Ayşe), belirli bir tarih bildiren gün ve ay adları (29 Ekim Cumhuriyet Bayramı) büyük harfle başlar. Ancak mevsim adları (ilkbahar, yaz, sonbahar, kış) hiçbir zaman büyük harfle yazılmaz; genel ifadelerde kullanılan gün ve ay adları da (''Her ay toplanırız.'') küçük harfle yazılır.

## Bitişik Yazılan Bazı Yapılar
Anlam kayması olan kalıcı birleşik kelimeler (gecekondu, hanımeli) bitişik yazılır. Yazım kuralları çoğunlukla bir ''çıkarma testi'' ile denetlenir: kelime cümleden çıkarıldığında anlam bozuluyorsa genellikle bir ektir ve bitişik yazılır; anlam bozulmuyorsa genellikle bir bağlaçtır ve ayrı yazılır.', 'Örnek: ''Sen de mi bu işe karıştın?'' cümlesindeki yazım kurallarını değerlendiriniz.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('4fae2e1f-eb50-46df-a94c-90b4fc97acfe', '9683464a-e0ce-493b-ae60-58c924e2ae5c', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde ''de'' bağlaç olarak kullanılmış, bu nedenle ayrı yazılmıştır?', 'Bağlaç olan ''de/da'' ile hâl eki olan ''-de/-da''yı ayırt eder.', 'İkinci cümledeki ''da'', ''O bizimle gelmek istedi.'' cümlesinden çıkarıldığında anlam bütünlüğü bozulmadığı için bağlaçtır ve ayrı yazılır. Diğer cümlelerdeki ''-de'' ekleri isme bulunma hâli katan bir ek olduğu için bitişik yazılmıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4fae2e1f-eb50-46df-a94c-90b4fc97acfe', 'Sende kalan kitabımı getirir misin?', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4fae2e1f-eb50-46df-a94c-90b4fc97acfe', 'O da bizimle gelmek istedi.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4fae2e1f-eb50-46df-a94c-90b4fc97acfe', 'Evde kimse yoktu.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4fae2e1f-eb50-46df-a94c-90b4fc97acfe', 'Bahçede oynayan çocukları gördüm.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('9f55315e-eb8e-4d6a-a157-2a737840506d', '9683464a-e0ce-493b-ae60-58c924e2ae5c', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde ''ki'' bağlaç olarak kullanılmış ve bu nedenle ayrı yazılmıştır?', 'Bağlaç ''ki'' ile sıfat yapan ''-ki'' ekini ayırt eder.', 'İkinci cümlede ''ki'', iki cümleyi birbirine bağlayan bir bağlaçtır ve ayrı yazılır. Diğer cümlelerde ''-ki'', isme sıfat ya da ilgi zamiri işlevi kazandıran bir ek olduğu için bitişik yazılmıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9f55315e-eb8e-4d6a-a157-2a737840506d', 'Sokaktaki çocuklar top oynuyordu.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9f55315e-eb8e-4d6a-a157-2a737840506d', 'Biliyordum ki bu iş kolay olmayacaktı.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9f55315e-eb8e-4d6a-a157-2a737840506d', 'Benimki masanın üzerinde duruyor.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9f55315e-eb8e-4d6a-a157-2a737840506d', 'Yarınki toplantıya katılamayacağım.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('8d3b10e5-76d1-4a24-8954-9c3fd76b0e50', '9683464a-e0ce-493b-ae60-58c924e2ae5c', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir yazım yanlışı vardır?', '''-ki'' ekinin bitişik yazılması gereken durumları fark eder.', '''Yarın'' kelimesine gelen sıfat yapan ''-ki'' eki bitişik yazılmalıdır; doğru yazım ''yarınki'' biçimindedir. Diğer cümlelerdeki yazımlar kurallara uygundur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8d3b10e5-76d1-4a24-8954-9c3fd76b0e50', 'Yarın ki sınava çalışmalıyım.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8d3b10e5-76d1-4a24-8954-9c3fd76b0e50', 'Sokaktaki köpek durmadan havlıyordu.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8d3b10e5-76d1-4a24-8954-9c3fd76b0e50', 'O da toplantıya katılacağını söyledi.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8d3b10e5-76d1-4a24-8954-9c3fd76b0e50', 'Kitaptaki resimleri çok beğendim.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('7ff5297e-38ac-4dd0-90b8-7d5cf0bb037d', '9683464a-e0ce-493b-ae60-58c924e2ae5c', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde büyük harf kullanımıyla ilgili bir yanlışlık vardır?', 'Mevsim adlarının büyük harfle yazılmadığı kuralını uygular.', 'Mevsim adları hiçbir zaman büyük harfle başlamaz; bu nedenle ''ilkbahar'' kelimesi küçük harfle yazılmalıdır. Diğer cümlelerdeki büyük harf kullanımları (unvan, özel gün adı, dil adı) doğrudur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('7ff5297e-38ac-4dd0-90b8-7d5cf0bb037d', 'Bu yıl İlkbahar çok erken geldi.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('7ff5297e-38ac-4dd0-90b8-7d5cf0bb037d', 'Ahmet Bey toplantıya geç kaldı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('7ff5297e-38ac-4dd0-90b8-7d5cf0bb037d', '29 Ekim Cumhuriyet Bayramı''nı coşkuyla kutladık.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('7ff5297e-38ac-4dd0-90b8-7d5cf0bb037d', 'Türkçe dersinde güzel bir şiir okuduk.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('70a7a661-b3e9-4c6e-9908-3d6d210de2bc', '9683464a-e0ce-493b-ae60-58c924e2ae5c', 'zor'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir yazım yanlışı yoktur?', 'Birden fazla yazım kuralını bir arada değerlendirerek doğru cümleyi belirler.', 'İkinci cümlede bağlaç olan ''de'' doğru biçimde ayrı, soru eki ''mi'' de kurala uygun olarak ayrı yazılmıştır. Diğer cümlelerde sırasıyla ''kitapta'' yerine ''kitapda'', ''yarınki'' yerine ''yarın ki'' ve ''onunki'' yerine ''onun ki'' kullanılarak yazım yanlışı yapılmıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('70a7a661-b3e9-4c6e-9908-3d6d210de2bc', 'Kitapda ne yazdığını çok merak ediyorum.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('70a7a661-b3e9-4c6e-9908-3d6d210de2bc', 'Sen de mi bu işe karıştın?', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('70a7a661-b3e9-4c6e-9908-3d6d210de2bc', 'Yarın ki toplantıyı sakın unutma.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('70a7a661-b3e9-4c6e-9908-3d6d210de2bc', 'Herkes onun ki kadar başarılı olamadı.', false, 3);
commit;