begin;
insert into topic_contents (topic_id, summary, content_md, example_question) values ('d36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'Gerçek, mecaz, yan ve terim anlam ile eş anlam, zıt anlam, sesteşlik ve deyimlerin cümle içindeki kullanımını örneklerle işleyen sözcükte anlam konusu.', '## Gerçek (Temel) Anlam ve Mecaz Anlam
Bir kelimenin ilk akla gelen, sözlükteki asıl anlamına gerçek (temel) anlam denir: ''Bu çanta çok ağırdı.'' Kelimenin benzetme yoluyla kazandığı, gerçek anlamından uzaklaşmış anlamına ise mecaz anlam denir: ''Sınav soruları oldukça ağırdı.'' (zor anlamında)

## Yan Anlam ve Terim Anlam
Bir kelimenin temel anlamıyla ilgili fakat ondan biraz uzaklaşmış anlamına yan anlam denir: ''Masanın ayağı kırıldı.'' Bir bilim, sanat veya meslek dalına özgü kavramı karşılayan anlama ise terim anlam denir: ''Bu cümlenin öznesini bulun.'' veya ''Kelimenin kökünü belirleyin.''

## Eş Anlam (Anlamdaş) ve Zıt Anlam (Karşıt)
Yazılışları farklı, anlamları aynı veya çok yakın olan kelimelere eş anlamlı (anlamdaş) denir: ''kara-siyah, misafir-konuk.'' Birbirinin karşıtı olan kelimelere ise zıt anlamlı (karşıt) denir: ''büyük-küçük, sıcak-soğuk.''

## Eş Sesli (Sesteş) Kelimeler
Yazılışları aynı, anlamları farklı kelimelere sesteş (eş sesli) denir: ''Yüzünde bir gülümseme vardı.'' (yüz=çehre) ile ''Denizde saatlerce yüzdü.'' (yüz=yüzmek eylemi) cümlelerindeki ''yüz'' kelimeleri sesteştir.

## Deyimler
İki veya daha fazla kelimeden oluşan, çoğunlukla mecazlı anlam taşıyan kalıplaşmış söz gruplarına deyim denir: ''eli kulağında'' (bir işin bitmesine az kalmış olması), ''içi kararmak'' (çok üzülmek). Deyimler, cümle içinde kalıplaşmış anlamlarıyla ve bu anlama uygun bağlamda kullanılmalıdır; anlamına ters düşen bir bağlamda kullanılması anlatım bozukluğuna yol açar.', '''Eli kulağında'' deyimi aşağıdaki cümlelerin hangisinde doğru kullanılmıştır?') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('0795d713-db0e-4468-9e84-0bc3deb45ff6', 'd36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde ''ağır'' sözcüğü mecaz anlamda kullanılmıştır?', 'Gerçek anlam ile mecaz anlamı ayırt eder.', 'İkinci cümlede ''ağır'' sözcüğü fiziksel bir ağırlığı değil, ''zor, çetin'' anlamını karşıladığı için mecaz anlamda kullanılmıştır. Diğer cümlelerde ''ağır'' sözcüğü nesnenin gerçek fiziksel ağırlığını belirtir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0795d713-db0e-4468-9e84-0bc3deb45ff6', 'Bu çanta gerçekten çok ağırdı.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0795d713-db0e-4468-9e84-0bc3deb45ff6', 'Sınav soruları oldukça ağırdı.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0795d713-db0e-4468-9e84-0bc3deb45ff6', 'Valizi taşırken sırtım ağrıdı, çünkü çok ağırdı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0795d713-db0e-4468-9e84-0bc3deb45ff6', 'Demir, ağır bir madendir.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('bdd3a383-6a62-407e-b95a-9100cae1f16f', 'd36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'kolay'::difficulty_level, 'Aşağıdaki kelime çiftlerinden hangisi eş anlamlıdır (anlamdaştır)?', 'Eş anlamlı (anlamdaş) kelimeleri tanır.', '''Kara'' ve ''siyah'' kelimeleri aynı rengi karşıladığı için eş anlamlıdır. Diğer seçeneklerdeki kelime çiftleri ise birbirinin zıt anlamlısıdır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('bdd3a383-6a62-407e-b95a-9100cae1f16f', 'kara - siyah', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('bdd3a383-6a62-407e-b95a-9100cae1f16f', 'büyük - küçük', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('bdd3a383-6a62-407e-b95a-9100cae1f16f', 'sıcak - soğuk', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('bdd3a383-6a62-407e-b95a-9100cae1f16f', 'ışık - karanlık', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('9ea4593a-800e-4762-8461-d68417b848c9', 'd36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'orta'::difficulty_level, '''Eli kulağında'' deyimi aşağıdaki cümlelerin hangisinde doğru kullanılmıştır?', 'Deyimlerin cümle içindeki uygun kullanımını değerlendirir.', '''Eli kulağında'' deyimi bir işin bitmesine çok az kaldığını anlatır; birinci cümlede projenin yakında tamamlanacağı belirtildiği için deyim doğru bağlamda kullanılmıştır. Diğer cümlelerde deyimin anlamıyla cümlenin geri kalanı çelişmektedir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9ea4593a-800e-4762-8461-d68417b848c9', 'Proje eli kulağında, birkaç güne kadar tamamlanmış olacak.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9ea4593a-800e-4762-8461-d68417b848c9', 'Bu iş eli kulağında, çünkü daha yeni başladık.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9ea4593a-800e-4762-8461-d68417b848c9', 'O her zaman eli kulağında biriydi.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9ea4593a-800e-4762-8461-d68417b848c9', 'Param eli kulağında bittiği için borç almak zorunda kaldım.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('b440292a-29b7-4b81-a2c0-44e35af73468', 'd36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde ''yüz'' sözcüğü diğerlerinden farklı bir anlamda (sesteş olarak) kullanılmıştır?', 'Sesteş (eş sesli) kelimeleri cümle bağlamında ayırt eder.', 'İkinci cümlede ''yüzdü'', ''yüzmek'' eyleminden gelir ve suda hareket etmeyi ifade eder; diğer cümlelerdeki ''yüz'' ise ''çehre, surat'' anlamındaki isimdir. Yazılışları aynı fakat anlamları farklı olduğu için bu kelimeler sesteştir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b440292a-29b7-4b81-a2c0-44e35af73468', 'Yüzünde güzel bir gülümseme vardı.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b440292a-29b7-4b81-a2c0-44e35af73468', 'Denizde saatlerce yüzdü.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b440292a-29b7-4b81-a2c0-44e35af73468', 'Yüzü hafif kızarmıştı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b440292a-29b7-4b81-a2c0-44e35af73468', 'Onun yüzüne bakamadım.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('82b36052-73e0-4ffc-81d8-d2a76a0946e8', 'd36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'zor'::difficulty_level, '''Kök'' sözcüğü aşağıdaki cümlelerin hangisinde terim anlamda (dil bilgisi terimi olarak) kullanılmıştır?', 'Terim anlamı gerçek ve mecaz anlamdan ayırt eder.', 'İkinci cümlede ''kök'', bir kelimenin anlam taşıyan en küçük parçasını belirten dil bilgisi terimi olarak kullanılmıştır. Diğer cümlelerde ''kök'' sözcüğü sırasıyla gerçek anlamda (bitki kökü) ve mecaz anlamda (kaynak, köken) kullanılmıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('82b36052-73e0-4ffc-81d8-d2a76a0946e8', 'Bahçedeki ağacın kökü çok derinlere inmişti.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('82b36052-73e0-4ffc-81d8-d2a76a0946e8', 'Bu kelimenin kökü Arapçadır.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('82b36052-73e0-4ffc-81d8-d2a76a0946e8', 'Sorunun kökünü araştırmalıyız.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('82b36052-73e0-4ffc-81d8-d2a76a0946e8', 'Bu ailenin kökleri çok eskiye dayanıyor.', false, 3);
commit;