begin;
insert into topic_contents (topic_id, summary, content_md, example_question) values ('eb6df17f-05d4-49df-b626-ba5d585672a9', 'Anlatım bozukluğu türlerini (gereksiz sözcük, çelişki, mantık hatası, tamlama yanlışlığı), öznel-nesnel yargı ayrımını ve cümle tamamlamayı örneklerle açıklayan konu.', '## Anlatım Bozukluğu Türleri
Anlatım bozukluğu, bir cümlede anlam veya dil bilgisi açısından ortaya çıkan hatalardır. Başlıca türleri:
- **Gereksiz sözcük kullanımı:** Aynı anlama gelen iki kelimenin bir arada kullanılması. ''Bu haber beni hem çok sevindirdi hem de mutlu etti.'' (sevindirmek ve mutlu etmek eş anlamlıdır, biri gereksizdir.)
- **Çelişki:** Cümledeki iki ifadenin birbiriyle çelişmesi. ''Belki de bu sınavı kesinlikle kazanacak.'' (''belki'' ihtimal, ''kesinlikle'' kesinlik bildirir; bir arada kullanılamaz.)
- **Mantık (neden-sonuç) hatası:** Cümledeki neden ile sonucun birbiriyle uyuşmaması. ''Param olmadığı için kitabı alamadım ama yine de aldım.''
- **Tamlama yanlışlığı:** Ortak kullanılan bir öğeye ait ekin eksik bırakılması. ''Ali ve babasının arabası kaza yaptı.'' cümlesinde ''Ali'' kelimesinden sonra ''-nin'' tamlayan eki eksiktir; doğrusu ''Ali''nin ve babasının arabası'' olmalıdır.

## Öznel Yargı ve Nesnel Yargı
Nesnel yargı, kişiden kişiye değişmeyen, kanıtlanabilir, gözlemlenebilir bilgi içeren yargıdır: ''Roman 320 sayfadan oluşmaktadır.'' Öznel yargı ise kişisel görüş, beğeni ya da yorum içerir ve kişiden kişiye değişebilir: ''Bence bu roman çok sıkıcıydı.'' ''En, en güzel, bence, bana göre, sanırım'' gibi ifadeler genellikle öznelliğin işaretidir.

## Cümle Tamamlama
Bir cümlenin ya da paragrafın bağlamına en uygun ifadeyi seçmek, cümledeki anlam bütünlüğünü ve mantıksal akışı bozmayan seçeneği bulmayı gerektirir. Doğru seçenek, metinde verilen bilgilerle çelişmemeli ve konu dışına çıkmamalıdır.', '''Belki de bu sınavı kesinlikle kazanacak.'' cümlesindeki anlatım bozukluğunun türünü belirtiniz.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('55380dbf-5554-4bed-b96b-68de47743b6c', 'eb6df17f-05d4-49df-b626-ba5d585672a9', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisi nesnel bir yargı bildirmektedir?', 'Öznel yargı ile nesnel yargıyı ayırt eder.', 'Birinci cümlede sayfa sayısı, kişiden kişiye değişmeyen, kanıtlanabilir bir bilgi olduğu için nesneldir. Diğer cümleler kişisel görüş ve beğeni içerdiğinden özneldir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('55380dbf-5554-4bed-b96b-68de47743b6c', 'Roman, 320 sayfadan oluşmaktadır.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('55380dbf-5554-4bed-b96b-68de47743b6c', 'Bence bu roman çok sıkıcıydı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('55380dbf-5554-4bed-b96b-68de47743b6c', 'Yazarın en başarılı eseri budur.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('55380dbf-5554-4bed-b96b-68de47743b6c', 'Bu film gelmiş geçmiş en iyi yapımdı.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('4830d69f-8d8c-4322-b5f1-d8b8d94e757c', 'eb6df17f-05d4-49df-b626-ba5d585672a9', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir anlatım bozukluğu vardır?', 'Gereksiz sözcük kullanımından kaynaklanan anlatım bozukluğunu fark eder.', '''Sevindirmek'' ve ''mutlu etmek'' aynı anlama geldiği için bu iki ifadenin bir arada kullanılması gereksiz tekrara, dolayısıyla anlatım bozukluğuna yol açmıştır. Diğer cümlelerde böyle bir tekrar yoktur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4830d69f-8d8c-4322-b5f1-d8b8d94e757c', 'Bu haber beni hem çok sevindirdi hem de mutlu etti.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4830d69f-8d8c-4322-b5f1-d8b8d94e757c', 'Öğrenciler sınava iyi hazırlandı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4830d69f-8d8c-4322-b5f1-d8b8d94e757c', 'Kitabı okuyup arkadaşına anlattı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4830d69f-8d8c-4322-b5f1-d8b8d94e757c', 'Yağmur yağınca sokaklar ıslandı.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('5328392f-cca6-4ec6-b191-57016dbf0465', 'eb6df17f-05d4-49df-b626-ba5d585672a9', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir anlatım bozukluğu vardır?', 'Çelişkiden kaynaklanan anlatım bozukluğunu tespit eder.', '''Belki'' ihtimal, ''kesinlikle'' ise kesinlik bildirir; bu iki ifade anlamca birbiriyle çeliştiği için cümlede anlatım bozukluğu vardır. Diğer cümlelerde böyle bir çelişki bulunmamaktadır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('5328392f-cca6-4ec6-b191-57016dbf0465', 'Belki de bu sınavı kesinlikle kazanacak.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('5328392f-cca6-4ec6-b191-57016dbf0465', 'Öğretmen konuyu tekrar anlattı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('5328392f-cca6-4ec6-b191-57016dbf0465', 'Sabah erkenden yola çıktık.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('5328392f-cca6-4ec6-b191-57016dbf0465', 'Kitapları düzenli bir şekilde raflara yerleştirdi.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('03e85f88-3b18-4ec7-8cca-81516ec12923', 'eb6df17f-05d4-49df-b626-ba5d585672a9', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir anlatım bozukluğu vardır?', 'Neden-sonuç ilişkisindeki mantık hatasını fark eder.', 'Cümlede önce parası olmadığı için kitabı alamadığı söylenmiş, ardından yine de aldığı belirtilerek çelişkili bir mantık hatası oluşturulmuştur. Diğer cümlelerde neden ile sonuç arasında tutarlı bir ilişki vardır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('03e85f88-3b18-4ec7-8cca-81516ec12923', 'Param olmadığı için kitabı alamadım ama yine de aldım.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('03e85f88-3b18-4ec7-8cca-81516ec12923', 'Erken kalktığım için derse zamanında yetiştim.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('03e85f88-3b18-4ec7-8cca-81516ec12923', 'Yorgun olduğu için erken yattı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('03e85f88-3b18-4ec7-8cca-81516ec12923', 'Kitabı bitirince bana geri verdi.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('1a58e075-3dbb-4bc1-a1a1-6f2831c360aa', 'eb6df17f-05d4-49df-b626-ba5d585672a9', 'zor'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir anlatım bozukluğu vardır?', 'Tamlama yanlışlığından kaynaklanan anlatım bozukluğunu ileri düzeyde tespit eder.', '''Ali'' kelimesinden sonra tamlayan eki ''-nin'' eksik bırakıldığı için cümlede tamlama yanlışlığı vardır; doğrusu ''Ali''nin ve babasının arabası'' biçiminde olmalıdır. Diğer cümlelerde böyle bir ek eksikliği yoktur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1a58e075-3dbb-4bc1-a1a1-6f2831c360aa', 'Ali ve babasının arabası kaza yaptı.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1a58e075-3dbb-4bc1-a1a1-6f2831c360aa', 'Ali''nin ve babasının arabası kaza yaptı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1a58e075-3dbb-4bc1-a1a1-6f2831c360aa', 'Öğrenciler sınıfa girdi ve yerlerine oturdu.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1a58e075-3dbb-4bc1-a1a1-6f2831c360aa', 'Yağmur dinince hep birlikte dışarı çıktık.', false, 3);
commit;