begin;
insert into topic_contents (topic_id, summary, content_md, example_question) values ('f884a167-9e40-4c5c-bc29-810eb13f200e', 'Paragrafta ana düşünce ve yardımcı düşünceyi ayırt etme, paragraf tamamlama ve metinden çıkarılabilecek/çıkarılamayacak yargıları belirleme becerilerini işleyen konu.', '## Konu ve Ana Düşünce
Bir paragrafın neyle ilgili olduğunu belirten kavrama konu denir; yazarın bu konu hakkında okura iletmek istediği asıl mesaja ise ana düşünce denir. Ana düşünce genellikle paragrafın son cümlesinde, bazen de ilk cümlesinde yer alır ve paragraftaki tüm cümleleri kapsayan bir yargı niteliğindedir.

## Yardımcı Düşünce
Ana düşünceyi destekleyen, açıklayan veya örnekleyen düşüncelere yardımcı düşünce denir. Bir paragrafta birden fazla yardımcı düşünce bulunabilir, ancak ana düşünce tektir.

## Paragraf Tamamlama
Paragrafın başına, ortasına ya da sonuna getirilecek cümle; paragrafın anlam bütünlüğünü, konu akışını ve mantık örgüsünü bozmamalıdır. Başa gelecek cümle genellikle konuyu tanıtır; sona gelecek cümle ise paragrafta anlatılanların bir sonucu, genellemesi ya da tamamlayıcısı niteliğinde olmalıdır. Doğru seçenek metindeki bilgilerle çelişmemeli ve konu dışına çıkmamalıdır.

## Metinden Çıkarılabilecek Yargılar
''Bu parçadan hangi yargıya ulaşılabilir/ulaşılamaz'' tipi sorularda, seçeneklerin metinde açıkça ifade edilen ya da metinden mantıksal olarak çıkarılabilen bilgilerle örtüşüp örtüşmediğine bakılır. Metinde yer almayan, aşırı genelleme içeren ya da metinle çelişen seçenekler yanlıştır.

## Anlatım Biçimleri
Paragraflarda yazarın öznel ya da nesnel bir bakış açısıyla yazıp yazmadığı; örnekleme, tanık gösterme, karşılaştırma gibi düşünceyi geliştirme yollarının kullanılıp kullanılmadığı da sıkça sorulur.', 'Aşağıdaki paragrafın ana düşüncesi ne olabilir? ''Kitap okumak, insanın hayal gücünü geliştirir, kelime dağarcığını zenginleştirir...''') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('8c4343f2-6679-4a1a-bf13-3a9603a4d61c', 'f884a167-9e40-4c5c-bc29-810eb13f200e', 'kolay'::difficulty_level, '''İnsanlar günlük hayatlarında birçok karar verir. Bu kararların bazıları küçük, bazıları ise hayatı derinden etkileyecek kadar büyüktür. Küçük kararlar genellikle anlık düşünülüp hızla alınırken büyük kararlar için uzun süre düşünülür, çevredeki insanların fikirleri alınır. Çünkü büyük kararların sonuçları, kişinin hayatını uzun yıllar etkileyebilir.'' Bu parçanın ana düşüncesi aşağıdakilerden hangisidir?', 'Paragrafın ana düşüncesini belirler.', 'Parça, büyük kararların uzun süre düşünülerek ve başkalarının görüşü alınarak verilmesi gerektiğini, çünkü sonuçlarının kalıcı olduğunu vurgulamaktadır. Diğer seçenekler ya parçanın yalnızca bir kısmını yansıtır ya da metinde yer almayan aşırı bir genelleme içerir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8c4343f2-6679-4a1a-bf13-3a9603a4d61c', 'İnsanlar hayatları boyunca sürekli karar alma durumundadır.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8c4343f2-6679-4a1a-bf13-3a9603a4d61c', 'Büyük kararlar, sonuçlarının kalıcı etkisi nedeniyle daha dikkatli ve uzun düşünülerek alınmalıdır.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8c4343f2-6679-4a1a-bf13-3a9603a4d61c', 'Küçük kararlar hızlı alındığı için önemsizdir.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8c4343f2-6679-4a1a-bf13-3a9603a4d61c', 'Çevredeki insanların fikirleri her zaman doğru kararlar verdirir.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('0e326fc3-3273-4770-b311-3819fa74bb04', 'f884a167-9e40-4c5c-bc29-810eb13f200e', 'kolay'::difficulty_level, '''Kitap okumak, insanın hayal gücünü geliştirir, kelime dağarcığını zenginleştirir ve empati kurma becerisini artırır. Ayrıca düzenli kitap okuyan bireylerin analitik düşünme yetenekleri de gelişir. Bu nedenle ______'' Bu parçada boş bırakılan yere aşağıdakilerden hangisi getirilmelidir?', 'Paragrafın anlam akışına uygun tamamlama cümlesini seçer.', 'Parçada kitap okumanın sağladığı faydalar sıralandığı için mantıksal sonuç, bu alışkanlığın erken yaşta kazandırılması gerektiğidir. Diğer seçenekler parçanın konusuyla ilgisizdir ya da metinde değinilmeyen konulara değinir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0e326fc3-3273-4770-b311-3819fa74bb04', 'televizyon izlemek de kitap okumak kadar faydalıdır.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0e326fc3-3273-4770-b311-3819fa74bb04', 'çocuklara küçük yaştan itibaren kitap okuma alışkanlığı kazandırılmalıdır.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0e326fc3-3273-4770-b311-3819fa74bb04', 'kitap okumanın hiçbir zararı yoktur.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0e326fc3-3273-4770-b311-3819fa74bb04', 'herkesin aynı türde kitap okuması gerekir.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('e9bc37d9-d918-4c60-8b78-809052d71989', 'f884a167-9e40-4c5c-bc29-810eb13f200e', 'orta'::difficulty_level, '''Şehirlerin hızla büyümesiyle birlikte yeşil alanlar giderek azalmaktadır. Betonlaşan kentlerde hava kalitesi düşmekte, sıcaklık artışları daha belirgin hissedilmektedir. Bununla birlikte bazı belediyeler, çatı bahçeleri ve dikey ormanlar gibi projelerle bu soruna çözüm aramaktadır. Ancak bu çabalar, kaybedilen yeşil alanların yerini tam olarak dolduramamaktadır.'' Bu parçanın ana düşüncesi aşağıdakilerden hangisidir?', 'Paragrafta ana düşünce ile yardımcı düşünceleri ayırt eder.', 'Parça, kentleşmeyle azalan yeşil alanlar için belediyelerin çözüm aradığını ama bu çabaların yeterli olmadığını vurgulamaktadır. Diğer seçenekler metinle çelişir ya da metinde yapılmayan bir karşılaştırma veya aşırı genelleme içerir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e9bc37d9-d918-4c60-8b78-809052d71989', 'Belediyeler çevre sorunlarına duyarsız kalmaktadır.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e9bc37d9-d918-4c60-8b78-809052d71989', 'Kentleşmeyle azalan yeşil alanların yerini, alınan önlemler yeterince dolduramamaktadır.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e9bc37d9-d918-4c60-8b78-809052d71989', 'Çatı bahçeleri, dikey ormanlardan daha etkilidir.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e9bc37d9-d918-4c60-8b78-809052d71989', 'Hava kalitesi yalnızca sıcaklıkla ilgilidir.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('8c2b1a20-fd4b-4e94-894d-080ccfe08aa3', 'f884a167-9e40-4c5c-bc29-810eb13f200e', 'orta'::difficulty_level, '''______ Bu tür kitaplar, karmaşık bilimsel kavramları sade bir dille anlatarak okurun ilgisini çeker. Yazar, günlük hayattan örnekler kullanarak konuyu somutlaştırır. Böylece bilim, sadece uzmanların değil herkesin anlayabileceği bir alan hâline gelir.'' Bu parçanın başına aşağıdaki cümlelerden hangisi getirilmelidir?', 'Paragrafın başına gelecek en uygun giriş cümlesini belirler.', 'Parçanın devamında ''bu tür kitaplar'' ifadesiyle atıf yapılan konu, ancak popüler bilim kitaplarını tanıtan birinci seçenekle uyumludur. Diğer seçenekler parçanın konusuyla ilgisizdir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8c2b1a20-fd4b-4e94-894d-080ccfe08aa3', 'Popüler bilim kitapları, bilimi geniş kitlelere ulaştırmayı amaçlayan eserlerdir.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8c2b1a20-fd4b-4e94-894d-080ccfe08aa3', 'Bilim insanları genellikle yalnız çalışmayı tercih eder.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8c2b1a20-fd4b-4e94-894d-080ccfe08aa3', 'Roman yazarları hayal gücünü kullanarak eser üretir.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('8c2b1a20-fd4b-4e94-894d-080ccfe08aa3', 'Her kitap mutlaka bir amaç taşımalıdır.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('87bab34d-3b9e-40cf-b229-0c2863631d76', 'f884a167-9e40-4c5c-bc29-810eb13f200e', 'zor'::difficulty_level, '''Bir sanat eserinin değeri, yalnızca teknik ustalıkla ölçülemez. Tuval üzerine ustaca işlenmiş bir tablo, izleyicide hiçbir duygu uyandırmıyorsa amacına ulaşamamış demektir. Oysa bazen çok basit çizgilerle oluşturulmuş bir eser, izleyicisini derinden etkileyebilir, onu düşünmeye sevk edebilir. Bu nedenle sanatı değerlendirirken teknik beceri kadar, eserin izleyicide bıraktığı etkiye de bakmak gerekir.'' Bu parçadan aşağıdaki yargılardan hangisine ulaşılamaz?', 'Paragraftan çıkarılabilecek ve çıkarılamayacak yargıları ayırt eder.', 'Parçada sanatçının ününden hiç söz edilmediği için dördüncü seçenekteki yargıya metinden ulaşılamaz. Diğer seçenekler parçada doğrudan ya da dolaylı olarak ifade edilmiştir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('87bab34d-3b9e-40cf-b229-0c2863631d76', 'Teknik açıdan kusursuz bir eser, izleyicide duygu uyandırmayabilir.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('87bab34d-3b9e-40cf-b229-0c2863631d76', 'Basit görünen eserler de izleyici üzerinde güçlü bir etki bırakabilir.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('87bab34d-3b9e-40cf-b229-0c2863631d76', 'Bir sanat eserini değerlendirirken hem teknik beceri hem de duygusal etki göz önünde bulundurulmalıdır.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('87bab34d-3b9e-40cf-b229-0c2863631d76', 'Sanat eserlerinin değeri, yalnızca sanatçının ününe göre belirlenir.', true, 3);
commit;