-- KPSS Vatandaşlık: 5 ana konu için tam kapsamlı içerik (özet, ders notu, örnek soru)
-- ve her konu için 4'er soru + 5'er seçenek. Var olan konular (Temel Hukuk Kavramları,
-- Anayasa, Yasama-Yürütme-Yargı) topic_contents UPSERT ile zenginleştiriliyor; eksik
-- olan iki konu (Temel Hak ve Özgürlükler, Uluslararası Kuruluşlar) yeni topic olarak ekleniyor.

insert into topic_contents (topic_id, summary, content_md, example_question) values ('f046e8ff-0d47-47fa-add9-45a27a151b63', 'Hukuk kurallarını diğer toplumsal düzen kurallarından (ahlak, din, görgü) ayıran temel özellik olan devlet gücüyle desteklenen müeyyide (yaptırım) kavramı; kamu-özel hukuk ayrımı ve normlar hiyerarşisi bu konunun omurgasını oluşturur.', '## Hukuk Kuralının Ayırt Edici Özelliği: Müeyyide
Hukuk kuralını ahlak, din ve görgü kuralları gibi diğer toplumsal düzen kurallarından ayıran en temel özellik, hukuk kurallarına uyulmadığında devredilen yaptırımın (müeyyidenin) DEVLET GÜCÜYLE desteklenmesidir. Ahlak kuralları da bir yaptırıma sahiptir (toplumsal ayıplama, vicdan azabı) ama bu yaptırım devlet gücüyle desteklenmez.

## Kamu Hukuku - Özel Hukuk Ayrımı
Kamu hukuku, devletin taraflardan biri olduğu ve taraflar arasında EŞİTSİZLİK/ÜSTÜNLÜK ilişkisinin bulunduğu hukuk dallarıdır (anayasa hukuku, ceza hukuku, idare hukuku, vergi hukuku). Özel hukuk ise kişiler arasındaki EŞİT taraflar ilişkisini düzenler (medeni hukuk, borçlar hukuku, ticaret hukuku).

## Normlar Hiyerarşisi (Hukuk Piramidi)
Türk hukuk sisteminde normlar hiyerarşik bir sıra izler: Anayasa en üstte, ardından kanunlar, ardından Cumhurbaşkanlığı kararnameleri (2017 Anayasa değişikliğiyle KHK''ların yerini almıştır), en altta ise yönetmelikler yer alır. Alt sıradaki bir norm, üst sıradaki norma aykırı olamaz.

## Hukukun Kaynakları
Yazılı kaynaklar (Anayasa, kanun, Cumhurbaşkanlığı kararnamesi, yönetmelik) ile yazısız kaynaklar (örf ve adet hukuku) hukukun kaynaklarını oluşturur. Örf ve adet hukuku, toplumda uzun süredir uygulanan ve hukuki bir zorunluluk inancıyla benimsenen kurallardır; devlet tarafından tanındığında bağlayıcı hâle gelir.

## Kritik Hap Notlar
- Hukuk kuralını diğer kurallardan ayıran özellik: müeyyidenin DEVLET GÜCÜYLE desteklenmesi (ahlak kuralının yaptırımı toplumsaldır, devletle değil).
- Kamu hukuku = devlet taraf + eşitsizlik ilişkisi (anayasa, ceza, idare, vergi hukuku); Özel hukuk = eşit taraflar (medeni, borçlar, ticaret hukuku).
- Normlar hiyerarşisi: Anayasa > Kanun > Cumhurbaşkanlığı Kararnamesi > Yönetmelik — 2017 sonrası KHK yerini Cumhurbaşkanlığı kararnamesine bırakmıştır, GÜNCEL müfredat notudur.
- Örf ve adet hukuku YAZISIZ bir kaynaktır ama devlet tarafından tanınıp uygulandığında bağlayıcı bir hukuk kuralı hâline gelir.
- Kanunların Anayasaya uygunluğunu denetleyen organ Anayasa Mahkemesi''dir; bu, hukukun üstünlüğü ilkesinin kurumsal güvencesidir.

## Video Ders Takip Rehberi
- [00:00 - 05:00] Toplumsal düzen kuralları (hukuk, ahlak, din, görgü) ve aralarındaki temel fark.
- [05:00 - 12:00] Müeyyide kavramı, kamu hukuku-özel hukuk ayrımı.
- [12:00 - 20:00] Normlar hiyerarşisi ve hukukun kaynakları örneklerle pekiştirme.
- [20:00 - Bitiş] ÖSYM''nin çeldiricileri: ahlak kuralının yaptırımıyla hukuk kuralının yaptırımının karıştırılması, KHK''nın hâlâ yürürlükte bir norm türü olduğu yanılgısı.', 'Bir kimse borcunu ödemediğinde devlet gücü kullanılarak (icra yoluyla) borcun tahsil edilmesi, hukuk kuralının hangi temel özelliğinin bir sonucudur?
A) Genellik B) Soyutluk C) Devlet gücüyle desteklenen müeyyide D) Yazılılık E) Süreklilik
Doğru Cevap: C — Hukuk kuralına uyulmamasının devlet gücüyle desteklenen bir yaptırıma bağlanması, onu diğer toplumsal düzen kurallarından ayıran temel özelliktir.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('3b756507-60fb-4ff3-8ba3-43aa8ddac429', 'f046e8ff-0d47-47fa-add9-45a27a151b63', 'kolay'::difficulty_level, 'Hukuk kurallarını ahlak kurallarından ayıran en temel özellik aşağıdakilerden hangisidir?', 'Hukuk kuralının ayırt edici özelliğini bilir.', 'Hukuk kurallarına uyulmadığında uygulanan yaptırımın DEVLET GÜCÜYLE desteklenmesi, onu ahlak kurallarından ayıran temel özelliktir (B doğru); ahlak kurallarının yaptırımı toplumsal ayıplama ve vicdani rahatsızlıktır, devlet gücüyle desteklenmez. Yazılı olma (A) tüm hukuk kuralları için geçerli değildir (örf ve adet hukuku yazısızdır). Genellik (C) ve süreklilik (D) hem hukuk hem ahlak kuralında bulunabilir. Değişkenlik (E) ayırt edici bir özellik değildir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3b756507-60fb-4ff3-8ba3-43aa8ddac429', 'Yazılı bir metne dayanması', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3b756507-60fb-4ff3-8ba3-43aa8ddac429', 'Yaptırımının devlet gücüyle desteklenmesi', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3b756507-60fb-4ff3-8ba3-43aa8ddac429', 'Herkes için geçerli (genel) olması', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3b756507-60fb-4ff3-8ba3-43aa8ddac429', 'Uzun süre değişmeden uygulanması', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3b756507-60fb-4ff3-8ba3-43aa8ddac429', 'Toplumdan topluma farklılık göstermesi', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('2d3965a4-91ef-4fc9-a3c6-f98555d92fce', 'f046e8ff-0d47-47fa-add9-45a27a151b63', 'orta'::difficulty_level, 'Aşağıdaki hukuk dallarından hangisi özel hukuk kapsamında değerlendirilir?', 'Kamu hukuku ile özel hukuku ayırt eder.', 'Borçlar hukuku, eşit taraflar (alacaklı-borçlu) arasındaki ilişkileri düzenlediği için özel hukuk kapsamındadır (D doğru). Anayasa hukuku (A), ceza hukuku (B), idare hukuku (C) ve vergi hukuku (E) ise devletin taraf olduğu ve üstün-taraf ilişkisinin bulunduğu kamu hukuku dallarıdır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2d3965a4-91ef-4fc9-a3c6-f98555d92fce', 'Anayasa hukuku', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2d3965a4-91ef-4fc9-a3c6-f98555d92fce', 'Ceza hukuku', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2d3965a4-91ef-4fc9-a3c6-f98555d92fce', 'İdare hukuku', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2d3965a4-91ef-4fc9-a3c6-f98555d92fce', 'Borçlar hukuku', true, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2d3965a4-91ef-4fc9-a3c6-f98555d92fce', 'Vergi hukuku', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('64479fb6-5457-4258-b5ac-ecca4a783644', 'f046e8ff-0d47-47fa-add9-45a27a151b63', 'zor'::difficulty_level, 'Türk hukuk sistemindeki normlar hiyerarşisiyle ilgili aşağıdaki çıkarımlardan hangisi doğrudur?', 'Normlar hiyerarşisini güncel mevzuata göre değerlendirir.', '2017 Anayasa değişikliği sonrasında KHK (Kanun Hükmünde Kararname) çıkarma yetkisi kaldırılmış, yerine Cumhurbaşkanlığı kararnamesi getirilmiştir; bir yönetmelik Cumhurbaşkanlığı kararnamesine aykırı olamaz (D doğru). A yanlıştır, kanun Anayasaya değil Anayasa kanuna üstündür (Anayasa en üsttedir). B yanlıştır, KHK artık normal dönemde çıkarılamaz. C yanlıştır, yönetmelik hiyerarşinin en altındadır, kanunun üstünde değildir. E yanlıştır, Cumhurbaşkanlığı kararnamesi kanunla aynı düzeyde değil kanunun ALTINDA yer alır ve kanuna aykırı olamaz.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('64479fb6-5457-4258-b5ac-ecca4a783644', 'Anayasa, kanunlara göre daha alt bir normdur', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('64479fb6-5457-4258-b5ac-ecca4a783644', 'KHK (Kanun Hükmünde Kararname), günümüzde de olağan dönemde çıkarılabilen bir norm türüdür', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('64479fb6-5457-4258-b5ac-ecca4a783644', 'Yönetmelik, kanunun üstünde yer alan bir normdur', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('64479fb6-5457-4258-b5ac-ecca4a783644', 'Bir yönetmelik, Cumhurbaşkanlığı kararnamesine aykırı hüküm içeremez', true, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('64479fb6-5457-4258-b5ac-ecca4a783644', 'Cumhurbaşkanlığı kararnamesi, kanunla tamamen aynı düzeyde bir norm olup kanuna aykırı olabilir', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('2484db10-1d02-4dfb-9663-4d36c9b03c8f', 'f046e8ff-0d47-47fa-add9-45a27a151b63', 'orta'::difficulty_level, 'Bir yörede yıllardan beri uygulanan ve toplum tarafından hukuki bir zorunluluk olarak benimsenen, ancak hiçbir yazılı metinde yer almayan bir kural, devlet tarafından tanınıp uygulandığında hukukun hangi kaynağı içinde değerlendirilir?', 'Hukukun yazısız kaynağını (örf ve adet hukuku) tanır.', 'Yazılı bir metne dayanmayan ama toplumda hukuki bir zorunluluk inancıyla uzun süredir uygulanan ve devlet tarafından tanınan kurallar örf ve adet hukukunu oluşturur; bu, hukukun YAZISIZ bir kaynağıdır (B doğru). Kanun (A), yönetmelik (C) ve Cumhurbaşkanlığı kararnamesi (D) yazılı kaynaklardır ve resmi bir metne dayanır. Mahkeme içtihadı (E) farklı bir kaynak türüdür, doğrudan bu tanıma uymaz.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2484db10-1d02-4dfb-9663-4d36c9b03c8f', 'Kanun', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2484db10-1d02-4dfb-9663-4d36c9b03c8f', 'Örf ve adet hukuku', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2484db10-1d02-4dfb-9663-4d36c9b03c8f', 'Yönetmelik', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2484db10-1d02-4dfb-9663-4d36c9b03c8f', 'Cumhurbaşkanlığı kararnamesi', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2484db10-1d02-4dfb-9663-4d36c9b03c8f', 'Mahkeme içtihadı', false, 4);

insert into topic_contents (topic_id, summary, content_md, example_question) values ('86ae4cc1-2323-4a43-8448-b1fa4daf514e', '1982 Anayasası''nın sert (katı) niteliği, değiştirilemez hükümleri (madde 1-2-3), anayasa değişikliği usulü ve 2017''de Cumhurbaşkanlığı hükümet sistemine geçişin getirdiği değişiklikler bu konunun temel omurgasıdır.', '## 1982 Anayasası''nın Genel Nitelikleri
1982 Anayasası SERT (katı) bir anayasadır; bu, olağan kanunlardan daha zor ve özel bir usulle (nitelikli çoğunluk) değiştirilebildiği anlamına gelir. Anayasanın 2. maddesi Türkiye Cumhuriyeti''nin niteliklerini (insan haklarına saygılı, Atatürk milliyetçiliğine bağlı, demokratik, laik ve sosyal bir hukuk devleti) sayar.

## Değiştirilemez Hükümler
Anayasanın ilk üç maddesi (1. madde: devletin şekli Cumhuriyettir; 2. madde: Cumhuriyetin nitelikleri; 3. madde: devletin bütünlüğü, bayrağı, milli marşı, başkenti) değiştirilemez ve değiştirilmesi TEKLİF DAHİ EDİLEMEZ hükümlerdir.

## Anayasa Değişikliği Usulü
Anayasa değişikliği teklifi, TBMM üye tam sayısının en az 1/3''ü (200 milletvekili) tarafından yazılı olarak yapılabilir. Teklifin kabulü için üye tam sayısının 3/5 çoğunluğu (360 oy) gerekir. 3/5 ile 2/3 (400 oy) arasında kabul edilen değişiklikler Cumhurbaşkanı tarafından halkoyuna sunulabilir veya tekrar görüşülmek üzere Meclis''e iade edilebilir; 2/3 çoğunlukla kabul edilen değişiklikleri Cumhurbaşkanı ya doğrudan onaylar ya da halkoyuna sunabilir.

## 2017 Anayasa Değişikliği ve Cumhurbaşkanlığı Hükümet Sistemi
2017''de yapılan halkoylamasıyla kabul edilen anayasa değişikliğiyle Türkiye parlamenter sistemden Cumhurbaşkanlığı hükümet sistemine geçmiştir: Başbakanlık ve Bakanlar Kurulu kaldırılmış, yürütme yetkisi tek başına Cumhurbaşkanına verilmiş, Cumhurbaşkanı aynı zamanda bir siyasi partiyle ilişkisini sürdürebilir hâle gelmiştir (önceki sistemde Cumhurbaşkanının parti ile ilişiği kesilirdi).

## Kritik Hap Notlar
- 1982 Anayasası SERT (katı) bir anayasadır — sıradan kanunlarla değil, nitelikli çoğunluk (3/5 veya 2/3) gerektiren özel bir usulle değiştirilebilir.
- Anayasanın 1-2-3. maddeleri (devletin şekli, nitelikleri, bayrak-başkent-dil) DEĞİŞTİRİLEMEZ ve değiştirilmesi TEKLİF DAHİ EDİLEMEZ.
- Anayasa değişikliği teklifi: TBMM üye tam sayısının EN AZ 1/3''ü (200 milletvekili). Kabul: EN AZ 3/5 (360 oy).
- 2017 değişikliğiyle Başbakanlık ve Bakanlar Kurulu KALDIRILDI, yürütme yetkisi TEK BAŞINA Cumhurbaşkanına verildi — bu, "kuvvetler ayrılığının güçlendirilmesi" değil, yürütmenin TEKLEŞTİRİLMESİ anlamına gelir.
- Anayasa Mahkemesi kanunların, Cumhurbaşkanlığı kararnamelerinin ve TBMM İçtüzüğü''nün Anayasaya uygunluğunu denetler (norm denetimi/anayasa yargısı).

## Video Ders Takip Rehberi
- [00:00 - 05:00] 1982 Anayasası''nın genel özellikleri, sertlik kavramı ve madde 2''deki devlet nitelikleri.
- [05:00 - 12:00] Değiştirilemez hükümler (madde 1-2-3) ve anayasa değişikliği usulü (1/3 teklif, 3/5-2/3 kabul).
- [12:00 - 20:00] 2017 Cumhurbaşkanlığı hükümet sistemine geçiş — Başbakanlık''ın kaldırılması örneği üzerinden pekiştirme.
- [20:00 - Bitiş] ÖSYM''nin çeldiricileri: teklif/kabul çoğunluk sayılarının karıştırılması, "değiştirilemez" ile "değiştirilmesi zor" ifadelerinin karıştırılması.', '1982 Anayasası''na göre anayasa değişikliği teklifi TBMM üye tam sayısının en az kaçta kaçı tarafından yapılabilir?
A) 1/2 B) 1/3 C) 2/3 D) 3/5 E) 3/4
Doğru Cevap: B — Anayasa değişikliği teklifi TBMM üye tam sayısının en az 1/3''ü tarafından yazılı olarak yapılabilir.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('97c95be5-dd47-49fc-8470-f9b448b51d09', '86ae4cc1-2323-4a43-8448-b1fa4daf514e', 'kolay'::difficulty_level, '1982 Anayasası''nın 1, 2 ve 3. maddeleriyle ilgili aşağıdakilerden hangisi doğrudur?', 'Anayasanın değiştirilemez hükümlerini bilir.', 'Anayasanın ilk üç maddesi (devletin şekli, nitelikleri, bayrak-başkent-dil gibi temel unsurlar) değiştirilemez ve değiştirilmesi teklif dahi edilemez (C doğru). A yanlıştır, tam tersine bu maddeler diğer maddelerden daha SIKI korunur. B yanlıştır, sadece TBMM kararıyla değil hiçbir usulle değiştirilemezler. D ve E gerçeği yansıtmayan, konuyla ilgisiz iddialardır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('97c95be5-dd47-49fc-8470-f9b448b51d09', 'Bu maddeler diğer maddelerle aynı usulle, herhangi bir kısıtlama olmadan değiştirilebilir', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('97c95be5-dd47-49fc-8470-f9b448b51d09', 'Bu maddeler yalnızca TBMM''nin basit çoğunluk kararıyla değiştirilebilir', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('97c95be5-dd47-49fc-8470-f9b448b51d09', 'Bu maddeler değiştirilemez ve değiştirilmesi teklif dahi edilemez', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('97c95be5-dd47-49fc-8470-f9b448b51d09', 'Bu maddeler yalnızca Anayasa Mahkemesi kararıyla değiştirilebilir', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('97c95be5-dd47-49fc-8470-f9b448b51d09', 'Bu maddeler halkoylamasına gerek kalmadan Cumhurbaşkanı kararıyla değiştirilebilir', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('e62344fc-513a-430a-8642-65c6a207a347', '86ae4cc1-2323-4a43-8448-b1fa4daf514e', 'orta'::difficulty_level, '2017 Anayasa değişikliği ile Türkiye''de yönetim sistemiyle ilgili aşağıdaki değişikliklerden hangisi gerçekleşmiştir?', 'Cumhurbaşkanlığı hükümet sistemine geçişin temel özelliklerini bilir.', '2017 Anayasa değişikliğiyle Başbakanlık ve Bakanlar Kurulu kaldırılmış, yürütme yetkisi tek başına Cumhurbaşkanına verilmiştir (C doğru). A ve B yanlıştır, tam tersi bir değişiklik yapılmıştır (parlamenter sistemden çıkılmış, güçler ayrılığı klasik anlamda korunmamıştır). D yanlıştır, TBMM üye sayısı 550''den 600''e ÇIKARILMIŞTIR, düşürülmemiştir. E yanlıştır, aksine Cumhurbaşkanının bir siyasi partiyle ilişkisini SÜRDÜREBİLMESİNE izin verilmiştir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e62344fc-513a-430a-8642-65c6a207a347', 'Parlamenter sistem güçlendirilerek Başbakanlığın yetkileri artırılmıştır', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e62344fc-513a-430a-8642-65c6a207a347', 'Kuvvetler ayrılığı ilkesi daha da katılaştırılarak yürütme iki başlı hâle getirilmiştir', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e62344fc-513a-430a-8642-65c6a207a347', 'Başbakanlık ve Bakanlar Kurulu kaldırılarak yürütme yetkisi tek başına Cumhurbaşkanına verilmiştir', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e62344fc-513a-430a-8642-65c6a207a347', 'TBMM üye tam sayısı 600''den 550''ye düşürülmüştür', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e62344fc-513a-430a-8642-65c6a207a347', 'Cumhurbaşkanının herhangi bir siyasi partiyle ilişkisinin kesilmesi zorunlu hâle getirilmiştir', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('449a48ee-654c-4bf1-8043-76d8147e19ab', '86ae4cc1-2323-4a43-8448-b1fa4daf514e', 'zor'::difficulty_level, 'TBMM''de bir anayasa değişikliği teklifi üye tam sayısının 3/5''i ile 2/3''ü arasında bir oranla (örneğin 3/5''ten fazla ama 2/3''ten az bir oyla) kabul edilmiştir. Bu durumda izlenecek yol aşağıdakilerden hangisidir?', 'Anayasa değişikliği usulünün oran aralıklarına göre sonuçlarını bilir.', 'Bir anayasa değişikliği teklifi üye tam sayısının 3/5''i ile 2/3''ü arasında bir oranla kabul edilirse, Cumhurbaşkanı bu değişikliği halkoyuna (referanduma) sunabilir veya tekrar görüşülmek üzere TBMM''ye geri gönderebilir (C doğru). A yanlıştır, bu durumda değişiklik otomatik olarak yürürlüğe girmez, halkoyuna sunulma ihtimali vardır. B yanlıştır, teklif reddedilmiş sayılmaz, kabul edilmiştir; sadece belirli bir prosedür izlenir. D ve E bu duruma özgü doğru prosedürler değildir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('449a48ee-654c-4bf1-8043-76d8147e19ab', 'Değişiklik hiçbir işleme gerek kalmadan doğrudan yürürlüğe girer', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('449a48ee-654c-4bf1-8043-76d8147e19ab', 'Teklif otomatik olarak reddedilmiş sayılır', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('449a48ee-654c-4bf1-8043-76d8147e19ab', 'Cumhurbaşkanı bu değişikliği halkoyuna sunabilir veya tekrar görüşülmek üzere TBMM''ye geri gönderebilir', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('449a48ee-654c-4bf1-8043-76d8147e19ab', 'Değişiklik doğrudan Anayasa Mahkemesi''nin onayına sunulur', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('449a48ee-654c-4bf1-8043-76d8147e19ab', 'Değişiklik yalnızca bir sonraki milletvekili genel seçiminden sonra yürürlüğe girebilir', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('738f4a6a-ece0-4bfd-928b-63a4ad7bb779', '86ae4cc1-2323-4a43-8448-b1fa4daf514e', 'orta'::difficulty_level, 'Anayasa Mahkemesi''nin başlıca görevlerinden biri olan "norm denetimi" ile ilgili aşağıdakilerden hangisi doğrudur?', 'Anayasa Mahkemesi''nin norm denetimi görevini açıklar.', 'Anayasa Mahkemesi, kanunların, Cumhurbaşkanlığı kararnamelerinin ve TBMM İçtüzüğü''nün Anayasaya şekil ve esas bakımından uygunluğunu denetler (D doğru). Yönetmelikler (A) bu denetimin konusu değildir, onların denetimi idari yargının (Danıştay) görevidir. Anayasa Mahkemesi milletvekili genel seçimlerini (B) değil, Yüksek Seçim Kurulu bu seçimleri yönetir. Uluslararası antlaşmaların Anayasaya uygunluğu (C) Anayasa Mahkemesi''nin denetim alanına girmez (usulüne göre yürürlüğe konulan antlaşmalar hakkında Anayasaya aykırılık iddiasıyla başvurulamaz). Cumhurbaşkanının cezai sorumluluğu (E) ayrı bir konu olan Yüce Divan yargılamasıyla ilgilidir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('738f4a6a-ece0-4bfd-928b-63a4ad7bb779', 'Yönetmeliklerin Anayasaya uygunluğunu denetler', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('738f4a6a-ece0-4bfd-928b-63a4ad7bb779', 'Milletvekili genel seçimlerinin sonuçlarını ilan eder', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('738f4a6a-ece0-4bfd-928b-63a4ad7bb779', 'Usulüne göre yürürlüğe konulmuş uluslararası antlaşmaların Anayasaya uygunluğunu denetler', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('738f4a6a-ece0-4bfd-928b-63a4ad7bb779', 'Kanunların, Cumhurbaşkanlığı kararnamelerinin ve TBMM İçtüzüğü''nün Anayasaya uygunluğunu denetler', true, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('738f4a6a-ece0-4bfd-928b-63a4ad7bb779', 'Cumhurbaşkanının günlük idari işlemlerini onaylar', false, 4);

insert into topic_contents (topic_id, summary, content_md, example_question) values ('37c6d817-c011-4012-9f18-b651bf8b022e', 'Kuvvetler ayrılığı ilkesi çerçevesinde yasama (TBMM), yürütme (Cumhurbaşkanı) ve yargı (bağımsız mahkemeler-HSK) organlarının güncel (2017 sonrası) yapısı ve işleyişi bu konunun temelini oluşturur.', '## Yasama: TBMM
Türkiye Büyük Millet Meclisi, 600 milletvekilinden oluşur (2017 değişikliğiyle 550''den 600''e çıkarılmıştır) ve milletvekili genel seçimleri 5 yılda bir yapılır (önceden 4 yıldı); bu seçimler Cumhurbaşkanlığı seçimiyle AYNI GÜNDE gerçekleştirilir. TBMM''nin başlıca görevleri kanun koymak, değiştirmek ve kaldırmak, bütçeyi görüşüp kabul etmek, Bakanlar Kurulu döneminde var olan güvenoyu denetimi artık yerini Meclis soruşturması gibi başka denetim yollarına bırakmıştır.

## Yürütme: Cumhurbaşkanı
2017 değişikliği sonrası yürütme yetkisi TEK BAŞINA Cumhurbaşkanına aittir. Cumhurbaşkanı halk tarafından 5 yıllığına seçilir ve bir kişi en fazla İKİ DEFA Cumhurbaşkanı seçilebilir (istisna: ikinci döneminde TBMM''nin seçimlerin yenilenmesine karar vermesi hâlinde üçüncü kez aday olabilir). Cumhurbaşkanı yardımcıları ve bakanları atar, Cumhurbaşkanlığı kararnamesi çıkarabilir (ancak münhasıran kanunla düzenlenmesi öngörülen konularda kararname çıkaramaz).

## Yargı: Bağımsız Mahkemeler ve HSK
Yargı yetkisi, Türk Milleti adına bağımsız ve tarafsız mahkemelerce kullanılır. Hakimler ve Savcılar Kurulu (HSK), hakim ve savcıların atanması, terfi ettirilmesi, disiplin işlemleri gibi mesleki konularını yürüterek yargı bağımsızlığının kurumsal güvencesini oluşturur.

## Kuvvetler Ayrılığı ve Fren-Denge Mekanizmaları
Kuvvetler ayrılığı MUTLAK bir ayrılık değil, organlar arasında karşılıklı FREN-DENGE (denetleme) mekanizmalarının bulunduğu YUMUŞAK bir ayrılıktır: örneğin TBMM, Cumhurbaşkanı hakkında Meclis soruşturması açabilir; Cumhurbaşkanı da TBMM seçimlerinin yenilenmesine karar verebilir.

## Kritik Hap Notlar
- TBMM üye sayısı 600''dür (2017 değişikliğiyle 550''den 600''e çıkarılmıştır) — GÜNCEL bilgi.
- Milletvekili genel seçimleri ve Cumhurbaşkanlığı seçimi 5 yılda bir ve AYNI GÜNDE yapılır (2017 öncesi milletvekili seçimleri 4 yıldı).
- Cumhurbaşkanı en fazla İKİ KEZ seçilebilir; istisnası TBMM''nin ikinci dönemde seçimleri yenileme kararı almasıdır.
- HSK, yargı bağımsızlığının kurumsal güvencesidir; hakim-savcıların atama/terfi/disiplin işlerini yürütür.
- Kuvvetler ayrılığı MUTLAK değil, YUMUŞAK bir ayrılıktır — organlar birbirini fren-denge mekanizmalarıyla denetler, tamamen bağımsız/izole çalışmazlar.

## Video Ders Takip Rehberi
- [00:00 - 05:00] Kuvvetler ayrılığı ilkesinin genel tanımı ve yumuşak ayrılık kavramı.
- [05:00 - 12:00] TBMM''nin yapısı (600 üye, 5 yıl) ve Cumhurbaşkanının yetkileri (2017 sonrası tek başlı yürütme).
- [12:00 - 20:00] Yargı bağımsızlığı ve HSK''nın rolü örnek üzerinden pekiştirme.
- [20:00 - Bitiş] ÖSYM''nin çeldiricileri: 550/600 üye sayısı karışıklığı, 4/5 yıl seçim süresi karışıklığı, Cumhurbaşkanının üçüncü kez aday olabileceği istisnai durumun atlanması.', '2017 Anayasa değişikliği sonrasında TBMM üye tam sayısı ve milletvekili genel seçimlerinin yapılma sıklığı aşağıdakilerden hangisinde doğru verilmiştir?
A) 550 üye - 4 yıl B) 600 üye - 5 yıl C) 550 üye - 5 yıl D) 600 üye - 4 yıl E) 500 üye - 5 yıl
Doğru Cevap: B — 2017 değişikliğiyle TBMM üye sayısı 600''e çıkarılmış, seçimler 5 yılda bir yapılmaya başlanmıştır.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('e84980f8-688f-4ac3-aa10-9654cf3af7f7', '37c6d817-c011-4012-9f18-b651bf8b022e', 'kolay'::difficulty_level, '2017 Anayasa değişikliği sonrasında TBMM üye tam sayısı kaça çıkarılmıştır?', 'TBMM''nin güncel üye sayısını bilir.', '2017 Anayasa değişikliğiyle TBMM üye tam sayısı 550''den 600''e çıkarılmıştır (D doğru). Diğer seçenekler (A, B, C, E) güncel mevzuata uymayan, yanlış rakamlardır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e84980f8-688f-4ac3-aa10-9654cf3af7f7', '500', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e84980f8-688f-4ac3-aa10-9654cf3af7f7', '550', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e84980f8-688f-4ac3-aa10-9654cf3af7f7', '450', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e84980f8-688f-4ac3-aa10-9654cf3af7f7', '600', true, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e84980f8-688f-4ac3-aa10-9654cf3af7f7', '650', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('c2733bc7-9e6f-4d1a-8114-4459334dc153', '37c6d817-c011-4012-9f18-b651bf8b022e', 'orta'::difficulty_level, 'Cumhurbaşkanlığı hükümet sisteminde Cumhurbaşkanının seçilme süresi ve tekrar seçilme sınırıyla ilgili aşağıdakilerden hangisi doğrudur?', 'Cumhurbaşkanının görev süresi ve seçilme sınırlarını bilir.', 'Cumhurbaşkanı halk tarafından 5 yıllığına seçilir ve bir kişi en fazla iki defa Cumhurbaşkanı seçilebilir; ancak ikinci döneminde TBMM''nin seçimlerin yenilenmesine karar vermesi hâlinde üçüncü kez aday olabilir (D doğru). A ve B rakamsal olarak yanlıştır (4 yıl değil 5 yıldır, sınırsız değil en fazla iki defadır). C yanlıştır, TBMM tarafından değil doğrudan halk tarafından seçilir. E, üç dönemin kesin bir kural olduğunu iddia ettiği için yanlıştır — üçüncü dönem yalnızca istisnai bir durumda mümkündür.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c2733bc7-9e6f-4d1a-8114-4459334dc153', '4 yıllığına seçilir ve sınırsız sayıda yeniden seçilebilir', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c2733bc7-9e6f-4d1a-8114-4459334dc153', '5 yıllığına seçilir ve sınırsız sayıda yeniden seçilebilir', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c2733bc7-9e6f-4d1a-8114-4459334dc153', '5 yıllığına, TBMM tarafından seçilir', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c2733bc7-9e6f-4d1a-8114-4459334dc153', '5 yıllığına halk tarafından seçilir ve en fazla iki defa seçilebilir (istisnai durumda üçüncü kez aday olabilir)', true, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c2733bc7-9e6f-4d1a-8114-4459334dc153', '7 yıllığına seçilir ve yalnızca bir kez görev yapabilir', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('ad03f7e1-9e4f-4e4d-b41a-1743604f0611', '37c6d817-c011-4012-9f18-b651bf8b022e', 'zor'::difficulty_level, 'Bir öğrenci kuvvetler ayrılığı ilkesiyle ilgili şu çıkarımları yapmıştır:
I. Yasama, yürütme ve yargı organları birbirinden tamamen izole, hiçbir etkileşimi olmayan bağımsız yapılardır.
II. TBMM''nin Cumhurbaşkanı hakkında Meclis soruşturması açabilmesi, organlar arası bir fren-denge mekanizmasıdır.
III. Kuvvetler ayrılığı Türkiye''de yumuşak (esnek) bir ayrılık biçiminde uygulanır.
Bu çıkarımlardan hangileri doğrudur?', 'Kuvvetler ayrılığının yumuşak/sert ayrım niteliğini ileri düzeyde değerlendirir.', 'II doğrudur; Meclis soruşturması organlar arası fren-denge mekanizmalarından biridir. III de doğrudur; Türkiye''de kuvvetler ayrılığı mutlak değil, yumuşak/esnek bir biçimde uygulanır. I ise YANLIŞTIR çünkü organlar arasında fren-denge mekanizmaları (Meclis soruşturması, TBMM seçimlerinin yenilenmesi gibi) bulunur; organlar birbirinden tamamen izole değildir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ad03f7e1-9e4f-4e4d-b41a-1743604f0611', 'Yalnız I', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ad03f7e1-9e4f-4e4d-b41a-1743604f0611', 'Yalnız III', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ad03f7e1-9e4f-4e4d-b41a-1743604f0611', 'I ve II', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ad03f7e1-9e4f-4e4d-b41a-1743604f0611', 'II ve III', true, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ad03f7e1-9e4f-4e4d-b41a-1743604f0611', 'I, II ve III', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('1b4ed332-5091-4c04-b714-323ca588f8aa', '37c6d817-c011-4012-9f18-b651bf8b022e', 'orta'::difficulty_level, 'Hakimler ve Savcılar Kurulu (HSK) ile ilgili aşağıdakilerden hangisi doğrudur?', 'HSK''nın görevlerini ve yargı bağımsızlığındaki rolünü bilir.', 'HSK, hakim ve savcıların atanması, terfi ettirilmesi ve disiplin işlemleri gibi mesleki konularını yürüterek yargı bağımsızlığının kurumsal güvencesini oluşturur (C doğru). A yanlıştır, kanunların Anayasaya uygunluğunu Anayasa Mahkemesi denetler, HSK değil. B yanlıştır, HSK yasama organı değildir, TBMM''ye bağlı bir yapı değildir. D yanlıştır, bütçeyi TBMM görüşüp kabul eder. E yanlıştır, milletvekili seçimlerini Yüksek Seçim Kurulu (YSK) yönetir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1b4ed332-5091-4c04-b714-323ca588f8aa', 'Kanunların Anayasaya uygunluğunu denetler', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1b4ed332-5091-4c04-b714-323ca588f8aa', 'TBMM''ye bağlı bir yasama organı alt birimidir', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1b4ed332-5091-4c04-b714-323ca588f8aa', 'Hakim ve savcıların atanması, terfisi ve disiplin işlerini yürütür', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1b4ed332-5091-4c04-b714-323ca588f8aa', 'Devlet bütçesini görüşüp kabul eder', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1b4ed332-5091-4c04-b714-323ca588f8aa', 'Milletvekili genel seçimlerini yönetir', false, 4);

insert into topics (id, subject_id, name, slug, kazanim_text, weight, order_index) values ('a761a66c-9aa8-45fe-a865-b4833c71d0b2', 'a9ee39e3-e35c-4ff0-885a-4af773855d4d', 'Temel Hak ve Özgürlükler', 'temel-hak-ve-ozgurlukler', 'Anayasada güvence altına alınan temel hak ve özgürlüklerin sınıflandırılmasını ve sınırlandırılma esaslarını açıklar.', 1.0, 4);
insert into topic_contents (topic_id, summary, content_md, example_question) values ('a761a66c-9aa8-45fe-a865-b4833c71d0b2', 'Temel hak ve özgürlüklerin kişi hakları, sosyal-ekonomik haklar ve siyasi haklar olarak sınıflandırılması; hakların ancak kanunla ve ölçülülük ilkesine uygun biçimde sınırlandırılabilmesi bu konunun omurgasıdır.', '## Hakların Sınıflandırılması
Kişi hakları (yaşama hakkı, kişi dokunulmazlığı, özel hayatın gizliliği, konut dokunulmazlığı) BİRİNCİ KUŞAK haklardır ve devletten müdahale etmemesini (negatif edim) talep eder. Sosyal ve ekonomik haklar (eğitim hakkı, sağlık hakkı, sosyal güvenlik hakkı, çalışma hakkı) İKİNCİ KUŞAK haklardır ve devletten aktif bir edimde bulunmasını (pozitif edim, yani hizmet sunmasını) gerektirir. Siyasi haklar (seçme-seçilme hakkı, siyasi parti kurma hakkı, kamu hizmetlerine girme hakkı) vatandaşların yönetime katılımını sağlayan haklardır.

## Hakların Sınırlandırılması (Madde 13)
Anayasanın 13. maddesine göre temel hak ve özgürlükler ancak KANUNLA sınırlanabilir. Bu sınırlama, Anayasanın sözüne ve ruhuna, demokratik toplum düzeninin ve laik Cumhuriyetin gereklerine ve ölçülülük ilkesine aykırı olamaz; hakkın ÖZÜNE dokunulamaz.

## Olağanüstü Hallerde Hak ve Özgürlüklerin Durdurulması (Madde 15)
Savaş, seferberlik veya olağanüstü hallerde, milletlerarası hukuktan doğan yükümlülükler ihlal edilmemek kaydıyla, durumun gerektirdiği ölçüde temel hak ve özgürlüklerin kullanılması kısmen veya tamamen durdurulabilir ya da bunlar için Anayasada öngörülen güvencelere aykırı tedbirler alınabilir. Ancak savaş hukukuna uygun fiiller sonucu meydana gelen ölümler dışında, kişinin yaşama hakkına, maddî ve manevî varlığının bütünlüğüne dokunulamaz; kimse din, vicdan, düşünce ve kanaatlerini açıklamaya zorlanamaz ve bunlardan dolayı suçlanamaz.

## Kritik Hap Notlar
- Kişi hakları (BİRİNCİ KUŞAK): devletten MÜDAHALE ETMEMESİNİ (negatif edim) ister — yaşama hakkı, özel hayatın gizliliği, konut dokunulmazlığı.
- Sosyal-ekonomik haklar (İKİNCİ KUŞAK): devletten AKTİF HİZMET SUNMASINI (pozitif edim) ister — eğitim, sağlık, sosyal güvenlik hakkı.
- Siyasi haklar: yönetime KATILIMI sağlar — seçme-seçilme, parti kurma, kamu hizmetine girme hakkı.
- Hak ve özgürlükler ANCAK KANUNLA sınırlanabilir; sınırlama ölçülülük ilkesine uygun olmalı ve hakkın ÖZÜNE dokunmamalıdır (madde 13).
- Olağanüstü hallerde bile YAŞAMA HAKKI, kişinin maddi-manevi varlığının bütünlüğü ve din/vicdan/düşünceyi açıklamaya zorlanamama/bundan suçlanamama MUTLAK (dokunulmaz) çekirdek haklardır (madde 15) — savaş hukukuna uygun fiiller sonucu ölümler bu kuralın istisnasıdır.

## Video Ders Takip Rehberi
- [00:00 - 05:00] Hakların kuşaklara göre sınıflandırılması: kişi hakları, sosyal-ekonomik haklar, siyasi haklar.
- [05:00 - 12:00] Negatif edim / pozitif edim ayrımı örneklerle pekiştirme.
- [12:00 - 20:00] Madde 13 — hakların kanunla ve ölçülülük ilkesiyle sınırlandırılması.
- [20:00 - Bitiş] ÖSYM''nin çeldiricileri: olağanüstü hallerde bile dokunulamayan çekirdek hakların (madde 15) atlanması veya "hiçbir hak sınırlanamaz" gibi aşırı genellemeler.', 'Eğitim hakkı, sağlık hakkı ve sosyal güvenlik hakkı gibi haklar, devletin hangi tür bir edimde bulunmasını gerektirir?
A) Negatif edim (müdahale etmeme) B) Pozitif edim (aktif hizmet sunma) C) Yalnızca yasama edimi D) Yalnızca yargısal edim E) Hiçbir edim gerektirmez
Doğru Cevap: B — Sosyal ve ekonomik haklar, devletin aktif olarak hizmet sunmasını (pozitif edim) gerektirir.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('3e24c677-29e5-4c21-be49-c2efd6e1860d', 'a761a66c-9aa8-45fe-a865-b4833c71d0b2', 'kolay'::difficulty_level, 'Yaşama hakkı ve özel hayatın gizliliği gibi haklar, hangi hak kategorisinde yer alır ve devletten ne beklenir?', 'Kişi haklarının niteliğini ve devletten beklenen edim türünü bilir.', 'Yaşama hakkı ve özel hayatın gizliliği kişi haklarıdır ve bu haklardan devletin beklenmesi gereken şey MÜDAHALE ETMEMESİDİR (negatif edim) (B doğru). Bu haklar için devletten aktif bir hizmet sunması (A) beklenmez; bu, sosyal-ekonomik hakların özelliğidir. Bu haklar siyasi haklarla (C) veya yönetime katılımla (D, E) ilgili değildir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3e24c677-29e5-4c21-be49-c2efd6e1860d', 'Sosyal-ekonomik haklardır; devletin aktif hizmet sunmasını gerektirir', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3e24c677-29e5-4c21-be49-c2efd6e1860d', 'Kişi haklarıdır; devletin bu alana müdahale etmemesini gerektirir', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3e24c677-29e5-4c21-be49-c2efd6e1860d', 'Siyasi haklardır; yönetime katılımı sağlar', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3e24c677-29e5-4c21-be49-c2efd6e1860d', 'Kişi haklarıdır; devletin doğrudan maddi yardım sağlamasını gerektirir', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3e24c677-29e5-4c21-be49-c2efd6e1860d', 'Bu haklar hiçbir kategoriye girmez', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('b9400d46-bfb8-4157-9fae-b8f5de69ad4f', 'a761a66c-9aa8-45fe-a865-b4833c71d0b2', 'orta'::difficulty_level, 'Anayasanın 13. maddesine göre temel hak ve özgürlüklerin sınırlandırılmasıyla ilgili aşağıdakilerden hangisi yanlıştır?', 'Hakların sınırlandırılma esaslarını (madde 13) bilir.', 'Temel hak ve özgürlükler ancak KANUNLA sınırlanabilir; bir yönetmelikle sınırlanabileceği iddiası (D) yanlıştır ve sorunun cevabıdır. Sınırlamanın Anayasanın sözüne ve ruhuna uygun olması (A), demokratik toplum düzeninin gereklerine aykırı olmaması (B), ölçülülük ilkesine uygun olması (C) ve hakkın özüne dokunulamaması (E) doğru ilkelerdir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b9400d46-bfb8-4157-9fae-b8f5de69ad4f', 'Sınırlama Anayasanın sözüne ve ruhuna aykırı olamaz', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b9400d46-bfb8-4157-9fae-b8f5de69ad4f', 'Sınırlama demokratik toplum düzeninin gereklerine aykırı olamaz', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b9400d46-bfb8-4157-9fae-b8f5de69ad4f', 'Sınırlama ölçülülük ilkesine uygun olmalıdır', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b9400d46-bfb8-4157-9fae-b8f5de69ad4f', 'Temel hak ve özgürlükler bir yönetmelikle de sınırlanabilir', true, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b9400d46-bfb8-4157-9fae-b8f5de69ad4f', 'Sınırlama hakkın özüne dokunamaz', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('564c16b8-956c-4b39-9ecc-efa298aadb94', 'a761a66c-9aa8-45fe-a865-b4833c71d0b2', 'zor'::difficulty_level, 'Olağanüstü hal ilan edilen bir dönemde, savaş hukukuna uygun fiiller sonucu meydana gelen ölümler dışında, aşağıdaki haklardan hangisine yönelik bir sınırlama Anayasa''ya göre YAPILAMAZ?', 'Olağanüstü hallerde dokunulamayan çekirdek hakları (madde 15) bilir.', 'Anayasanın 15. maddesine göre, olağanüstü hallerde bile kişinin yaşama hakkına ve maddi-manevi varlığının bütünlüğüne dokunulamaz (savaş hukukuna uygun fiiller sonucu ölümler hariç) (C doğru). Seyahat özgürlüğü (A), toplantı ve gösteri yürüyüşü hakkı (B), basın özgürlüğü (D) ve mülkiyet hakkı (E) olağanüstü hallerde durumun gerektirdiği ölçüde SINIRLANABİLECEK haklar arasındadır; bunlar madde 15''in mutlak/dokunulmaz çekirdeği kapsamında değildir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('564c16b8-956c-4b39-9ecc-efa298aadb94', 'Seyahat özgürlüğü', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('564c16b8-956c-4b39-9ecc-efa298aadb94', 'Toplantı ve gösteri yürüyüşü düzenleme hakkı', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('564c16b8-956c-4b39-9ecc-efa298aadb94', 'Yaşama hakkı ve kişinin maddi-manevi varlığının bütünlüğü', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('564c16b8-956c-4b39-9ecc-efa298aadb94', 'Basın özgürlüğü', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('564c16b8-956c-4b39-9ecc-efa298aadb94', 'Mülkiyet hakkı', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('e3cf87f5-2055-4a8f-83f2-e9ab2a7666d5', 'a761a66c-9aa8-45fe-a865-b4833c71d0b2', 'orta'::difficulty_level, 'Seçme ve seçilme hakkı ile siyasi parti kurma hakkı aşağıdaki hak kategorilerinden hangisinde yer alır?', 'Siyasi hakları sınıflandırır.', 'Seçme-seçilme hakkı ve siyasi parti kurma hakkı, vatandaşların devlet yönetimine katılımını sağlayan SİYASİ haklardır (D doğru). Bu haklar kişi hakları (A) gibi devletin müdahale etmemesini değil, sosyal-ekonomik haklar (B) gibi devletin doğrudan hizmet sunmasını da gerektirmez; doğal haklar (C) ve kültürel haklar (E) bu iki hakkı tanımlamak için kullanılan doğru kategoriler değildir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e3cf87f5-2055-4a8f-83f2-e9ab2a7666d5', 'Kişi hakları (koruyucu haklar)', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e3cf87f5-2055-4a8f-83f2-e9ab2a7666d5', 'Sosyal ve ekonomik haklar', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e3cf87f5-2055-4a8f-83f2-e9ab2a7666d5', 'Doğal haklar', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e3cf87f5-2055-4a8f-83f2-e9ab2a7666d5', 'Siyasi haklar', true, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e3cf87f5-2055-4a8f-83f2-e9ab2a7666d5', 'Kültürel haklar', false, 4);

insert into topics (id, subject_id, name, slug, kazanim_text, weight, order_index) values ('dafcd822-68ff-458c-b30b-00446742dcb2', 'a9ee39e3-e35c-4ff0-885a-4af773855d4d', 'Uluslararası Kuruluşlar', 'uluslararasi-kuruluslar', 'Türkiye''nin üye olduğu başlıca uluslararası kuruluşları ve amaçlarını açıklar.', 1.0, 5);
insert into topic_contents (topic_id, summary, content_md, example_question) values ('dafcd822-68ff-458c-b30b-00446742dcb2', 'Türkiye''nin kurucu üye veya üye olduğu başlıca uluslararası kuruluşlar (Birleşmiş Milletler, NATO, Avrupa Konseyi, Avrupa Birliği adaylık süreci) ve her birinin amacı, kuruluş tarihi bu konunun omurgasını oluşturur.', '## Birleşmiş Milletler (BM)
1945''te kurulan ve uluslararası barış ve güvenliği korumayı amaçlayan BM''ye Türkiye KURUCU ÜYE olarak katılmıştır. Genel merkezi New York''tadır; Güvenlik Konseyi''nin 5 daimi üyesi (ABD, Rusya, Çin, İngiltere, Fransa) veto yetkisine sahiptir.

## NATO (Kuzey Atlantik Antlaşması Örgütü)
1949''da kurulan kolektif güvenlik/savunma örgütü olan NATO''ya Türkiye 1952''de üye olmuştur (Kore Savaşı''na asker göndermesinin ardından). Bir üyeye yapılan saldırı tüm üyelere yapılmış sayılır (kolektif savunma ilkesi).

## Avrupa Konseyi
1949''da kurulan, insan hakları, demokrasi ve hukukun üstünlüğü ilkelerini geliştirmeyi amaçlayan bir örgüttür; Türkiye kurucu üyelerindendir. Avrupa İnsan Hakları Mahkemesi (AİHM) Avrupa Konseyi''ne bağlıdır — bu, Avrupa Birliği''nden FARKLI bir kuruluştur ve sık sık karıştırılır.

## Avrupa Birliği (AB) ile İlişkiler
Türkiye 1959''da dönemin AET''sine (Avrupa Ekonomik Topluluğu) üyelik başvurusunda bulunmuş, 1963''te Ankara Anlaşması ile ortaklık statüsü kazanmış, 1996''da Gümrük Birliği''ne dahil olmuş, 1999 Helsinki Zirvesi''nde ADAY ÜLKE statüsü kazanmış ve 2005''te tam üyelik müzakerelerine resmen başlamıştır. Türkiye HENÜZ AB''ye tam üye DEĞİLDİR.

## Diğer Kuruluşlar
Türk Devletleri Teşkilatı (eski adıyla Türk Konseyi), Türk dilli bağımsız devletler (Azerbaycan, Kazakistan, Kırgızistan, Özbekistan, Türkiye) arasındaki iş birliğini geliştirmeyi amaçlar. İslam İşbirliği Teşkilatı (İİT), İslam ülkeleri arasındaki dayanışmayı artırmayı hedefler.

## Kritik Hap Notlar
- BM (1945) — Türkiye KURUCU ÜYE, genel merkezi New York.
- NATO (1949 kuruldu) — Türkiye 1952''de üye oldu (Kore Savaşı sonrası), kolektif savunma ilkesi.
- Avrupa Konseyi (1949) ≠ Avrupa Birliği — AİHM Avrupa Konseyi''ne bağlıdır, bu ikisi sıkça karıştırılır!
- AB süreci kronolojisi: 1959 başvuru → 1963 Ankara Anlaşması (ortaklık) → 1996 Gümrük Birliği → 1999 Helsinki Zirvesi (ADAY ülke statüsü) → 2005 tam üyelik müzakereleri başlangıcı. Türkiye HÂLÂ TAM ÜYE DEĞİLDİR.
- Türk Devletleri Teşkilatı, Türk dilli bağımsız devletleri (Azerbaycan, Kazakistan, Kırgızistan, Özbekistan, Türkiye) bir araya getirir.

## Video Ders Takip Rehberi
- [00:00 - 05:00] BM ve NATO''nun kuruluş amaçları ve Türkiye''nin üyelik tarihleri.
- [05:00 - 12:00] Avrupa Konseyi ile Avrupa Birliği arasındaki temel fark (AİHM''in bağlı olduğu kuruluş).
- [12:00 - 20:00] Türkiye-AB ilişkilerinin kronolojisi (1959-2005) örnek zaman çizelgesiyle pekiştirme.
- [20:00 - Bitiş] ÖSYM''nin çeldiricileri: Avrupa Konseyi ile Avrupa Birliği''nin karıştırılması, Türkiye''nin AB''ye "tam üye" olduğu yanılgısı.', 'Avrupa İnsan Hakları Mahkemesi (AİHM) hangi uluslararası kuruluşa bağlı olarak faaliyet göstermektedir?
A) Avrupa Birliği B) Avrupa Konseyi C) NATO D) Birleşmiş Milletler E) İslam İşbirliği Teşkilatı
Doğru Cevap: B — AİHM, Avrupa Birliği''nden farklı bir kuruluş olan Avrupa Konseyi''ne bağlıdır.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('50dbc797-35ec-4344-966c-1bb5aa584551', 'dafcd822-68ff-458c-b30b-00446742dcb2', 'kolay'::difficulty_level, 'Türkiye, Birleşmiş Milletler (BM) örgütüne hangi statüde katılmıştır?', 'Türkiye''nin BM''deki konumunu bilir.', 'Türkiye, 1945''te kurulan Birleşmiş Milletler''e KURUCU ÜYE olarak katılmıştır (B doğru). A, C, D ve E ifadeleri Türkiye''nin BM''deki gerçek statüsünü yansıtmaz; Türkiye sonradan katılan bir üye değil, örgütün kuruluşunda yer alan devletlerden biridir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('50dbc797-35ec-4344-966c-1bb5aa584551', 'Gözlemci üye olarak', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('50dbc797-35ec-4344-966c-1bb5aa584551', 'Kurucu üye olarak', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('50dbc797-35ec-4344-966c-1bb5aa584551', 'Aday üye olarak', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('50dbc797-35ec-4344-966c-1bb5aa584551', 'Geçici üye olarak', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('50dbc797-35ec-4344-966c-1bb5aa584551', 'Türkiye BM''ye hiç üye olmamıştır', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('fe6a4ce2-c283-4d3f-8f06-538aeff6c15d', 'dafcd822-68ff-458c-b30b-00446742dcb2', 'orta'::difficulty_level, 'Avrupa İnsan Hakları Mahkemesi (AİHM) ile ilgili aşağıdakilerden hangisi doğrudur?', 'AİHM''in bağlı olduğu kuruluşu (Avrupa Konseyi) doğru tanır.', 'AİHM, Avrupa Birliği''ne değil Avrupa Konseyi''ne bağlı bir kuruluştur; bu iki örgüt (Avrupa Konseyi ve AB) birbirinden farklıdır ve sıkça karıştırılır (C doğru). A ve B, AİHM''i Avrupa Birliği veya NATO ile ilişkilendirdiği için yanlıştır. D ve E de yanlış kuruluşlarla ilişkilendirmedir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('fe6a4ce2-c283-4d3f-8f06-538aeff6c15d', 'Avrupa Birliği''ne bağlı bir kuruluştur', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('fe6a4ce2-c283-4d3f-8f06-538aeff6c15d', 'NATO''nun bir alt organıdır', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('fe6a4ce2-c283-4d3f-8f06-538aeff6c15d', 'Avrupa Birliği''nden farklı bir kuruluş olan Avrupa Konseyi''ne bağlıdır', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('fe6a4ce2-c283-4d3f-8f06-538aeff6c15d', 'Birleşmiş Milletler''in bir alt organıdır', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('fe6a4ce2-c283-4d3f-8f06-538aeff6c15d', 'İslam İşbirliği Teşkilatı''na bağlıdır', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('dbe441d0-b20e-44f2-8a77-cba9c8936bf1', 'dafcd822-68ff-458c-b30b-00446742dcb2', 'zor'::difficulty_level, 'Türkiye-Avrupa Birliği ilişkilerinin kronolojik gelişimiyle ilgili aşağıdaki sıralamalardan hangisi doğrudur?', 'Türkiye-AB ilişkilerinin kronolojisini bilir.', 'Doğru kronoloji: 1959''da AET''ye üyelik başvurusu → 1963''te Ankara Anlaşması ile ortaklık statüsü → 1996''da Gümrük Birliği''ne dahil olma → 1999 Helsinki Zirvesi''nde aday ülke statüsü kazanma → 2005''te tam üyelik müzakerelerinin başlaması (C doğru). Diğer seçenekler bu olayların sırasını veya içeriğini yanlış vermektedir; örneğin bazıları Türkiye''nin bugün tam üye olduğunu ima etmektedir ki bu YANLIŞTIR — Türkiye hâlâ tam üye değildir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('dbe441d0-b20e-44f2-8a77-cba9c8936bf1', '1999 Helsinki Zirvesi → 1963 Ankara Anlaşması → 1959 başvuru → 2005 tam üyelik', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('dbe441d0-b20e-44f2-8a77-cba9c8936bf1', '1963 Ankara Anlaşması → 1959 başvuru → 2005 tam üyelik → 1999 aday statüsü', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('dbe441d0-b20e-44f2-8a77-cba9c8936bf1', '1959 başvuru → 1963 Ankara Anlaşması → 1996 Gümrük Birliği → 1999 aday ülke statüsü → 2005 müzakerelerin başlaması', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('dbe441d0-b20e-44f2-8a77-cba9c8936bf1', '1996 Gümrük Birliği → 1959 başvuru → 1999 tam üyelik → 2005 aday statüsü', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('dbe441d0-b20e-44f2-8a77-cba9c8936bf1', '2005 tam üyelik → 1999 aday statüsü → 1963 Ankara Anlaşması → 1959 başvuru', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('e389d72c-6716-43df-ada7-d2e62ec18521', 'dafcd822-68ff-458c-b30b-00446742dcb2', 'orta'::difficulty_level, 'Azerbaycan, Kazakistan, Kırgızistan, Özbekistan ve Türkiye arasındaki iş birliğini geliştirmeyi amaçlayan uluslararası kuruluş aşağıdakilerden hangisidir?', 'Türk Devletleri Teşkilatı''nın amacını ve üyelerini bilir.', 'Türk Devletleri Teşkilatı (eski adıyla Türk Konseyi), Türk dilli bağımsız devletler arasındaki iş birliğini geliştirmeyi amaçlayan bir kuruluştur (B doğru). NATO (A) bir savunma örgütüdür ve bu ülkelerin tamamını kapsamaz. Avrupa Konseyi (C) ve Avrupa Birliği (D) Avrupa odaklı kuruluşlardır, bu Orta Asya/Türk devletleriyle ilgili değildir. Birleşmiş Milletler (E) evrensel bir örgüttür, bu spesifik iş birliğini tanımlamaz.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e389d72c-6716-43df-ada7-d2e62ec18521', 'NATO', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e389d72c-6716-43df-ada7-d2e62ec18521', 'Türk Devletleri Teşkilatı', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e389d72c-6716-43df-ada7-d2e62ec18521', 'Avrupa Konseyi', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e389d72c-6716-43df-ada7-d2e62ec18521', 'Avrupa Birliği', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e389d72c-6716-43df-ada7-d2e62ec18521', 'Birleşmiş Milletler', false, 4);

