-- KPSS Coğrafya: 5 ana konu için tam kapsamlı içerik (özet, ders notu, örnek soru)
-- ve her konu için 4'er soru + 5'er seçenek. Var olan konular (Türkiye'nin Yeri ve
-- Konumu, İklim, Nüfus ve Yerleşme) topic_contents UPSERT ile zenginleştiriliyor;
-- eksik olan iki konu (Türkiye'nin Yerşekilleri, Ekonomik Coğrafya) yeni topic olarak ekleniyor.

insert into topic_contents (topic_id, summary, content_md, example_question) values ('73d24254-55ed-43ae-8627-1456e48059b4', 'Türkiye''nin matematik konumu (enlem-boylam) ile özel konumu (yakın çevre ilişkileri) birbirinden ayrı sonuçlar doğurur; KPSS bu iki kavramı ve sonuçlarını karıştırmadan ayırt edebilmeyi ölçer.', '## Matematik Konum ve Sonuçları
Türkiye 36-42 kuzey enlemleri, 26-45 doğu boylamları arasında yer alır. Matematik konumun (enlemin) doğrudan sonuçları şunlardır: dört mevsimin belirgin yaşanması, güneş ışınlarının geliş açısının ve gölge boyu uzunluğunun mevsime/mekâna göre değişmesi, yerel saat farklarının doğuda daha ileri, batıda daha geri olması, gündüz-gece süresinin yıl içinde ve yerden yere değişmesi.

## Özel Konum ve Sonuçları
Özel konum, Türkiye''nin yakın çevresiyle olan beşerî-ekonomik-siyasi ilişkilerini ifade eder: üç kıtaya (Asya-Avrupa-Afrika) yakınlık, İstanbul ve Çanakkale Boğazlarının jeopolitik/ticari önemi, çok sayıda komşu ülkeye (8 komşu) sahip olması, önemli kara-demir-boru hattı güzergâhları üzerinde bulunması, iklim ve bitki örtüsü çeşitliliği, turizm potansiyelinin yüksekliği.

## En Kritik Ayrım
Bir sonucun matematik konuma mı yoksa özel konuma mı ait olduğunu belirlemek bu konudaki soruların can damarıdır: "mevsimler, yerel saat, gölge boyu, güneş ışını açısı" → matematik konum; "komşu sayısı, boğazlar, kıtalararası konum, ticaret yolları, turizm çeşitliliği" → özel konum.

## Kritik Hap Notlar
- Matematik konum sonuçları: yerel saat farkı, dört mevsimin belirgin yaşanması, gölge boyu ve güneş ışını geliş açısının değişmesi, gündüz-gece süresi farkı.
- Özel konum sonuçları: üç kıtaya yakınlık, boğazların jeopolitik önemi, 8 komşu ülke, ulaşım/ticaret güzergâhları, turizm çeşitliliği.
- Türkiye idari olarak TEK bir saat dilimini benimser; bu siyasi/idari bir tercihtir, matematik konumun getirdiği gerçek yerel saat farkını ortadan kaldırmaz.
- "26-45 doğu boylamları, 36-42 kuzey enlemleri" rakamları ezber gerektirir ama asıl önemli olan HANGİ SONUCUN hangi konuma ait olduğudur.
- Sınır uzunluğu ve komşu sayısı özel konumun sonucudur, enlem/boylamla (matematik konumla) ilgisi yoktur.

## Video Ders Takip Rehberi
- [00:00 - 05:00] Matematik konum tanımı ve Türkiye''nin enlem-boylam aralığı.
- [05:00 - 12:00] Matematik konumun sonuçları: yerel saat, mevsimler, gölge boyu, güneş ışını açısı.
- [12:00 - 20:00] Özel konum ve sonuçları: üç kıtaya yakınlık, boğazlar, komşular, ticaret yolları — harita üzerinden pekiştirme.
- [20:00 - Bitiş] ÖSYM''nin en sevdiği tuzak: bir sonucun matematik mi özel mi konuma ait olduğunun karıştırılması.', 'Türkiye''de Van''da güneş İstanbul''a göre daha erken doğar. Bu durum aşağıdakilerden hangisiyle açıklanır?
A) Türkiye''nin özel konumu B) Türkiye''nin matematik konumu (boylam etkisi) C) Türkiye''nin komşu sayısı D) Türkiye''nin yüzölçümü E) Türkiye''nin turizm potansiyeli
Doğru Cevap: B — Yerel saat farkı doğrudan boylam farkına bağlıdır, bu da matematik konumun bir sonucudur.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('60432c81-98e2-422e-bb1c-91d668b9d77c', '73d24254-55ed-43ae-8627-1456e48059b4', 'kolay'::difficulty_level, 'Türkiye''nin matematik konumunun bir sonucu olarak aşağıdakilerden hangisi gösterilebilir?', 'Matematik konumun sonuçlarını ayırt eder.', 'Yerel saat farkı doğrudan enlem-boylam konumuna, yani matematik konuma bağlıdır (B doğru). Komşu sayısı (A), boğazların önemi (C), turizm çeşitliliği (D) ve ticaret yollarının üzerinde bulunma (E) özel konumun sonuçlarıdır; beşerî/siyasi ilişkilerle ilgilidir, enlem-boylamla değil.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('60432c81-98e2-422e-bb1c-91d668b9d77c', 'Sekiz komşu ülkeye sahip olması', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('60432c81-98e2-422e-bb1c-91d668b9d77c', 'Doğu ile batı arasında yerel saat farkının bulunması', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('60432c81-98e2-422e-bb1c-91d668b9d77c', 'İstanbul ve Çanakkale Boğazlarının jeopolitik öneme sahip olması', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('60432c81-98e2-422e-bb1c-91d668b9d77c', 'Turizm gelirlerinin çeşitlilik göstermesi', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('60432c81-98e2-422e-bb1c-91d668b9d77c', 'Önemli ticaret yolları üzerinde bulunması', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('3ab1fc08-0722-4471-85b6-70385dec62ce', '73d24254-55ed-43ae-8627-1456e48059b4', 'orta'::difficulty_level, 'Aşağıdakilerden hangisi Türkiye''nin özel konumunun bir sonucu değildir?', 'Özel konum sonuçlarını matematik konum sonuçlarından ayırt eder.', 'Gölge boylarının mevsimden mevsime değişmesi, güneş ışınlarının geliş açısındaki (yani enlem/matematik konumdaki) değişime bağlıdır (E doğru, bu bir özel konum sonucu DEĞİLDİR). Üç kıtaya yakınlık (A), boğazların önemi (B), 8 komşu (C) ve ticaret yollarının kesişmesi (D) özel konumun tipik sonuçlarıdır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3ab1fc08-0722-4471-85b6-70385dec62ce', 'Üç kıtaya yakın olması', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3ab1fc08-0722-4471-85b6-70385dec62ce', 'Boğazların jeopolitik açıdan önemli olması', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3ab1fc08-0722-4471-85b6-70385dec62ce', 'Sekiz ülkeyle komşu olması', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3ab1fc08-0722-4471-85b6-70385dec62ce', 'Kara, demir ve boru hattı ticaret yollarının kesişim noktasında bulunması', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3ab1fc08-0722-4471-85b6-70385dec62ce', 'Gölge boylarının mevsimden mevsime değişmesi', true, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('3512b847-e2b9-419a-b2fc-65d2b7a0ad8e', '73d24254-55ed-43ae-8627-1456e48059b4', 'zor'::difficulty_level, 'Bir öğrenci, Türkiye''nin konumu ile ilgili şu çıkarımları yapmıştır:
I. Yerel saat farkı, Türkiye''nin özel konumunun bir sonucudur.
II. Dört mevsimin belirgin yaşanması matematik konumun sonucudur.
III. Türkiye''nin tek saat dilimini idari olarak benimsemesi, doğu-batı arasındaki GERÇEK yerel saat farkının fiilen ortadan kalktığı anlamına gelir.
Bu çıkarımlardan hangileri YANLIŞTIR?', 'Matematik/özel konum kavramlarını ileri düzeyde ayırt eder.', 'II doğrudur; dört mevsimin belirgin yaşanması, güneş ışınlarının geliş açısının enleme bağlı değişimiyle ilgilidir, yani matematik konumun sonucudur. I ise YANLIŞTIR çünkü yerel saat farkı boylama (matematik konuma) bağlıdır, özel konuma değil. III de YANLIŞTIR çünkü tek saat dilimi kullanımı yalnızca idari/siyasi bir tercihtir; doğu ile batı arasındaki coğrafi/gerçek yerel saat farkı (güneşin doğuş-batış saatleri açısından) fiilen var olmaya devam eder, sadece resmi saatlerde bu fark yansıtılmaz.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3512b847-e2b9-419a-b2fc-65d2b7a0ad8e', 'Yalnız I', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3512b847-e2b9-419a-b2fc-65d2b7a0ad8e', 'Yalnız II', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3512b847-e2b9-419a-b2fc-65d2b7a0ad8e', 'I ve III', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3512b847-e2b9-419a-b2fc-65d2b7a0ad8e', 'II ve III', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3512b847-e2b9-419a-b2fc-65d2b7a0ad8e', 'I, II ve III', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('4a51bc7f-ca78-4090-960c-631569937f22', '73d24254-55ed-43ae-8627-1456e48059b4', 'orta'::difficulty_level, 'Türkiye''nin sınırlarının uzunluğu ve komşu ülke sayısının fazla olması, aşağıdaki konum unsurlarından hangisiyle açıklanır?', 'Sınır ve komşuluk ilişkilerini konum unsurlarıyla ilişkilendirir.', 'Sınır uzunluğu ve komşu ülke sayısı, ülkenin coğrafi olarak hangi bölgede, hangi devletlerle çevrili olduğuyla ilgili olduğu için özel konumun bir sonucudur (B doğru). Matematik konum (A) enlem-boylama bağlı sonuçları (yerel saat, mevsimler) ifade eder ve sınır/komşuluk ile doğrudan ilgili değildir. C, D, E seçenekleri konu dışı, anlamsız çeldiricilerdir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4a51bc7f-ca78-4090-960c-631569937f22', 'Matematik konum', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4a51bc7f-ca78-4090-960c-631569937f22', 'Özel konum', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4a51bc7f-ca78-4090-960c-631569937f22', 'Yerel saat farkı', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4a51bc7f-ca78-4090-960c-631569937f22', 'Gölge boyu uzunluğu', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4a51bc7f-ca78-4090-960c-631569937f22', 'Güneş ışınlarının geliş açısı', false, 4);

insert into topic_contents (topic_id, summary, content_md, example_question) values ('f4bdef2c-d148-4d88-832f-731b8e3d122c', 'Türkiye''de görülen dört büyük iklim tipinin (Karadeniz, Akdeniz, karasal, Marmara geçiş) yağış rejimi, sıcaklık özellikleri ve görüldüğü bölgeler; bu tiplerin birbirinden ayırt edilmesi KPSS''de en sık sorulan alt başlıktır.', '## Karadeniz İklimi
Her mevsim yağışlı, yazı en yağışlı mevsim olan (yaz kuraklığı görülmeyen tek iklim tipi) bir iklimdir; yıllık yağış miktarı ve yıl içi dağılımı en dengeli iklimimizdir. Doğu Karadeniz''de yağış miktarı Türkiye ortalamasının kat kat üzerindedir (bakı ve dağların kıyıya paralel uzanışı nedeniyle).

## Akdeniz İklimi
Yazları sıcak ve kurak, kışları ılık ve yağışlı geçen; yağışın büyük kısmının kış mevsiminde düştüğü bir iklimdir. Doğal bitki örtüsü maki (bodur, çalı formunda, kuraklığa dayanıklı) dir. Kışın kar yağışı görülse de kısa sürede erir.

## Karasal İklim(ler)
İç Anadolu, Doğu Anadolu ve Güneydoğu Anadolu''da farklı alt tipleriyle görülür: yazları sıcak-kurak, kışları soğuk ve karlı geçer; yıllık ve günlük sıcaklık farkı (kara ikliminin karakteristik özelliği) çok fazladır. Doğal bitki örtüsü step (bozkır)tir. Doğu Anadolu, yükseltinin fazla olması nedeniyle Türkiye''nin en soğuk kışlarının yaşandığı bölgedir.

## Marmara (Geçiş) İklimi
Karadeniz ile Akdeniz iklimi arasında bir geçiş özelliği taşır; yazları Akdeniz kadar kurak, kışları Karadeniz kadar yağışlı olmayan ILIMLI bir iklimdir. Bitki örtüsü olarak hem orman hem de maki bir arada (karışık) görülür.

## Kritik Hap Notlar
- Yaz kuraklığı GÖRÜLMEYEN tek iklim: Karadeniz iklimi — "her mevsim yağışlı, en yağışlı mevsim yaz" ifadesi doğrudan Karadeniz''i işaret eder.
- Yıllık/günlük sıcaklık farkının EN FAZLA olduğu iklim: karasal iklim — deniz etkisinden uzaklık nedeniyle.
- Doğal bitki örtüsü eşleştirmesi: Karadeniz=orman (gür, geniş yapraklı-iğne yapraklı karışık), Akdeniz=maki, Karasal=step (bozkır), Marmara=karışık (orman+maki).
- En fazla yağış alan yer Doğu Karadeniz (Rize ve çevresi); en az yağış alan yerler ise Tuz Gölü çevresi ve İç Anadolu''nun bazı çukur alanları ile Iğdır Ovası''dır.
- Akdeniz ikliminde yağışın mevsimlik dağılımı: KIŞ en yağışlı, YAZ en kurak mevsimdir — Karadeniz ile karıştırılmamalıdır (Karadeniz''de yaz kurak DEĞİLDİR).
- Bakı (bir yamacın güneşe bakma durumu) ve dağların kıyıya paralel/dik uzanışı, Karadeniz kıyısındaki yağış miktarının doğuya doğru artmasını açıklayan temel faktördür.

## Video Ders Takip Rehberi
- [00:00 - 05:00] İklim tiplerinin genel tanıtımı ve Türkiye''de görülen dört ana iklim tipi.
- [05:00 - 12:00] Her iklim tipinin yağış rejimi, sıcaklık özelliği ve bitki örtüsü eşleştirmesi.
- [12:00 - 20:00] Bölge-iklim örneklemesi: Rize (Karadeniz), Antalya (Akdeniz), Erzurum (Karasal/Doğu Anadolu), Bursa (Marmara geçiş) üzerinden pekiştirme.
- [20:00 - Bitiş] ÖSYM''nin çeldiricileri: Akdeniz ile Karadeniz''in yağış mevsimi karıştırması, karasal iklim alt tiplerinin (İç Anadolu/Doğu Anadolu/GAP) birbirine karıştırılması.', 'Bir bölgede yazları çok sıcak ve kurak, kışları soğuk ve kar yağışlı geçmekte, yıllık sıcaklık farkı oldukça fazla olmaktadır. Bu bölgede aşağıdaki iklim tiplerinden hangisi görülmektedir?
A) Karadeniz iklimi B) Akdeniz iklimi C) Karasal iklim D) Ekvatoral iklim E) Muson iklimi
Doğru Cevap: C — Yıllık sıcaklık farkının fazla olması ve yaz-kış zıtlığı karasal iklimin temel özelliğidir.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('c70f3a79-658f-41e6-8736-1266871c103f', 'f4bdef2c-d148-4d88-832f-731b8e3d122c', 'kolay'::difficulty_level, 'Her mevsim yağışlı olan, yazın en yağışlı mevsim olduğu iklim tipi aşağıdakilerden hangisidir?', 'İklim tiplerinin yağış rejimi özelliklerini bilir.', 'Karadeniz iklimi, Türkiye''de yaz kuraklığının görülmediği tek iklim tipidir; her mevsim yağış alır ve en fazla yağış yaz aylarında düşer (A doğru). Akdeniz (B) yazın kurak, kışın yağışlıdır. Karasal iklim (C) yazın kurak geçer. Marmara (D) geçiş özelliği taşır ama Karadeniz kadar dengeli değildir. Muson iklimi (E) Türkiye''de görülmez, bu bir çeldiricidir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c70f3a79-658f-41e6-8736-1266871c103f', 'Karadeniz iklimi', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c70f3a79-658f-41e6-8736-1266871c103f', 'Akdeniz iklimi', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c70f3a79-658f-41e6-8736-1266871c103f', 'Karasal iklim', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c70f3a79-658f-41e6-8736-1266871c103f', 'Marmara (geçiş) iklimi', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c70f3a79-658f-41e6-8736-1266871c103f', 'Muson iklimi', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('1281007a-bc8f-40ed-b9d5-e4e5091b05a0', 'f4bdef2c-d148-4d88-832f-731b8e3d122c', 'orta'::difficulty_level, 'Aşağıdaki iklim-bitki örtüsü eşleştirmelerinden hangisi yanlıştır?', 'İklim tiplerini karakteristik bitki örtüleriyle eşleştirir.', 'Karasal iklimin doğal bitki örtüsü step (bozkır)tir, orman DEĞİLDİR (D yanlış ve sorunun cevabı) — orman, nemli/yağışlı iklimlerin (Karadeniz, Marmara) tipik bitki örtüsüdür. Karadeniz-orman (A), Akdeniz-maki (B) ve Marmara-karışık orman+maki (C) eşleştirmeleri doğrudur. E seçeneği (step-kurakçıl bitkiler) de doğrudur, karasal iklimle tutarlıdır ama soru ''yanlış'' eşleştirmeyi sorduğu için D cevaptır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1281007a-bc8f-40ed-b9d5-e4e5091b05a0', 'Karadeniz iklimi – gür orman', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1281007a-bc8f-40ed-b9d5-e4e5091b05a0', 'Akdeniz iklimi – maki', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1281007a-bc8f-40ed-b9d5-e4e5091b05a0', 'Marmara (geçiş) iklimi – karışık orman ve maki', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1281007a-bc8f-40ed-b9d5-e4e5091b05a0', 'Karasal iklim – gür orman', true, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1281007a-bc8f-40ed-b9d5-e4e5091b05a0', 'Karasal iklim – step (bozkır)', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('3b6e9fcb-fb85-4d1f-8012-c08aaad6f8b6', 'f4bdef2c-d148-4d88-832f-731b8e3d122c', 'zor'::difficulty_level, 'Aşağıdaki haritada A ve B noktaları Türkiye''nin farklı kıyı kesimlerinde yer almaktadır. A noktasında yıllık yağış miktarı 2000 mm''nin üzerindeyken, aynı iklim tipinin görüldüğü B noktasında bu miktar 700 mm civarındadır. Bu farkın en önemli nedeni aşağıdakilerden hangisidir?', 'Aynı iklim tipi içindeki yağış miktarı farklarını bakı ve dağların uzanış doğrultusuyla ilişkilendirir.', 'Karadeniz kıyısında yağış miktarındaki bu tür büyük farklar, dağların kıyıya paralel uzanması ve nemli hava kütlelerinin karşılaştığı yamaçların bakı (güneşe/denize bakma) durumuna bağlıdır; Doğu Karadeniz''de dağlar denize daha dik/yakın ve yükselti daha fazla olduğundan yağış miktarı dramatik biçimde artar (D doğru). Enlem farkı (A) bu kısa mesafede ihmal edilebilir düzeydedir. Toprak tipi (B) ve bitki örtüsü yoğunluğu (C) yağışın SONUCUdur, NEDENİ değildir — sebep-sonuç ters çevrilmiştir. Deniz suyu sıcaklığı (E) yağış miktarındaki bu büyüklükte bir farkı açıklayacak temel faktör değildir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3b6e9fcb-fb85-4d1f-8012-c08aaad6f8b6', 'İki nokta arasındaki enlem farkının çok büyük olması', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3b6e9fcb-fb85-4d1f-8012-c08aaad6f8b6', 'B noktasındaki toprak tipinin farklı olması', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3b6e9fcb-fb85-4d1f-8012-c08aaad6f8b6', 'A noktasındaki bitki örtüsünün daha yoğun olması', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3b6e9fcb-fb85-4d1f-8012-c08aaad6f8b6', 'Dağların kıyıya paralel uzanması ve bakı farkının nemli hava kütlelerinin yükselişini etkilemesi', true, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3b6e9fcb-fb85-4d1f-8012-c08aaad6f8b6', 'B noktasındaki deniz suyu sıcaklığının daha düşük olması', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('af979c88-5085-4f87-ad40-e1cb595da5a1', 'f4bdef2c-d148-4d88-832f-731b8e3d122c', 'orta'::difficulty_level, 'Doğu Anadolu Bölgesi''nde kışların Türkiye''nin geri kalanına göre daha sert ve soğuk geçmesinin temel nedeni aşağıdakilerden hangisidir?', 'Yükseltinin iklim üzerindeki etkisini açıklar.', 'Doğu Anadolu''nun ortalama yükseltisinin Türkiye''nin diğer bölgelerine göre çok daha fazla olması, sıcaklığın yükseklikle birlikte düşmesi (her 200 metrede yaklaşık 1°C azalma) ilkesi gereği kışların olağanüstü sert ve soğuk geçmesine neden olur (B doğru). Enlem farkı (A) tek başına bu kadar büyük bir sıcaklık farkını açıklamaz. Karadeniz''e yakınlık (C) tam tersine ılımanlaştırıcı bir etki yapardı ama dağlar bu etkiyi engeller. Toprak tipi (D) ve bitki örtüsü (E) sıcaklık farkının nedeni değil, iklimin bir sonucudur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('af979c88-5085-4f87-ad40-e1cb595da5a1', 'Enlem derecesinin çok yüksek olması', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('af979c88-5085-4f87-ad40-e1cb595da5a1', 'Bölgenin ortalama yükseltisinin fazla olması', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('af979c88-5085-4f87-ad40-e1cb595da5a1', 'Karadeniz''e yakın olması', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('af979c88-5085-4f87-ad40-e1cb595da5a1', 'Toprak tipinin farklı olması', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('af979c88-5085-4f87-ad40-e1cb595da5a1', 'Bitki örtüsünün seyrek olması', false, 4);

insert into topics (id, subject_id, name, slug, kazanim_text, weight, order_index) values ('714f0c66-ba93-4fc8-8b82-9b0800a7350f', 'e096912f-78c9-431d-8a7b-f5b3c005f472', 'Türkiye''nin Yerşekilleri', 'turkiyenin-yersekilleri', 'Türkiye''nin yer şekillerinin oluşumunu ve dağılışını, bunların ekonomik faaliyetlere etkisiyle birlikte açıklar.', 1.0, 6);
insert into topic_contents (topic_id, summary, content_md, example_question) values ('714f0c66-ba93-4fc8-8b82-9b0800a7350f', 'Türkiye''nin dağların kıyıya paralel uzandığı, ortalama yükseltisinin (yaklaşık 1132 m) Avrupa''ya göre yüksek olduğu, III. Jeolojik zamanda oluşan genç ve halen deprem üretebilen bir arazi yapısına sahip olduğu gerçeği; bu konu genellikle deprem, akarsu, ova/plato/dağ ayrımı üzerinden sorulur.', '## Oluşum ve Genel Özellikler
Türkiye, III. (Neojen-Tersiyer) Jeolojik Zamanda gerçekleşen Alp-Himalaya orojenezi (dağ oluşumu) sırasında şekillenmiş GENÇ bir arazi yapısına sahiptir. Bu gençlik nedeniyle yer şekilleri henüz aşınmaya yeterince uğramamış, DİK ve ENGEBELİDİR; ayrıca fay hatları hâlâ aktiftir, bu yüzden Türkiye önemli bir deprem kuşağındadır (Kuzey Anadolu Fay Hattı ve Doğu Anadolu Fay Hattı en bilinenleridir).

## Dağların Uzanışı
Türkiye''de dağlar genel olarak KIYIYA PARALEL uzanır (Kuzey Anadolu Dağları ve Toros Dağları); bunun en önemli sonucu, kıyı ile iç kesimler arasındaki ulaşımın zorlaşması ve denizel iklimin iç kesimlere fazla sokulamamasıdır (kıyı ile iç kesim arasında iklim/bitki örtüsü farkının keskin olması).

## Ova, Plato ve Havzalar
Ovalar; akarsuların taşıdığı alüvyonlarla (delta ovaları, örn. Çukurova, Bafra, Çarşamba) veya çöküntü hatları boyunca (tektonik ovalar, örn. Gediz, Büyük Menderes) oluşur. Platolar (İç Anadolu''daki Haymana, Obruk Platosu gibi) çevresine göre yüksekte, akarsularla yer yer yarılmış düzlüklerdir ve genellikle hayvancılık faaliyetlerinde kullanılır. Havzalar (Erzurum-Erzincan, Muş Ovası) çevresi dağlarla çevrili çöküntü alanlarıdır.

## Akarsular
Türkiye akarsuları genel olarak KISA, DEBİLERİ DÜZENSİZ ve EĞİMLERİ FAZLADIR (bu nedenle hidroelektrik potansiyeli yüksektir ama ulaşıma elverişli değildir). En uzun akarsuyu Kızılırmak''tır (ama en fazla su taşıyanı, yani debisi en yüksek akarsu Fırat''tır) — bu ikisinin karıştırılması ÖSYM''nin klasik tuzağıdır.

## Kritik Hap Notlar
- Türkiye yer şekilleri III. Jeolojik Zamanda oluşmuş GENÇ bir yapıdır → hem dik/engebeli arazi hem de aktif deprem kuşağı bununla açıklanır.
- Dağların KIYIYA PARALEL uzanması → kıyı-iç kesim ulaşımını zorlaştırır, denizelliğin içe sokulmasını engeller.
- EN UZUN akarsu: Kızılırmak. EN FAZLA SU TAŞIYAN (debisi en yüksek) akarsu: Fırat. Bu ikisi ASLA karıştırılmamalıdır.
- Türkiye akarsularının ortak özelliği: kısa boylu, düzensiz rejimli (debili), eğimi fazla → ulaşıma elverişsiz ama hidroelektrik potansiyeli yüksek.
- Delta ovaları (Çukurova, Bafra, Çarşamba) akarsu biriktirmesiyle; tektonik ovalar (Gediz, Büyük Menderes) çöküntü hareketiyle oluşur — oluşum mekanizması farklıdır.
- Platolar hayvancılık (özellikle yayla hayvancılığı) için elverişlidir; bu, düz ama yüksekte olmaları ve iklim koşullarıyla ilgilidir.

## Video Ders Takip Rehberi
- [00:00 - 05:00] Türkiye yer şekillerinin oluşum zamanı (III. Jeolojik Zaman) ve genel özellikleri (genç, engebeli, deprem kuşağı).
- [05:00 - 12:00] Dağların kıyıya paralel uzanışı ve bunun ulaşım/iklime etkisi.
- [12:00 - 20:00] Ova-plato-havza ayrımı ve akarsu özellikleri (Kızılırmak-Fırat karşılaştırması) örnek harita üzerinden.
- [20:00 - Bitiş] ÖSYM''nin çeldiricileri: en uzun/en fazla su taşıyan akarsu karışıklığı, delta ovası ile tektonik ovanın oluşum mekanizmasının karıştırılması.', 'Türkiye''nin en uzun akarsuyu ile debisi (su miktarı) en fazla olan akarsuyu aşağıdakilerin hangisinde doğru verilmiştir?
A) Kızılırmak - Fırat B) Fırat - Kızılırmak C) Sakarya - Dicle D) Fırat - Dicle E) Kızılırmak - Sakarya
Doğru Cevap: A — Kızılırmak en uzun, Fırat ise en fazla su taşıyan (debisi en yüksek) akarsudur.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('f0be4e6c-fa70-4728-9ad2-6d10934e78ba', '714f0c66-ba93-4fc8-8b82-9b0800a7350f', 'kolay'::difficulty_level, 'Türkiye''de dağların genel olarak kıyıya paralel uzanmasının en belirgin sonucu aşağıdakilerden hangisidir?', 'Dağların uzanış doğrultusunun ulaşım ve iklime etkisini açıklar.', 'Dağların kıyıya paralel uzanması, kıyı kesimi ile iç kesimler arasındaki ulaşımı zorlaştırır ve denizel iklimin etkisinin iç kesimlere kolayca sokulamamasına neden olur (B doğru). Bu durum akarsu debisiyle (A), toprak verimliliğiyle (C), maden çeşitliliğiyle (D) veya nüfus yoğunluğuyla (E) doğrudan ilgili değildir; bunlar başka etmenlere bağlıdır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f0be4e6c-fa70-4728-9ad2-6d10934e78ba', 'Akarsuların debisinin artması', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f0be4e6c-fa70-4728-9ad2-6d10934e78ba', 'Kıyı ile iç kesimler arasında ulaşımın zorlaşması', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f0be4e6c-fa70-4728-9ad2-6d10934e78ba', 'Toprakların daha verimli hale gelmesi', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f0be4e6c-fa70-4728-9ad2-6d10934e78ba', 'Maden çeşitliliğinin artması', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f0be4e6c-fa70-4728-9ad2-6d10934e78ba', 'Nüfusun kıyıdan iç kesimlere kaymasının hızlanması', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('990ea0e8-a49e-490f-878c-869daebb603e', '714f0c66-ba93-4fc8-8b82-9b0800a7350f', 'orta'::difficulty_level, 'Türkiye''nin yer şekillerinin III. Jeolojik Zamanda oluşmuş genç bir yapıya sahip olmasının doğal bir sonucu aşağıdakilerden hangisidir?', 'Yer şekillerinin oluşum yaşı ile deprem riski arasındaki ilişkiyi açıklar.', 'Genç bir arazi yapısı, fay hatlarının hâlâ aktif olması anlamına gelir; bu da Türkiye''nin önemli bir deprem kuşağında yer almasını doğrudan açıklar (C doğru). Akarsuların debisinin düzenli olması (A) tam tersine yanlıştır, Türkiye akarsuları düzensiz rejimlidir. Ova sayısının azlığı (B), maden yataklarının bulunmayışı (D) ve iklim çeşitliliğinin olmayışı (E) yer şekillerinin gençliğiyle doğrudan ilişkili değildir/gerçeği yansıtmaz.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('990ea0e8-a49e-490f-878c-869daebb603e', 'Akarsuların debisinin çok düzenli olması', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('990ea0e8-a49e-490f-878c-869daebb603e', 'Ova sayısının ülke genelinde çok az olması', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('990ea0e8-a49e-490f-878c-869daebb603e', 'Fay hatlarının hâlâ aktif olması nedeniyle önemli bir deprem kuşağında yer alınması', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('990ea0e8-a49e-490f-878c-869daebb603e', 'Maden yataklarının hiç bulunmaması', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('990ea0e8-a49e-490f-878c-869daebb603e', 'İklim çeşitliliğinin görülmemesi', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('abec4e12-ee97-423b-96b5-cc75b11c9c80', '714f0c66-ba93-4fc8-8b82-9b0800a7350f', 'zor'::difficulty_level, 'Bir öğrenci Türkiye''deki ovalarla ilgili şu çıkarımları yapmıştır:
I. Çukurova, Bafra ve Çarşamba ovaları akarsuların taşıdığı alüvyonların birikmesiyle oluşmuştur.
II. Gediz ve Büyük Menderes ovaları tamamen akarsu biriktirmesiyle oluşmuş olup tektonik hareketlerle hiçbir ilgisi yoktur.
III. Platolar, çevresine göre yüksekte yer alan ve akarsularla yer yer yarılmış düzlüklerdir.
Bu çıkarımlardan hangileri doğrudur?', 'Ova ve plato oluşum mekanizmalarını ileri düzeyde ayırt eder.', 'I doğrudur; Çukurova, Bafra, Çarşamba gibi delta ovaları akarsu biriktirmesiyle (alüvyon) oluşur. III de doğrudur, bu platoların standart tanımıdır. II ise YANLIŞTIR çünkü Gediz ve Büyük Menderes ovaları öncelikle TEKTONİK (çöküntü) hareketlerle oluşmuş, üzerine sonradan akarsu alüvyonlarının da eklenmesiyle bugünkü hâlini almış ''tektonik ovalar''dır — akarsu birikmesiyle hiç ilgisi olmadığı iddiası tamamen yanlıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('abec4e12-ee97-423b-96b5-cc75b11c9c80', 'Yalnız I', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('abec4e12-ee97-423b-96b5-cc75b11c9c80', 'Yalnız II', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('abec4e12-ee97-423b-96b5-cc75b11c9c80', 'I ve III', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('abec4e12-ee97-423b-96b5-cc75b11c9c80', 'II ve III', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('abec4e12-ee97-423b-96b5-cc75b11c9c80', 'I, II ve III', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('1412e17d-c371-4a26-ba82-045308e93fc4', '714f0c66-ba93-4fc8-8b82-9b0800a7350f', 'orta'::difficulty_level, 'Türkiye akarsularının ortak özellikleriyle ilgili aşağıdaki ifadelerden hangisi yanlıştır?', 'Türkiye akarsularının genel özelliklerini bilir.', 'Türkiye akarsuları genel olarak eğimin fazla olması nedeniyle hidroelektrik enerji potansiyeli AÇISINDAN ELVERİŞLİDİR; bu yüzden ''hidroelektrik potansiyeli düşüktür'' ifadesi (D) yanlıştır ve sorunun cevabıdır. Kısa boylu olmaları (A), düzensiz rejime/debiye sahip olmaları (B) ve bu yüzden ulaşıma elverişli olmamaları (C) doğru genellemelerdir. Yağış rejimine bağlı olarak debilerinin mevsimden mevsime değişmesi (E) de doğrudur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1412e17d-c371-4a26-ba82-045308e93fc4', 'Genel olarak kısa boyludurlar', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1412e17d-c371-4a26-ba82-045308e93fc4', 'Debileri (su miktarları) düzensizdir', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1412e17d-c371-4a26-ba82-045308e93fc4', 'Eğimleri fazla olduğu için ulaşıma elverişli değildirler', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1412e17d-c371-4a26-ba82-045308e93fc4', 'Eğimleri fazla olduğu için hidroelektrik potansiyelleri düşüktür', true, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1412e17d-c371-4a26-ba82-045308e93fc4', 'Debileri yağış rejimine bağlı olarak mevsimden mevsime değişir', false, 4);

insert into topic_contents (topic_id, summary, content_md, example_question) values ('6b76a27b-b27e-4065-8325-d027f3f3377a', 'Türkiye''de nüfusun dağılışını etkileyen doğal (iklim, yer şekilleri, su kaynakları) ve beşerî (sanayi, ulaşım, tarım, turizm) etmenler; nüfus yoğunluğunun kıyı-iç kesim arasındaki dağılımı bu konunun omurgasıdır.', '## Nüfus Dağılışını Etkileyen Doğal Etmenler
İklim (ılıman/elverişli iklimlerde nüfus daha yoğun; Doğu Anadolu''nun sert kara iklimi nüfusu seyrekleştirir), yer şekilleri (dağlık-engebeli alanlarda nüfus seyrek, ova ve düzlüklerde yoğun), toprak verimliliği ve su kaynaklarına yakınlık nüfus dağılışını belirleyen temel doğal etmenlerdir.

## Nüfus Dağılışını Etkileyen Beşerî ve Ekonomik Etmenler
Sanayileşme (Marmara Bölgesi''nin nüfus yoğunluğunun en yüksek olmasının temel nedeni), ulaşım imkânları, tarımsal verimlilik (Çukurova, Ege gibi verimli ovalar), turizm potansiyeli (Akdeniz-Ege kıyıları) ve tarihsel-kültürel etmenler (yerleşim geleneği, göç hareketleri) nüfusun beşerî boyuttaki dağılış nedenleridir.

## Kıyı-İç Kesim Dengesizliği
Türkiye nüfusunun büyük bölümü kıyı kesimlerde (özellikle Marmara ve Ege) toplanmıştır; bunun nedeni hem iklimin elverişliliği hem de sanayi-ticaret-ulaşım imkânlarının kıyıda yoğunlaşmasıdır. İç ve Doğu Anadolu''nun bazı bölümleri, sert iklim ve dağlık yapı nedeniyle Türkiye''nin nüfus yoğunluğu en düşük alanları arasındadır.

## Kritik Hap Notlar
- Marmara Bölgesi''nin nüfus yoğunluğunun en fazla olmasının BAŞLICA nedeni SANAYİLEŞMEdir (doğal etmen değil, beşerî bir etmendir!) — sıkça sorulan bir ayrımdır.
- Doğu Anadolu''nun düşük nüfus yoğunluğu, öncelikle DOĞAL bir etmen olan sert kara iklimi ve engebeli yer şekilleriyle açıklanır.
- Nüfus yoğunluğu ile nüfus artış hızı FARKLI kavramlardır: yoğun nüfuslu bir yer, düşük artış hızına sahip olabilir (ör. büyükşehirlerde doğurganlık düşük olabilir) — bu ikisinin karıştırılmaması gerekir.
- Verimli ovalar (Çukurova, Ege ovaları) tarımsal etkinlik nedeniyle yoğun nüfusludur — bu bir beşerî-ekonomik etmen (tarım) sonucudur.
- Turizm potansiyeli yüksek kıyı ilçelerinde (Antalya, Muğla) mevsimsel nüfus artışları (nüfus hareketliliği) görülür — bu, kalıcı nüfus yoğunluğundan ayrı bir kavramdır.

## Video Ders Takip Rehberi
- [00:00 - 05:00] Nüfus dağılışını etkileyen doğal etmenler (iklim, yer şekilleri, su kaynakları).
- [05:00 - 12:00] Beşerî ve ekonomik etmenler (sanayi, tarım, turizm, ulaşım) ve Marmara Bölgesi örneği.
- [12:00 - 20:00] Kıyı-iç kesim nüfus dengesizliği örnek harita üzerinden pekiştirme.
- [20:00 - Bitiş] ÖSYM''nin çeldiricileri: doğal etmen-beşerî etmen karışıklığı, nüfus yoğunluğu ile nüfus artış hızının karıştırılması.', 'Marmara Bölgesi''nin Türkiye''nin en yoğun nüfuslu bölgesi olmasının temel nedeni aşağıdakilerden hangisidir?
A) İklim koşullarının çok elverişli olması B) Sanayileşme düzeyinin yüksek olması C) Yer şekillerinin çok düz olması D) Su kaynaklarının bol olması E) Toprak veriminin çok yüksek olması
Doğru Cevap: B — Marmara''nın yoğun nüfuslu olmasının başlıca nedeni sanayileşme (beşerî bir etmen) düzeyinin yüksek olmasıdır.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('42fcf944-91bf-4249-9251-60b13080fa4d', '6b76a27b-b27e-4065-8325-d027f3f3377a', 'kolay'::difficulty_level, 'Aşağıdakilerden hangisi Türkiye''de nüfus dağılışını etkileyen doğal etmenlerden biri değildir?', 'Doğal ve beşerî nüfus etmenlerini ayırt eder.', 'Sanayileşme düzeyi bir beşerî/ekonomik etmendir, doğal bir etmen değildir (C doğru ve sorunun cevabı). İklim (A), yer şekilleri (B), su kaynaklarına yakınlık (D) ve toprak verimliliği (E) ise doğrudan doğa kaynaklı, doğal etmenlerdir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('42fcf944-91bf-4249-9251-60b13080fa4d', 'İklim koşulları', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('42fcf944-91bf-4249-9251-60b13080fa4d', 'Yer şekillerinin engebeliliği', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('42fcf944-91bf-4249-9251-60b13080fa4d', 'Sanayileşme düzeyi', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('42fcf944-91bf-4249-9251-60b13080fa4d', 'Su kaynaklarına yakınlık', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('42fcf944-91bf-4249-9251-60b13080fa4d', 'Toprak verimliliği', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('9fc077b9-5ce4-48fe-a486-ab13d636ad06', '6b76a27b-b27e-4065-8325-d027f3f3377a', 'orta'::difficulty_level, 'Doğu Anadolu Bölgesi''nin Türkiye''nin en seyrek nüfuslu bölgelerinden biri olmasının en önemli nedeni aşağıdakilerden hangisidir?', 'Bölgesel nüfus yoğunluğu farklarını doğal etmenlerle ilişkilendirir.', 'Doğu Anadolu''nun sert kara iklimi ve yüksek/engebeli yer şekilleri (yüksek yaylalar, dağlık arazi), tarımsal ve yerleşim koşullarını zorlaştırarak nüfusun seyrek kalmasına neden olan başlıca doğal etmenlerdir (B doğru). Sanayileşme düzeyinin yüksek olması (A) tam tersine yoğun nüfusa yol açardı ve bölge için geçerli değildir. Ulaşım ağının gelişmişliği (C), turizm potansiyelinin yüksek olması (D) ve tarımsal verimin fazla olması (E) de bölgenin gerçek durumunu yansıtmaz; bunlar nüfusu ARTTIRAN etmenlerdir, bölgenin seyrekliğini açıklamaz.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9fc077b9-5ce4-48fe-a486-ab13d636ad06', 'Sanayileşme düzeyinin çok yüksek olması', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9fc077b9-5ce4-48fe-a486-ab13d636ad06', 'Sert kara ikliminin ve engebeli yer şekillerinin egemen olması', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9fc077b9-5ce4-48fe-a486-ab13d636ad06', 'Ulaşım ağının çok gelişmiş olması', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9fc077b9-5ce4-48fe-a486-ab13d636ad06', 'Turizm potansiyelinin çok yüksek olması', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9fc077b9-5ce4-48fe-a486-ab13d636ad06', 'Tarımsal verimliliğin çok fazla olması', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('afe0ef73-0a9f-492b-8e01-afe1c2d12ac4', '6b76a27b-b27e-4065-8325-d027f3f3377a', 'zor'::difficulty_level, 'Bir ilin nüfus yoğunluğunun yüksek, ancak yıllık nüfus artış hızının düşük (hatta negatif) olduğu belirlenmiştir. Bu durum aşağıdaki çıkarımlardan hangisiyle en iyi açıklanır?', 'Nüfus yoğunluğu ile nüfus artış hızı kavramlarını ayırt eder.', 'Nüfus yoğunluğu (birim alana düşen kişi sayısı) ile nüfus artış hızı (belirli bir dönemdeki nüfus değişim oranı) birbirinden tamamen farklı kavramlardır; kalabalık/yoğun nüfuslu büyük şehirlerde doğurganlık oranlarının düşük olması ve dışa göçün fazla olması, o ilin YOĞUN olmasına rağmen artış hızının düşük/negatif çıkmasına yol açabilir (C doğru). A ve B kavramları birbirinin yerine geçirilebilir gibi sunduğu için (aynı şey olduklarını iddia ettiği için) yanlıştır. D ve E, verilen bilgiyle çelişen veya konuyla ilgisiz iddialardır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('afe0ef73-0a9f-492b-8e01-afe1c2d12ac4', 'Nüfus yoğunluğu ile nüfus artış hızı aynı kavramdır, bu durum çelişkilidir', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('afe0ef73-0a9f-492b-8e01-afe1c2d12ac4', 'Bu durum yalnızca ölçüm hatasından kaynaklanır', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('afe0ef73-0a9f-492b-8e01-afe1c2d12ac4', 'Nüfus yoğunluğu ile nüfus artış hızı farklı kavramlardır; yoğun nüfuslu bir yerde doğurganlığın düşük olması bu duruma yol açabilir', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('afe0ef73-0a9f-492b-8e01-afe1c2d12ac4', 'Bu il mutlaka bir tarım bölgesidir', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('afe0ef73-0a9f-492b-8e01-afe1c2d12ac4', 'Bu durum yalnızca deniz kıyısında bulunan illerde görülebilir', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('b656ded9-92c4-4951-9656-409393c52eb1', '6b76a27b-b27e-4065-8325-d027f3f3377a', 'orta'::difficulty_level, 'Antalya ve Muğla gibi illerde yaz aylarında nüfusun geçici olarak önemli ölçüde artması aşağıdaki etmenlerden hangisiyle açıklanır?', 'Turizmin nüfus hareketliliği üzerindeki etkisini açıklar.', 'Antalya ve Muğla gibi illerde yaz aylarındaki geçici nüfus artışı, bu illerin yüksek turizm potansiyeline bağlı olarak yaz mevsiminde çok sayıda turist ve mevsimlik işçi çekmesiyle açıklanır (D doğru). Bu, kalıcı nüfus yoğunluğundan farklı, GEÇİCİ bir nüfus hareketliliğidir. Sanayileşme (A), tarımsal verim (B) ve madencilik (C) bu illerin yaz aylarındaki geçici nüfus artışının temel nedeni değildir; kış turizmi (E) de bu bölgeler için değil, dağlık/karlı bölgeler için geçerlidir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b656ded9-92c4-4951-9656-409393c52eb1', 'Sanayi tesislerinin yaz aylarında üretimi artırması', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b656ded9-92c4-4951-9656-409393c52eb1', 'Tarımsal üretimin yaz aylarında zirve yapması', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b656ded9-92c4-4951-9656-409393c52eb1', 'Madencilik faaliyetlerinin yaz aylarında hızlanması', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b656ded9-92c4-4951-9656-409393c52eb1', 'Yüksek turizm potansiyeli nedeniyle yaz aylarında yoğun turist ve mevsimlik işçi akını', true, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b656ded9-92c4-4951-9656-409393c52eb1', 'Kış turizminin yaz aylarında etkisini artırması', false, 4);

insert into topics (id, subject_id, name, slug, kazanim_text, weight, order_index) values ('307f95b7-0c09-47b4-b088-895dba797c11', 'e096912f-78c9-431d-8a7b-f5b3c005f472', 'Ekonomik Coğrafya (Tarım, Sanayi, Ulaşım)', 'ekonomik-cografya-tarim-sanayi-ulasim', 'Türkiye''nin tarım, sanayi, ulaşım ve ticaret faaliyetlerinin bölgesel dağılışını ve bu dağılışı etkileyen etmenleri açıklar.', 1.0, 7);
insert into topic_contents (topic_id, summary, content_md, example_question) values ('307f95b7-0c09-47b4-b088-895dba797c11', 'Türkiye''de tarımsal ürün deseninin iklime bağlı bölgesel farklılığı, sanayinin Marmara''da yoğunlaşma nedenleri ve ulaşım türlerinin (kara, demir, deniz, hava) yer şekilleriyle ilişkisi; KPSS bu üç alanı sıkça ürün-bölge ve sanayi-etken eşleştirmeleriyle sorar.', '## Tarım
Türkiye''de tarımsal ürün deseni büyük ölçüde İKLİME bağlıdır: turunçgil ve zeytin Akdeniz-Ege kıyılarında (Akdeniz iklimi ister), çay Doğu Karadeniz''de (bol ve düzenli yağış+asidik toprak ister), fındık Karadeniz kıyı şeridinde, tütün Ege ve Karadeniz''de, pamuk Çukurova-Ege-GAP''ta (yüksek sıcaklık toplamı ve sulama ister), buğday İç Anadolu''da (yarı kurak iklime dayanıklı) yetiştirilir. GAP (Güneydoğu Anadolu Projesi) bölgesinde sulamanın artmasıyla pamuk üretiminde büyük artış yaşanmıştır — bu, beşerî bir müdahalenin (sulama projesi) doğal sınırlamaları (kuraklık) aşabildiğinin klasik örneğidir.

## Sanayi
Türkiye''de sanayi en çok Marmara Bölgesi''nde (özellikle İstanbul-Kocaeli-Bursa hattı) yoğunlaşmıştır. Bunun nedenleri: büyük şehirlerde ucuz/nitelikli iş gücü ve geniş iç pazarın bulunması, limanlara ve ana ulaşım güzergâhlarına yakınlık (hammadde/ürün taşımacılığının kolaylığı), sermaye birikimi ve enerji/altyapı olanaklarının gelişmiş olmasıdır. Sanayinin bir bölgede yoğunlaşması ayrıca o bölgeye GÖÇ alarak nüfus yoğunluğunu da artırır (Nüfus ve Yerleşme konusuyla doğrudan bağlantılıdır).

## Ulaşım ve Ticaret
Türkiye''de kara yolu taşımacılığı (hem yolcu hem yük) en yaygın ulaşım türüdür; demir yolu, dağların kıyıya paralel uzanması ve arazinin engebeli olması nedeniyle yeterince gelişememiştir (yüksek maliyetli tünel/viyadük ihtiyacı). Deniz yolu ağır yük taşımacılığında (özellikle dış ticarette) önemlidir; boğazlar (İstanbul, Çanakkale) hem iç hem transit deniz taşımacılığında stratejik öneme sahiptir. Hava yolu, son yıllarda hem iç hem dış hat yolcu taşımacılığında hızla büyümüştür.

## Kritik Hap Notlar
- Çay = Doğu Karadeniz (bol/düzenli yağış + asidik toprak); Fındık = Karadeniz kıyı şeridi geneli; Turunçgil-Zeytin = Akdeniz-Ege kıyıları; Pamuk = Çukurova-Ege-GAP (sıcaklık toplamı + sulama); Buğday = İç Anadolu (yarı kurak iklime dayanıklı, geniş ova).
- GAP sonrası GÜNEYDOĞU ANADOLU''da pamuk üretiminin artması, SULAMANIN (beşerî bir müdahale) doğal kuraklık sınırını nasıl aşabildiğinin klasik örneğidir — sık sorulan bir çıkarımdır.
- Marmara''nın sanayi merkezi olmasının nedenleri: iş gücü + iç pazar + limanlara/ana yollara yakınlık + sermaye birikimi — TEK bir nedene indirgenmemelidir (çok faktörlü bir sonuçtur).
- Demir yolunun Türkiye''de yeterince gelişememesinin başlıca nedeni ARAZİNİN ENGEBELİ olması ve dağların kıyıya paralel uzanmasıdır (yüksek inşaat maliyeti).
- Sanayi yoğunlaşması → göç → nüfus yoğunluğu artışı zinciri, konular arası (Ekonomik Coğrafya–Nüfus) bir bağlantı kurar; ÖSYM bu tür çapraz bağlantılı sorulara sıcak bakar.

## Video Ders Takip Rehberi
- [00:00 - 05:00] Tarımsal ürün deseninin iklime bağlılığı — temel ürün-bölge eşleştirmeleri.
- [05:00 - 12:00] GAP örneği üzerinden sulamanın doğal sınırlamaları aşma etkisi; sanayinin Marmara''da yoğunlaşma nedenleri.
- [12:00 - 20:00] Ulaşım türlerinin (kara/demir/deniz/hava) yer şekilleriyle ilişkisi örnek üzerinden pekiştirme.
- [20:00 - Bitiş] ÖSYM''nin çeldiricileri: ürün-bölge eşleştirmelerinin karıştırılması (özellikle çay-fındık, pamuk-tütün), sanayi yoğunlaşmasının TEK bir nedene indirgenmesi.', 'GAP (Güneydoğu Anadolu Projesi) kapsamında yapılan sulama çalışmaları sonucunda Şanlıurfa ve Diyarbakır çevresinde hangi tarım ürününün üretiminde belirgin bir artış yaşanmıştır?
A) Çay B) Fındık C) Pamuk D) Zeytin E) Muz
Doğru Cevap: C — GAP''ın sulama imkânı sağlamasıyla bölgede pamuk üretimi büyük ölçüde artmıştır.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('a33cf980-1673-491e-8141-1c417a2b1493', '307f95b7-0c09-47b4-b088-895dba797c11', 'kolay'::difficulty_level, 'Aşağıdaki tarım ürünü - yetiştirildiği bölge eşleştirmelerinden hangisi doğrudur?', 'Tarımsal ürün deseninin bölgesel dağılışını bilir.', 'Çayın en yoğun üretildiği bölge, bol ve düzenli yağış ile asidik toprak yapısı nedeniyle Doğu Karadeniz''dir (B doğru). Turunçgil (A) Karadeniz''de değil Akdeniz-Ege kıyılarında yetişir. Zeytin (C) İç Anadolu''da değil yine Akdeniz-Ege''de yetişir. Buğday (D) Doğu Karadeniz''de değil İç Anadolu''da yaygındır. Pamuk (E) Doğu Anadolu''da değil Çukurova-Ege-GAP bölgelerinde yetiştirilir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a33cf980-1673-491e-8141-1c417a2b1493', 'Turunçgil – Doğu Karadeniz', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a33cf980-1673-491e-8141-1c417a2b1493', 'Çay – Doğu Karadeniz', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a33cf980-1673-491e-8141-1c417a2b1493', 'Zeytin – İç Anadolu', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a33cf980-1673-491e-8141-1c417a2b1493', 'Buğday – Doğu Karadeniz', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a33cf980-1673-491e-8141-1c417a2b1493', 'Pamuk – Doğu Anadolu', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('49b4f1d6-7ca8-4d5b-98d1-6891c1ff8512', '307f95b7-0c09-47b4-b088-895dba797c11', 'orta'::difficulty_level, 'GAP (Güneydoğu Anadolu Projesi) sonrasında Güneydoğu Anadolu''da pamuk üretiminin belirgin biçimde artması aşağıdaki çıkarımlardan hangisini en iyi destekler?', 'Beşerî müdahalelerin (sulama projeleri) doğal sınırlamalar üzerindeki etkisini yorumlar.', 'Bu durum, sulama gibi beşerî bir müdahalenin, bölgenin kurak iklim koşullarından kaynaklanan doğal bir tarımsal sınırlamayı büyük ölçüde aşabildiğini gösterir (C doğru). A yanlıştır çünkü tarımsal üretim iklimden tamamen bağımsız değildir, sulama iklimin OLUMSUZ etkisini azaltmıştır, iklimi anlamsız kılmamıştır. B, D ve E verilen bilgiyle desteklenmeyen, konuyla ilgisiz veya abartılı iddialardır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('49b4f1d6-7ca8-4d5b-98d1-6891c1ff8512', 'Tarımsal üretim tamamen iklimden bağımsız hale gelmiştir', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('49b4f1d6-7ca8-4d5b-98d1-6891c1ff8512', 'Bölgede artık hiçbir sulama ihtiyacı kalmamıştır', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('49b4f1d6-7ca8-4d5b-98d1-6891c1ff8512', 'Sulama gibi beşerî bir müdahale, kurak iklimin getirdiği doğal sınırlamayı büyük ölçüde aşabilmiştir', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('49b4f1d6-7ca8-4d5b-98d1-6891c1ff8512', 'Bölgede artık yalnızca pamuk tarımı yapılmaktadır', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('49b4f1d6-7ca8-4d5b-98d1-6891c1ff8512', 'Bu durum yalnızca Karadeniz Bölgesi için geçerlidir', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('afedcd0f-3c25-4ca8-9a85-edbcf1be8667', '307f95b7-0c09-47b4-b088-895dba797c11', 'zor'::difficulty_level, 'Marmara Bölgesi''nin Türkiye''nin en büyük sanayi merkezi olmasıyla ilgili aşağıdaki çıkarımlardan hangisi YAPILAMAZ?', 'Sanayi yoğunlaşmasının çok faktörlü nedenlerini ileri düzeyde değerlendirir.', 'Marmara''nın sanayi merkezi olması; nitelikli/ucuz iş gücü ve geniş iç pazarın varlığı (A doğru), limanlara ve ana ulaşım güzergâhlarına yakınlık (B doğru) ve sermaye birikiminin fazla olması (D doğru) gibi ÇOK FAKTÖRLÜ bir sonuçtur. C ifadesi ise YANLIŞTIR ve sorunun cevabıdır: sanayinin yoğunlaşması yalnızca ''iklimin çok elverişli olmasına'' bağlanamaz — iklim, sanayi yer seçiminde belirleyici bir faktör değildir; iş gücü, pazar, ulaşım ve sermaye çok daha belirleyicidir. E doğrudur, sanayi yoğunlaşması genellikle o bölgeye göçü ve nüfus artışını tetikler.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('afedcd0f-3c25-4ca8-9a85-edbcf1be8667', 'Bölgede nitelikli ve ucuz iş gücü ile geniş bir iç pazarın bulunması bu durumu açıklayan etmenlerden biridir', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('afedcd0f-3c25-4ca8-9a85-edbcf1be8667', 'Limanlara ve ana ulaşım güzergâhlarına yakın olması bu durumu açıklayan etmenlerden biridir', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('afedcd0f-3c25-4ca8-9a85-edbcf1be8667', 'Bu durum yalnızca ve tek başına bölgenin iklim koşullarının çok elverişli olmasıyla açıklanabilir', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('afedcd0f-3c25-4ca8-9a85-edbcf1be8667', 'Sermaye birikiminin fazla olması bu durumu açıklayan etmenlerden biridir', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('afedcd0f-3c25-4ca8-9a85-edbcf1be8667', 'Sanayinin yoğunlaşması bölgeye göçü tetikleyerek nüfus yoğunluğunu artırabilir', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('fdb1e87d-dffa-49d9-875c-0b4e408d4ba5', '307f95b7-0c09-47b4-b088-895dba797c11', 'orta'::difficulty_level, 'Türkiye''de demir yolu ulaşımının kara yoluna kıyasla yeterince gelişememesinin temel nedeni aşağıdakilerden hangisidir?', 'Ulaşım türlerinin gelişimini yer şekilleriyle ilişkilendirir.', 'Türkiye arazisinin engebeli olması ve dağların kıyıya paralel uzanması, demir yolu güzergâhlarında çok sayıda tünel ve viyadük gerektirerek maliyeti artırmış, bu da demir yolunun kara yoluna göre yeterince gelişememesine yol açmıştır (C doğru). Nüfusun az olması (A) ve sanayinin gelişmemiş olması (B) Türkiye geneli için gerçeği yansıtmaz. Petrol/doğal gaz kaynaklarının bolluğu (D) ulaşım türü tercihini değil enerji politikalarını ilgilendirir. İklimin çok elverişli olması (E) demir yolu gelişimini engelleyen bir etmen değildir, konuyla ters bir ilişki kurar.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('fdb1e87d-dffa-49d9-875c-0b4e408d4ba5', 'Türkiye''de nüfusun çok az olması', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('fdb1e87d-dffa-49d9-875c-0b4e408d4ba5', 'Sanayinin ülke genelinde hiç gelişmemiş olması', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('fdb1e87d-dffa-49d9-875c-0b4e408d4ba5', 'Arazinin engebeli olması ve dağların kıyıya paralel uzanmasının maliyeti artırması', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('fdb1e87d-dffa-49d9-875c-0b4e408d4ba5', 'Petrol ve doğal gaz kaynaklarının çok bol olması', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('fdb1e87d-dffa-49d9-875c-0b4e408d4ba5', 'İklimin demir yolu yapımı için çok elverişli olması', false, 4);

