-- KPSS Tarih: 4 mevcut konu için tam kapsamlı içerik (özet, ders notu, örnek soru)
-- ve her konu için 4'er soru + 5'er seçenek. Var olan 4 konu (İlk Türk Devletleri,
-- Osmanlı Kuruluş Dönemi, Kurtuluş Savaşı, İnkılap Tarihi) topic_contents UPSERT ile
-- zenginleştiriliyor; eksik olan konu (İlk Türk-İslam Devletleri) yeni topic olarak ekleniyor.

insert into topic_contents (topic_id, summary, content_md, example_question) values ('c876132a-c63c-4a00-bc2b-f40f32d682d6', 'Büyük Hun İmparatorluğu, Avrupa Hun Devleti, Göktürk Devleti ve Uygur Devleti İslamiyet öncesi Türk tarihinin temel devletleridir. Kut inancı, ikili (doğu-batı) teşkilat yapısı ve konargöçer yaşam tarzı bu devletlerin ortak özellikleridir; Uygurların yerleşik hayata geçip Mani dinini benimsemesi ise bu genel örüntünün istisnasıdır.', '## Büyük Hun İmparatorluğu
Bilinen ilk teşkilatlı Türk devletidir. Mete Han döneminde (MÖ 209) onlu (ondalık) askeri-idari teşkilat kurulmuş, Çin ile mücadele edilmiştir. Hunlar, Çinlilerin kuzeyden gelen akınları durdurmak için Çin Seddi''ni inşa etmesine neden olmuştur.

## Avrupa Hun Devleti
Kavimler Göçü (375) sonucunda Orta Asya''dan batıya göç eden Hunlar tarafından kurulmuştur. En güçlü dönemini Attila zamanında yaşamış, Bizans ve Roma üzerinde baskı kurmuştur. Kavimler Göçü, Roma İmparatorluğu''nun 395''te ikiye ayrılmasına ve Avrupa''da feodalitenin (derebeylik) doğmasına zemin hazırlamıştır.

## Göktürk Devleti
Türk adını taşıyan ilk devlettir (552, Bumin Kağan). Orhun Anıtları (Bilge Kağan, Kültigin, Vezir Tonyukuk adına dikilen), Türk tarihinin ilk yazılı belgeleridir ve Türk adının geçtiği ilk metinlerdir. Bilge Kağan döneminde devlet ikinci kez toparlanmış (Kutluk/II. Göktürk Devleti), ancak devlet ikiye (Doğu-Batı) ayrılmıştır.

## Uygur Devleti
Göktürklerden sonra kurulan Uygurlar, Türk tarihinde İLK KEZ yerleşik hayata geçen ve İLK KEZ bir dini (Maniheizm) benimseyen Türk devletidir; bu iki özellik onları savaşçı-konargöçer Türk devlet geleneğinden ayırır. Mani dini etkisiyle et yemekten ve savaşmaktan uzaklaşmışlardır ki bu da devletin askeri gücünün zayıflamasına yol açmıştır.

## Ortak Türk Devlet Teşkilatı
Türklerde hükümdara "kut" (Tanrı tarafından verilmiş yönetme yetkisi) inancı hâkimdi; bu inanç, taht kavgalarına (kut''un hanedanın tüm erkek üyelerinde olduğu düşünüldüğü için) da zemin hazırlamıştır. İkili teşkilat (doğu-batı, sağ-sol kanat) yönetim biçimi çoğu Türk devletinde görülür. Kurultay (Toy), devlet işlerinin görüşüldüğü danışma meclisidir.

## Kritik Hap Notlar
- Mete Han (Büyük Hun) onlu teşkilatın kurucusudur; bu askeri düzen sonraki tüm Türk devletlerine örnek olmuştur.
- Kavimler Göçü''nün nedeni Avrupa Hunlarının (Batı Hun) batıya ilerlemesidir; SONUCU ise Roma''nın ikiye bölünmesi ve Avrupa''da feodalitenin başlamasıdır.
- Orhun Anıtları, Türk adının geçtiği İLK yazılı Türkçe kaynaktır (Göktürkler dönemi, Bilge Kağan-Kültigin-Tonyukuk adına).
- Uygurlar, Türk tarihinde YERLEŞİK HAYATA GEÇEN VE DİNİNİ DEĞİŞTİREN (Maniheizm) ilk Türk devletidir — bu iki özellik ÖSYM''nin en sık sorduğu Uygur ayırt edicisidir.
- "Kut" inancı, Türklerde hükümdarlık yetkisinin Tanrı tarafından verildiği inancıdır; ülkenin hanedan üyeleri arasında paylaşılabilir görülmesi taht kavgalarının (ve devletlerin kısa sürede parçalanmasının) en önemli nedenidir.

## Video Ders Takip Rehberi
- [00:00 - 05:00] Büyük Hun İmparatorluğu ve Mete Han''ın onlu teşkilatı.
- [05:00 - 12:00] Avrupa Hun Devleti, Attila ve Kavimler Göçü''nün Avrupa''ya etkileri.
- [12:00 - 20:00] Göktürk Devleti, Orhun Anıtları ve devletin ikiye ayrılma süreci.
- [20:00 - Bitiş] Uygur Devleti''nin yerleşik hayata geçişi, Maniheizm''in benimsenmesi ve kut inancı/ikili teşkilat gibi ortak Türk devlet gelenekleri.', 'Aşağıdaki Türk devletlerinden hangisi yerleşik hayata geçmiş ve bir dini (Maniheizm) benimsemiş olmasıyla diğerlerinden ayrılır?
A) Büyük Hun İmparatorluğu B) Avrupa Hun Devleti C) Göktürk Devleti D) Uygur Devleti E) Kutluk Devleti
Doğru Cevap: D — Uygurlar, Türk tarihinde yerleşik hayata geçen ve Maniheizm dinini benimseyen ilk Türk devletidir.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('0239fcbc-0ae6-40b8-9f3c-47ad7d0cd8c3', 'c876132a-c63c-4a00-bc2b-f40f32d682d6', 'kolay'::difficulty_level, 'Onlu (ondalık) askeri-idari teşkilatı kurarak sonraki Türk devletlerine örnek olan hükümdar aşağıdakilerden hangisidir?', 'Büyük Hun İmparatorluğu''nun teşkilat yapısını bilir.', 'Mete Han, MÖ 209''da Büyük Hun İmparatorluğu''nda onlu askeri-idari teşkilatı kurmuş ve bu düzen kendisinden sonraki tüm Türk devletlerine örnek olmuştur (C doğru). Bilge Kağan (A) ve Kültigin (B) Göktürk dönemi hükümdarlarındandır. Attila (D) Avrupa Hun Devleti hükümdarıdır. Bumin Kağan (E) Göktürk Devleti''nin kurucusudur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0239fcbc-0ae6-40b8-9f3c-47ad7d0cd8c3', 'Bilge Kağan', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0239fcbc-0ae6-40b8-9f3c-47ad7d0cd8c3', 'Kültigin', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0239fcbc-0ae6-40b8-9f3c-47ad7d0cd8c3', 'Mete Han', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0239fcbc-0ae6-40b8-9f3c-47ad7d0cd8c3', 'Attila', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0239fcbc-0ae6-40b8-9f3c-47ad7d0cd8c3', 'Bumin Kağan', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('088b308c-9a94-4cf5-a5b5-cb5cf7b2e96a', 'c876132a-c63c-4a00-bc2b-f40f32d682d6', 'orta'::difficulty_level, 'Türk adının geçtiği ilk yazılı Türkçe kaynak aşağıdakilerden hangisidir?', 'Orhun Anıtları''nın önemini bilir.', 'Orhun Anıtları (Bilge Kağan, Kültigin ve Vezir Tonyukuk adına dikilen), Türk adının geçtiği ilk yazılı Türkçe belgelerdir (B doğru). Kutadgu Bilig (A) Karahanlı dönemine ait bir siyasetname eseridir. Divan-ı Lügati''t Türk (C) ve Divan-ı Hikmet (D) de İslamiyet sonrası dönem eserleridir. Uygur alfabesiyle yazılmış metinler (E) Orhun Anıtları''ndan sonra ortaya çıkmıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('088b308c-9a94-4cf5-a5b5-cb5cf7b2e96a', 'Kutadgu Bilig', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('088b308c-9a94-4cf5-a5b5-cb5cf7b2e96a', 'Orhun Anıtları', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('088b308c-9a94-4cf5-a5b5-cb5cf7b2e96a', 'Divan-ı Lügati''t Türk', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('088b308c-9a94-4cf5-a5b5-cb5cf7b2e96a', 'Divan-ı Hikmet', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('088b308c-9a94-4cf5-a5b5-cb5cf7b2e96a', 'Uygur dönemi metinleri', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('92fdd507-514d-4618-83b9-0e4e9a81fa10', 'c876132a-c63c-4a00-bc2b-f40f32d682d6', 'orta'::difficulty_level, 'Kavimler Göçü''nün (375) sonuçlarıyla ilgili aşağıdaki bilgilerden hangisi doğrudur?', 'Kavimler Göçü''nün Avrupa tarihine etkisini bilir.', 'Kavimler Göçü, Avrupa''da köklü değişikliklere yol açmış; Roma İmparatorluğu 395''te Doğu ve Batı olmak üzere ikiye ayrılmış, göç sonucu oluşan karışıklık ortamı Avrupa''da feodalitenin (derebeylik rejiminin) doğmasına zemin hazırlamıştır (C doğru). A yanlıştır, göçü BAŞLATAN Avrupa Hunlarıdır, Çin değildir. B yanlıştır, İslamiyet bu tarihte henüz doğmamıştı (610''da doğdu). D yanlıştır, göç Roma''yı güçlendirmemiş, aksine yıkılış sürecini hızlandırmıştır. E yanlıştır, Kavimler Göçü''nü Türkler (Hunlar) başlatmıştır, Germen kavimleri göçe bu baskı sonucunda katılmıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('92fdd507-514d-4618-83b9-0e4e9a81fa10', 'Çin, kuzeyden gelen bu göçü başlatmıştır.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('92fdd507-514d-4618-83b9-0e4e9a81fa10', 'İslamiyet bu göç sırasında Arabistan''da doğmuştur.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('92fdd507-514d-4618-83b9-0e4e9a81fa10', 'Roma İmparatorluğu ikiye ayrılmış ve Avrupa''da feodalite doğmuştur.', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('92fdd507-514d-4618-83b9-0e4e9a81fa10', 'Bu göç, Roma İmparatorluğu''nu güçlendirmiştir.', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('92fdd507-514d-4618-83b9-0e4e9a81fa10', 'Göçü başlatan kavim Germenlerdir.', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('b20f3b98-7728-4f63-9f63-70a305f1edf6', 'c876132a-c63c-4a00-bc2b-f40f32d682d6', 'zor'::difficulty_level, 'Türk devletlerinde görülen ''kut'' inancıyla ilgili aşağıdaki yargılardan hangisi doğrudur?', 'Kut inancının siyasi sonuçlarını değerlendirir.', 'Kut inancına göre yönetme yetkisi Gök Tanrı tarafından hükümdara ve hanedanın tüm erkek üyelerine verilmiş kabul edildiğinden, bu durum taht kavgalarına ve devletlerin kısa sürede parçalanmasına zemin hazırlamıştır (B doğru). A yanlıştır, kut yalnızca hükümdara değil hanedan üyelerine de verilmiş sayılırdı, bu da sorunun kaynağıydı. C yanlıştır, kut dini değil siyasi-yönetsel bir meşruiyet kaynağıdır. D yanlıştır, kut inancı devlet birliğini SAĞLAMLAŞTIRMAMIŞ, tam tersine parçalanmaya yol açmıştır. E yanlıştır, bu inanç yalnızca bir devlete özgü değil, ortak Türk devlet geleneğinin bir parçasıdır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b20f3b98-7728-4f63-9f63-70a305f1edf6', 'Kut, yalnızca hükümdarın kendisine verilmiş, hanedanın diğer üyelerini kapsamazdı.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b20f3b98-7728-4f63-9f63-70a305f1edf6', 'Kut inancı, hanedan üyeleri arasında taht kavgalarına ve devletlerin parçalanmasına zemin hazırlamıştır.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b20f3b98-7728-4f63-9f63-70a305f1edf6', 'Kut, dinî bir kavram olup siyasi bir sonuç doğurmamıştır.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b20f3b98-7728-4f63-9f63-70a305f1edf6', 'Kut inancı, Türk devletlerinde birliği güçlendirmiş ve iç kargaşayı önlemiştir.', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b20f3b98-7728-4f63-9f63-70a305f1edf6', 'Kut inancı yalnızca Uygur Devleti''ne özgüdür.', false, 4);

insert into topic_contents (topic_id, summary, content_md, example_question) values ('145d44b3-a8e7-430f-8778-71fb8929a97d', 'Osman Bey''in beyliği devlete dönüştürmesinden başlayarak Orhan Bey''in kurumsallaşma adımları (ilk düzenli ordu, ilk medrese), I. Murad döneminde merkezi teşkilatın (yeniçeri ocağı, kapıkulu) oluşması, Yıldırım Bayezıd döneminde Ankara Savaşı ve Fetret Devri, son olarak Çelebi Mehmed ve II. Murad döneminde devletin yeniden toparlanması bu konunun kronolojik omurgasını oluşturur.', '## Osman Bey Dönemi (Beylikten Devlete Geçiş)
1299''da Osman Bey''in bağımsızlığını ilan etmesiyle Osmanlı Beyliği kurulmuştur. Bizans tekfurlarıyla mücadele edilmiş, Karacahisar ve Yenişehir gibi yerler fethedilmiştir.

## Orhan Bey Dönemi (Kurumsallaşmanın Başlangıcı)
Orhan Bey, Bursa''yı fethederek (1326) başkent yapmıştır. İLK düzenli Osmanlı ordusu (Yaya ve Müsellem birlikleri) bu dönemde kurulmuştur. İLK Osmanlı medresesi İznik''te açılmıştır. Rumeli''ye geçiş de bu dönemde (Çimpe Kalesi, 1352) başlamıştır.

## I. Murad (Hüdavendigâr) Dönemi
Merkezi devlet teşkilatının temelleri bu dönemde atılmıştır: Kapıkulu Ocakları ve Yeniçeri Ocağı kurulmuş (Pençik/Devşirme sistemiyle), Divan-ı Hümayun düzenli hâle getirilmiş, Çandarlı Kara Halil''in önerisiyle ilk kez kadıaskerlik ve beylerbeyilik makamları oluşturulmuştur. I. Kosova Savaşı (1389) ile Balkanlarda Osmanlı hâkimiyeti pekişmiştir.

## Yıldırım Bayezıd ve Ankara Savaşı (1402)
Yıldırım Bayezıd, Anadolu Türk birliğini sağlamak amacıyla Anadolu beyliklerini Osmanlı topraklarına katmıştır; bu politika Timur ile karşı karşıya gelmesine neden olmuştur. 1402 Ankara Savaşı''nda Osmanlı ordusu Timur''a yenilmiş, Bayezıd esir düşmüş ve devlet Fetret Devri''ne (1402-1413) girmiştir; bu dönemde şehzadeler arasında taht kavgaları yaşanmıştır.

## Çelebi Mehmed ve II. Murad Dönemi
Çelebi Mehmed, Fetret Devri''ni sona erdirerek (1413) devlet birliğini yeniden sağlamıştır; bu nedenle kendisine "Osmanlı Devleti''nin ikinci kurucusu" denir. II. Murad döneminde Varna (1444) ve II. Kosova (1448) savaşları kazanılarak Osmanlı''nın Balkanlardaki üstünlüğü kesinleşmiştir.

## Kritik Hap Notlar
- İLK düzenli Osmanlı ordusu (Yaya-Müsellem) ve İLK Osmanlı medresesi (İznik) ORHAN BEY dönemine aittir; bu iki "ilk" ÖSYM''nin en sık sorduğu Orhan Bey ayırt edicisidir.
- Kapıkulu Ocakları ve Yeniçeri Ocağı I. MURAD döneminde kurulmuştur; devşirme sistemiyle beslenen bu ocaklar merkezi otoritenin güçlenmesini sağlamıştır.
- Ankara Savaşı''nın (1402) temel nedeni Yıldırım Bayezıd''ın Anadolu Türk birliğini sağlama politikasıdır; bu, Timur ile Anadolu beylikleri üzerindeki nüfuz mücadelesine dönüşmüştür.
- Fetret Devri (1402-1413), Osmanlı tarihinde şehzadeler arası taht kavgalarının yaşandığı, devletin parçalanma tehlikesi geçirdiği dönemdir; bu döneme Çelebi Mehmed son vermiştir.
- Varna (1444) ve II. Kosova (1448) savaşları II. Murad döneminde kazanılmış, Osmanlı''nın Balkanlardaki kalıcı üstünlüğünü pekiştirmiştir.

## Video Ders Takip Rehberi
- [00:00 - 05:00] Osman Bey döneminde beylikten devlete geçiş süreci.
- [05:00 - 12:00] Orhan Bey döneminde kurumsallaşma: ilk düzenli ordu, ilk medrese, Rumeli''ye geçiş.
- [12:00 - 20:00] I. Murad döneminde merkezi teşkilat (Kapıkulu-Yeniçeri) ve Yıldırım Bayezıd döneminde Ankara Savaşı-Fetret Devri.
- [20:00 - Bitiş] Çelebi Mehmed''in devleti toparlaması ve II. Murad döneminde Balkanlarda kesin üstünlük.', 'Osmanlı Devleti''nde ilk düzenli ordunun (Yaya ve Müsellem birlikleri) kurulduğu dönem aşağıdakilerden hangisidir?
A) Osman Bey B) Orhan Bey C) I. Murad D) Yıldırım Bayezıd E) II. Murad
Doğru Cevap: B — İlk düzenli Osmanlı ordusu, Orhan Bey döneminde Yaya ve Müsellem birlikleri olarak kurulmuştur.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('27372e6f-3385-4e4f-bf19-21cde1072b70', '145d44b3-a8e7-430f-8778-71fb8929a97d', 'kolay'::difficulty_level, 'Osmanlı Beyliği''nin bağımsızlığını ilan ederek devletin kurucusu kabul edilen hükümdar aşağıdakilerden hangisidir?', 'Osmanlı Devleti''nin kuruluşunu bilir.', 'Osman Bey, 1299''da bağımsızlığını ilan ederek Osmanlı Beyliği''ni kurmuştur (A doğru). Orhan Bey (B) Osman Bey''in oğludur ve kurumsallaşmayı başlatmıştır. I. Murad (C), Yıldırım Bayezıd (D) ve Çelebi Mehmed (E) kuruluştan sonraki dönemlerde tahta çıkmış hükümdarlardır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('27372e6f-3385-4e4f-bf19-21cde1072b70', 'Osman Bey', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('27372e6f-3385-4e4f-bf19-21cde1072b70', 'Orhan Bey', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('27372e6f-3385-4e4f-bf19-21cde1072b70', 'I. Murad', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('27372e6f-3385-4e4f-bf19-21cde1072b70', 'Yıldırım Bayezıd', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('27372e6f-3385-4e4f-bf19-21cde1072b70', 'Çelebi Mehmed', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('08f7ec6f-6618-4d63-a049-b9d8f39bf6c7', '145d44b3-a8e7-430f-8778-71fb8929a97d', 'orta'::difficulty_level, 'Kapıkulu Ocakları ve Yeniçeri Ocağı''nın kurulduğu dönem aşağıdakilerden hangisidir?', 'Merkezi teşkilatın oluşum dönemini bilir.', 'Kapıkulu Ocakları ve Yeniçeri Ocağı, devşirme (pençik) sistemiyle asker temin edilmesi yoluyla I. MURAD (Hüdavendigâr) döneminde kurulmuştur (C doğru). Osman Bey (A) ve Orhan Bey (B) döneminde henüz bu kurumlar oluşmamıştı; Orhan Bey döneminde sadece Yaya-Müsellem birlikleri vardı. Yıldırım Bayezıd (D) ve Çelebi Mehmed (E) bu kurumların kurulmasından sonraki dönemlerdir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('08f7ec6f-6618-4d63-a049-b9d8f39bf6c7', 'Osman Bey', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('08f7ec6f-6618-4d63-a049-b9d8f39bf6c7', 'Orhan Bey', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('08f7ec6f-6618-4d63-a049-b9d8f39bf6c7', 'I. Murad', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('08f7ec6f-6618-4d63-a049-b9d8f39bf6c7', 'Yıldırım Bayezıd', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('08f7ec6f-6618-4d63-a049-b9d8f39bf6c7', 'Çelebi Mehmed', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('f2bd33f3-4955-42b4-8a3b-8bbd2ef847f8', '145d44b3-a8e7-430f-8778-71fb8929a97d', 'orta'::difficulty_level, '1402 Ankara Savaşı''nın temel nedeni aşağıdakilerden hangisidir?', 'Ankara Savaşı''nın nedenini bilir.', 'Yıldırım Bayezıd''ın Anadolu Türk siyasi birliğini sağlamak amacıyla Anadolu beyliklerini Osmanlı topraklarına katma politikası, bu beyliklere sığınan beylerin Timur''dan yardım istemesiyle Timur ile Osmanlı''yı karşı karşıya getirmiştir (B doğru). A yanlıştır, savaşın nedeni bir Balkan meselesi değildir. C yanlıştır, Fetret Devri savaşın NEDENİ değil SONUCUDUR. D yanlıştır, bu dönemde henüz İstanbul kuşatılmamıştı bu amaçla. E yanlıştır, savaşın doğrudan nedeni dinî değil siyasi-topraksal bir çekişmedir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f2bd33f3-4955-42b4-8a3b-8bbd2ef847f8', 'Osmanlı''nın Balkanlardaki topraklarını genişletme isteği', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f2bd33f3-4955-42b4-8a3b-8bbd2ef847f8', 'Yıldırım Bayezıd''ın Anadolu Türk birliğini sağlama politikasının Timur ile çıkar çatışmasına yol açması', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f2bd33f3-4955-42b4-8a3b-8bbd2ef847f8', 'Fetret Devri''nin başlamış olması', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f2bd33f3-4955-42b4-8a3b-8bbd2ef847f8', 'İstanbul''un fethedilmek istenmesi', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f2bd33f3-4955-42b4-8a3b-8bbd2ef847f8', 'Dini bir anlaşmazlığın ortaya çıkması', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('f0b9bf6b-fa68-4291-820b-8d8d2ca9adda', '145d44b3-a8e7-430f-8778-71fb8929a97d', 'zor'::difficulty_level, 'Fetret Devri (1402-1413) ile ilgili aşağıdaki bilgilerden hangisi doğrudur?', 'Fetret Devri''nin nedenini ve sonucunu değerlendirir.', 'Fetret Devri, Ankara Savaşı''nda Yıldırım Bayezıd''ın esir düşmesi SONUCUNDA ortaya çıkmış, şehzadeler arası taht kavgalarıyla geçen bir dönemdir ve Çelebi Mehmed''in 1413''te tahtı ele geçirmesiyle sona ermiştir (D doğru). A yanlıştır, bu dönem Osmanlı''nın GÜÇLENDİĞİ değil ZAYIFLADIĞI bir dönemdir. B yanlıştır, Fetret Devri''ni II. Murad değil Çelebi Mehmed sona erdirmiştir. C yanlıştır, bu dönemde toprak kaybı yaşanmış, kazanım değil kayıp söz konusudur. E yanlıştır, Fetret Devri Ankara Savaşı''nın NEDENİ değil SONUCUDUR.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f0b9bf6b-fa68-4291-820b-8d8d2ca9adda', 'Bu dönemde Osmanlı Devleti büyük ölçüde güçlenmiştir.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f0b9bf6b-fa68-4291-820b-8d8d2ca9adda', 'Bu döneme II. Murad son vermiştir.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f0b9bf6b-fa68-4291-820b-8d8d2ca9adda', 'Bu dönemde önemli toprak kazanımları elde edilmiştir.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f0b9bf6b-fa68-4291-820b-8d8d2ca9adda', 'Bu dönem, Ankara Savaşı''nın sonucunda ortaya çıkmış ve Çelebi Mehmed tarafından sona erdirilmiştir.', true, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('f0b9bf6b-fa68-4291-820b-8d8d2ca9adda', 'Fetret Devri, Ankara Savaşı''nın çıkmasına neden olmuştur.', false, 4);

insert into topic_contents (topic_id, summary, content_md, example_question) values ('091291bb-a136-48e2-94b1-8d12631be6ad', 'Mondros Ateşkes Antlaşması sonrası başlayan işgaller, Kuvâ-yi Milliye direnişi, Amasya Genelgesi ile başlayan milli mücadele süreci, Erzurum-Sivas Kongreleri, TBMM''nin açılışı, Doğu-Güney-Batı cephelerindeki savaşlar (İnönü, Sakarya, Büyük Taarruz) ve Lozan Antlaşması ile sonuçlanan süreç bu konunun kronolojik omurgasını oluşturur.', '## Mondros Ateşkes Antlaşması (30 Ekim 1918) ve İşgaller
I. Dünya Savaşı''nda Osmanlı Devleti''nin yenilgisi sonucu imzalanan Mondros, itilaf devletlerine "güvenliklerini tehdit eden" herhangi bir yeri işgal etme hakkı tanıyan (7. madde) ağır şartlar içerir. Bu maddeye dayanarak İtilaf Devletleri ve Yunanistan çeşitli Anadolu topraklarını (İzmir, Antep, Maraş, Urfa, Adana vb.) işgal etmiştir. İzmir''in işgali (15 Mayıs 1919) Kuvâ-yi Milliye direnişini hızlandıran en önemli olaylardan biridir.

## Kuvâ-yi Milliye ve Amasya Genelgesi (22 Haziran 1919)
Kuvâ-yi Milliye, düzenli ordudan önce işgallere karşı direnen yerel milis kuvvetleridir. Mustafa Kemal, 19 Mayıs 1919''da Samsun''a çıkarak Kurtuluş Savaşı''nı fiilen başlatmıştır. Amasya Genelgesi''nde "Milletin bağımsızlığını yine milletin azim ve kararı kurtaracaktır" ifadesiyle millî egemenlik ilkesi ilk kez resmi bir belgede vurgulanmış; bu genelge Kurtuluş Savaşı''nın "gerekçesi ve yöntemi" niteliğindedir.

## Erzurum ve Sivas Kongreleri (1919)
Erzurum Kongresi (bölgesel nitelikte) ile Sivas Kongresi''nde (millî nitelikte) alınan kararlarla "manda ve himaye kabul edilemez" ilkesi benimsenmiş, Temsil Heyeti kurulmuş ve millî mücadelenin tek merkezden yönetilmesi kararlaştırılmıştır. Misak-ı Millî (Son Osmanlı Mebusan Meclisi''nde, 1920) bu kongrelerdeki kararların devamı niteliğinde ulusal sınırları belirlemiştir.

## TBMM''nin Açılması (23 Nisan 1920)
İstanbul''un işgali (16 Mart 1920) ve Mebusan Meclisi''nin kapatılması üzerine Ankara''da TBMM açılmıştır. TBMM, hem yasama hem yürütme yetkisini elinde bulunduran "güçler birliği" ilkesine dayanan olağanüstü bir meclistir.

## Cepheler ve Savaşlar
Doğu Cephesi''nde Ermenilerle (Gümrü Antlaşması, 1920), Güney Cephesi''nde Fransızlarla (Ankara Antlaşması, 1921) mücadele edilmiştir. Batı Cephesi''nde Yunanlara karşı I. İnönü (1921, TBMM''nin ilk askeri ve siyasi başarısı, bu zaferle TBMM İtilaf Devletlerince ilk kez -Londra Konferansı''na davetle- tanınmıştır), II. İnönü, Sakarya Meydan Muharebesi (1921, Mustafa Kemal''e Başkomutanlık ve Mareşallik unvanı verilmiştir) ve Büyük Taarruz-Başkomutanlık Meydan Muharebesi (Ağustos 1922, "Ordular! İlk hedefiniz Akdeniz''dir, ileri!") kazanılmıştır.

## Mudanya Ateşkesi (1922) ve Lozan Antlaşması (24 Temmuz 1923)
Mudanya Ateşkes Antlaşması ile savaş fiilen sona ermiş, Lozan Antlaşması ile de Türkiye''nin bağımsızlığı ULUSLARARASI alanda hukuken tanınmıştır. Lozan''da kapitülasyonlar tamamen kaldırılmış; ancak Musul sorunu ve boğazlar meselesi (Boğazlar Komisyonu) tam çözülemeyip ileriki yıllara (Musul 1926 Ankara Antlaşması, Boğazlar 1936 Montrö Sözleşmesi) bırakılmıştır.

## Kritik Hap Notlar
- Mondros''un 7. maddesi, İtilaf Devletlerine "güvenliği tehdit eden yerleri işgal etme" hakkı tanıyarak işgallere HUKUKİ ZEMİN oluşturmuştur; bu madde ÖSYM''de en sık vurgulanan Mondros ayırt edicisidir.
- Amasya Genelgesi, Kurtuluş Savaşı''nın GEREKÇESİNİ ve YÖNTEMİNİ belirleyen belgedir; bu nedenle "ihtilalin ilk belgesi/fikir hazırlığı" olarak nitelendirilir; Erzurum ve Sivas kongreleri ise bu kararların uygulama ve teşkilatlanma aşamasıdır.
- TBMM''nin İtilaf Devletlerince ilk kez tanınması I. İNÖNÜ ZAFERİ sonrasında, Londra Konferansı''na davet edilmesiyle olmuştur — bu, savaş alanındaki başarının diplomatik sonuç doğurduğu klasik bir örnektir.
- Mustafa Kemal''e Başkomutanlık ve Mareşallik unvanı SAKARYA MEYDAN MUHAREBESİ sonrasında TBMM tarafından verilmiştir; Büyük Taarruz ile karıştırılmamalıdır.
- Lozan Antlaşması''nda TAM çözülemeyen iki sorun Musul (1926''da Ankara Antlaşması ile Irak sınırları içinde kalmıştır) ve Boğazlar (1936 Montrö Sözleşmesi''ne kadar tam egemenlik sağlanamamıştır) meseleleridir.

## Video Ders Takip Rehberi
- [00:00 - 05:00] Mondros Ateşkesi, 7. madde ve işgallerin başlaması.
- [05:00 - 12:00] Kuvâ-yi Milliye, Amasya Genelgesi, Erzurum-Sivas Kongreleri ve Misak-ı Millî.
- [12:00 - 20:00] TBMM''nin açılışı ve cephelerdeki mücadele: İnönü, Sakarya, Büyük Taarruz.
- [20:00 - Bitiş] Mudanya Ateşkesi, Lozan Antlaşması ve çözülemeyen Musul-Boğazlar sorunları.', 'TBMM''nin İtilaf Devletlerince ilk kez tanınmasına (Londra Konferansı''na davet edilmesine) yol açan gelişme aşağıdakilerden hangisidir?
A) Sakarya Meydan Muharebesi B) I. İnönü Muharebesi C) Büyük Taarruz D) Mudanya Ateşkesi E) Gümrü Antlaşması
Doğru Cevap: B — TBMM, I. İnönü Muharebesi''ndeki başarısının ardından İtilaf Devletlerince ilk kez Londra Konferansı''na davet edilerek fiilen tanınmıştır.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('eeabb9b7-fb10-4438-9930-949924ca5157', '091291bb-a136-48e2-94b1-8d12631be6ad', 'kolay'::difficulty_level, 'Osmanlı Devleti''nin I. Dünya Savaşı''ndan çekilmesini sağlayan ve İtilaf Devletlerine geniş işgal yetkisi tanıyan antlaşma aşağıdakilerden hangisidir?', 'Mondros Ateşkes Antlaşması''nı bilir.', 'Mondros Ateşkes Antlaşması (30 Ekim 1918), Osmanlı Devleti''ni I. Dünya Savaşı''ndan çıkarmış ve 7. maddesiyle İtilaf Devletlerine güvenliklerini tehdit eden yerleri işgal etme hakkı tanımıştır (C doğru). Sevr (A) bir barış antlaşması taslağıdır ve Mondros''tan sonra hazırlanmıştır. Lozan (B) ve Mudanya (D) Kurtuluş Savaşı''nı sona erdiren belgelerdir. Gümrü (E) Doğu Cephesi''nde Ermenilerle imzalanan bir antlaşmadır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('eeabb9b7-fb10-4438-9930-949924ca5157', 'Sevr Antlaşması', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('eeabb9b7-fb10-4438-9930-949924ca5157', 'Lozan Antlaşması', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('eeabb9b7-fb10-4438-9930-949924ca5157', 'Mondros Ateşkes Antlaşması', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('eeabb9b7-fb10-4438-9930-949924ca5157', 'Mudanya Ateşkes Antlaşması', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('eeabb9b7-fb10-4438-9930-949924ca5157', 'Gümrü Antlaşması', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('c775b81a-be61-4770-a958-4086ab62c264', '091291bb-a136-48e2-94b1-8d12631be6ad', 'orta'::difficulty_level, 'Kurtuluş Savaşı''nın gerekçesini ve yöntemini belirleyen, ''Milletin bağımsızlığını yine milletin azim ve kararı kurtaracaktır'' ifadesinin yer aldığı belge aşağıdakilerden hangisidir?', 'Amasya Genelgesi''nin önemini bilir.', 'Bu ifade Amasya Genelgesi''nde (22 Haziran 1919) yer alır ve millî egemenlik ilkesinin ilk resmi vurgulandığı belge olması nedeniyle Kurtuluş Savaşı''nın gerekçesi ve yöntemini belirleyen temel metin kabul edilir (B doğru). Erzurum Kongresi (A) bölgesel, Sivas Kongresi (C) millî nitelikli kongrelerdir ve Amasya Genelgesi''nden sonra yapılmıştır. Misak-ı Millî (D) sınırları belirleyen bir karardır. Amasya Görüşmeleri (E) farklı bir aşamadır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c775b81a-be61-4770-a958-4086ab62c264', 'Erzurum Kongresi kararları', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c775b81a-be61-4770-a958-4086ab62c264', 'Amasya Genelgesi', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c775b81a-be61-4770-a958-4086ab62c264', 'Sivas Kongresi kararları', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c775b81a-be61-4770-a958-4086ab62c264', 'Misak-ı Millî', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c775b81a-be61-4770-a958-4086ab62c264', 'Amasya Görüşmeleri', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('139f3c60-21c5-4b5c-b10a-a3e8d73b1bab', '091291bb-a136-48e2-94b1-8d12631be6ad', 'orta'::difficulty_level, 'TBMM''nin açılmasına doğrudan zemin hazırlayan gelişme aşağıdakilerden hangisidir?', 'TBMM''nin açılış sürecini bilir.', 'İstanbul''un İtilaf Devletlerince resmen işgal edilmesi (16 Mart 1920) ve Mebusan Meclisi''nin kapatılması üzerine, milli iradeyi temsil edecek yeni bir meclise duyulan ihtiyaçla Ankara''da TBMM açılmıştır (23 Nisan 1920) (D doğru). A, B ve C''deki olaylar TBMM açıldıktan SONRA gerçekleşmiştir. E''deki Sivas Kongresi TBMM''nin açılışından önce olsa da açılışın DOĞRUDAN nedeni değildir; doğrudan neden İstanbul''un işgalidir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('139f3c60-21c5-4b5c-b10a-a3e8d73b1bab', 'I. İnönü Muharebesi''nin kazanılması', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('139f3c60-21c5-4b5c-b10a-a3e8d73b1bab', 'Sakarya Meydan Muharebesi''nin kazanılması', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('139f3c60-21c5-4b5c-b10a-a3e8d73b1bab', 'Lozan Antlaşması''nın imzalanması', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('139f3c60-21c5-4b5c-b10a-a3e8d73b1bab', 'İstanbul''un işgal edilmesi ve Mebusan Meclisi''nin kapatılması', true, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('139f3c60-21c5-4b5c-b10a-a3e8d73b1bab', 'Sivas Kongresi''nin toplanması', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('52aec63b-fefc-4d40-be9b-b136beb5a7ae', '091291bb-a136-48e2-94b1-8d12631be6ad', 'zor'::difficulty_level, 'Lozan Antlaşması ile ilgili aşağıdaki bilgilerden hangisi doğrudur?', 'Lozan Antlaşması''nın kazanımlarını ve çözülemeyen sorunlarını değerlendirir.', 'Lozan Antlaşması''nda kapitülasyonlar tamamen kaldırılmış olsa da Musul ve Boğazlar sorunları TAM olarak çözülememiş, bu sorunlar ileriki yıllara (Musul için 1926 Ankara Antlaşması, Boğazlar için 1936 Montrö Sözleşmesi) bırakılmıştır (C doğru). A yanlıştır, Lozan bir ateşkes değil BARIŞ antlaşmasıdır (ateşkes Mudanya''dır). B yanlıştır, kapitülasyonlar kısmen değil TAMAMEN kaldırılmıştır. D yanlıştır, Musul sorunu Lozan''da çözülmemiştir. E yanlıştır, Türkiye''nin bağımsızlığı Lozan ile uluslararası alanda TANINMIŞTIR, aksi doğru değildir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('52aec63b-fefc-4d40-be9b-b136beb5a7ae', 'Lozan, Kurtuluş Savaşı''nı sona erdiren bir ateşkes antlaşmasıdır.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('52aec63b-fefc-4d40-be9b-b136beb5a7ae', 'Kapitülasyonlar kısmen kaldırılmış, bazı ayrıcalıklar devam etmiştir.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('52aec63b-fefc-4d40-be9b-b136beb5a7ae', 'Musul ve Boğazlar sorunları tam çözülemeyip sonraki yıllara bırakılmıştır.', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('52aec63b-fefc-4d40-be9b-b136beb5a7ae', 'Musul sorunu bu antlaşmayla kesin olarak Türkiye lehine çözülmüştür.', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('52aec63b-fefc-4d40-be9b-b136beb5a7ae', 'Bu antlaşmayla Türkiye''nin bağımsızlığı uluslararası alanda tanınmamıştır.', false, 4);

insert into topic_contents (topic_id, summary, content_md, example_question) values ('3c087fbc-2d70-4b75-880e-8e2f9e4475fb', 'Cumhuriyetin ilanı ve halifeliğin kaldırılmasıyla başlayan siyasi inkılaplar; Medeni Kanun''un kabulüyle hukuk alanındaki köklü değişim; Tevhid-i Tedrisat ve harf inkılabıyla eğitim-kültür alanındaki dönüşüm; İzmir İktisat Kongresi ve aşar vergisinin kaldırılmasıyla ekonomik atılım; kadınlara siyasi hakların tanınmasıyla toplumsal inkılaplar bu konunun beş temel alt başlığıdır.', '## Siyasi İnkılaplar
Cumhuriyet, 29 Ekim 1923''te ilan edilmiş, ilk Cumhurbaşkanı Mustafa Kemal seçilmiştir. Halifelik, 3 Mart 1924''te kaldırılmıştır; bu, laik devlet düzenine geçişte en kritik adımlardan biridir çünkü halifelik hem dini hem de TBMM''nin egemenliğiyle çelişen bir siyasi otorite kaynağıydı. Aynı gün Tevhid-i Tedrisat Kanunu da kabul edilmiştir.

## Hukuk İnkılapları
1926''da İsviçre Medeni Kanunu esas alınarak Türk Medeni Kanunu kabul edilmiştir; bu kanunla tek eşlilik getirilmiş, kadın-erkek miras ve boşanma hakları eşitlenmiş, mahkemelerde din esaslı değil laik hukuk ilkeleri benimsenmiştir. Aynı dönemde İtalyan Ceza Kanunu ve Alman Ticaret Kanunu''ndan da uyarlamalar yapılmıştır.

## Eğitim ve Kültür İnkılapları
Tevhid-i Tedrisat Kanunu (3 Mart 1924) ile eğitim kurumları Millî Eğitim Bakanlığı çatısı altında BİRLEŞTİRİLMİŞ, medreseler kapatılmıştır; bu, eğitimde laikleşmenin ve birliğin sağlanmasıdır. 1928''de Latin harflerine dayalı yeni Türk alfabesi kabul edilmiş (Harf İnkılabı), okuryazarlık oranını artırmak amacıyla Millet Mektepleri açılmıştır.

## Ekonomik İnkılaplar
1923''te toplanan İzmir İktisat Kongresi''nde "Misak-ı İktisadi" ilkeleri belirlenmiş, millî ve bağımsız bir ekonomi hedeflenmiştir. 1925''te Aşar vergisi (Osmanlı''dan kalma, üretim üzerinden alınan ağır bir vergi) kaldırılarak çiftçinin yükü hafifletilmiştir. Kabotaj Kanunu (1926) ile Türk karasularında taşımacılık yalnızca Türk gemilerine bırakılmıştır.

## Toplumsal İnkılaplar
Kılık-Kıyafet Kanunu (Şapka İnkılabı, 1925) ile fes kaldırılmıştır. Kadınlara sırasıyla belediye seçimlerinde (1930), muhtarlık seçimlerinde (1933) ve son olarak 1934''te milletvekili seçme ve seçilme hakkı tanınmıştır; bu, dönemin birçok Avrupa ülkesinden (örneğin Fransa 1944) ÖNCE gerçekleşmiş bir kazanımdır. Soyadı Kanunu (1934) ile herkesin bir soyadı alması zorunlu kılınmıştır.

## Kritik Hap Notlar
- Halifeliğin kaldırılması (3 Mart 1924) ile Tevhid-i Tedrisat Kanunu''nun kabulü AYNI GÜNE denk gelir; bu iki inkılap sırasıyla siyasi ve eğitim alanındaki laikleşmeyi simgeler.
- Medeni Kanun (1926) İSVİÇRE''den, Ceza Kanunu İTALYA''dan, Ticaret Kanunu ALMANYA''dan uyarlanmıştır — bu üçlü eşleştirme ÖSYM''nin klasik "hangi kanun hangi ülkeden" tuzağıdır.
- Kadınlara seçme-seçilme hakkı KADEMELİ olarak tanınmıştır: 1930 belediye, 1933 muhtarlık, 1934 milletvekilliği — bu sıralama sıkça karıştırılır.
- Aşar vergisinin kaldırılması (1925) EKONOMİK bir inkılaptır ve doğrudan çiftçiyi rahatlatmayı hedeflemiştir; toplumsal değil ekonomik kategoriye girer.
- Harf İnkılabı (1928), okuryazarlığı artırmak ve BATI ile kültürel-bilimsel entegrasyonu kolaylaştırmak amacıyla yapılmıştır; Latin alfabesine geçişle birlikte Millet Mektepleri açılarak halka okuma-yazma öğretilmiştir.

## Video Ders Takip Rehberi
- [00:00 - 05:00] Cumhuriyetin ilanı ve halifeliğin kaldırılması: siyasi inkılaplar.
- [05:00 - 12:00] Medeni Kanun ve hukuk alanındaki köklü değişim.
- [12:00 - 20:00] Tevhid-i Tedrisat, Harf İnkılabı ve ekonomik inkılaplar (İzmir İktisat Kongresi, Aşar''ın kaldırılması).
- [20:00 - Bitiş] Toplumsal inkılaplar: kılık-kıyafet, kadın hakları ve soyadı kanunu.', 'Türk Medeni Kanunu hangi ülkenin kanunundan esinlenerek 1926''da kabul edilmiştir?
A) Fransa B) Almanya C) İtalya D) İsviçre E) İngiltere
Doğru Cevap: D — Türk Medeni Kanunu, 1926''da İsviçre Medeni Kanunu esas alınarak kabul edilmiştir.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('2aa8e743-ebdb-43cd-b861-0fa83ac78809', '3c087fbc-2d70-4b75-880e-8e2f9e4475fb', 'kolay'::difficulty_level, 'Cumhuriyetin ilan edildiği tarih ve ilk Cumhurbaşkanı aşağıdakilerden hangisinde doğru verilmiştir?', 'Cumhuriyetin ilanını bilir.', 'Cumhuriyet 29 Ekim 1923''te ilan edilmiş ve Mustafa Kemal ilk Cumhurbaşkanı seçilmiştir (B doğru). Diğer seçeneklerdeki tarihler (3 Mart 1924 halifeliğin kaldırılması, 1926 Medeni Kanun, 1928 Harf İnkılabı, 1934 kadınlara seçme-seçilme hakkı) farklı inkılaplara aittir ve Cumhuriyetin ilan tarihiyle karıştırılmamalıdır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2aa8e743-ebdb-43cd-b861-0fa83ac78809', '3 Mart 1924 - Mustafa Kemal', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2aa8e743-ebdb-43cd-b861-0fa83ac78809', '29 Ekim 1923 - Mustafa Kemal', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2aa8e743-ebdb-43cd-b861-0fa83ac78809', '1926 - İsmet İnönü', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2aa8e743-ebdb-43cd-b861-0fa83ac78809', '1928 - Mustafa Kemal', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2aa8e743-ebdb-43cd-b861-0fa83ac78809', '1934 - İsmet İnönü', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('e7682692-4828-4a0f-bdab-26aa1703b864', '3c087fbc-2d70-4b75-880e-8e2f9e4475fb', 'orta'::difficulty_level, 'Aşağıdakilerden hangisi 3 Mart 1924 tarihinde gerçekleşen iki önemli gelişmeden biri değildir?', 'Aynı tarihte gerçekleşen inkılapları ayırt eder.', 'Medeni Kanun''un kabulü 1926 yılında gerçekleşmiştir, 3 Mart 1924''te DEĞİL (C doğru, gerçekleşmeyen). Halifeliğin kaldırılması (A) ve Tevhid-i Tedrisat Kanunu''nun kabulü (B) aynı gün, 3 Mart 1924''te gerçekleşmiştir. Şer''iye ve Evkaf Vekaleti''nin kaldırılması (D) ile Erkân-ı Harbiye-i Umumiye Vekaleti''nin kaldırılması (E) da aynı gün alınan kararlar arasındadır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e7682692-4828-4a0f-bdab-26aa1703b864', 'Halifeliğin kaldırılması', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e7682692-4828-4a0f-bdab-26aa1703b864', 'Tevhid-i Tedrisat Kanunu''nun kabulü', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e7682692-4828-4a0f-bdab-26aa1703b864', 'Türk Medeni Kanunu''nun kabulü', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e7682692-4828-4a0f-bdab-26aa1703b864', 'Şer''iye ve Evkaf Vekaleti''nin kaldırılması', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e7682692-4828-4a0f-bdab-26aa1703b864', 'Erkân-ı Harbiye-i Umumiye Vekaleti''nin kaldırılması', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('6fd0a121-e382-47e2-b1d8-f7ba73ca0f0b', '3c087fbc-2d70-4b75-880e-8e2f9e4475fb', 'orta'::difficulty_level, 'Kadınlara milletvekili seçme ve seçilme hakkının tanındığı yıl aşağıdakilerden hangisidir?', 'Kadın haklarındaki kademeli gelişimi bilir.', 'Kadınlara milletvekili seçme ve seçilme hakkı 1934''te tanınmıştır (D doğru); bu hak, belediye (1930) ve muhtarlık (1933) seçimlerindeki haklardan sonra en geniş kapsamlı olanıdır. 1923 (A), 1926 (B) ve 1930 (C) bu son aşamadan önceki farklı gelişmelere ait tarihlerdir; 1930''da yalnızca belediye seçimlerinde hak tanınmıştı, milletvekilliği değil.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('6fd0a121-e382-47e2-b1d8-f7ba73ca0f0b', '1923', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('6fd0a121-e382-47e2-b1d8-f7ba73ca0f0b', '1926', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('6fd0a121-e382-47e2-b1d8-f7ba73ca0f0b', '1930', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('6fd0a121-e382-47e2-b1d8-f7ba73ca0f0b', '1934', true, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('6fd0a121-e382-47e2-b1d8-f7ba73ca0f0b', '1938', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('258257dc-6234-4625-9aba-f3c6cdc5fa87', '3c087fbc-2d70-4b75-880e-8e2f9e4475fb', 'zor'::difficulty_level, 'Aşar vergisinin kaldırılması (1925) ile ilgili aşağıdaki yargılardan hangisi doğrudur?', 'Ekonomik inkılapları toplumsal/siyasi inkılaplardan ayırt eder.', 'Aşar vergisinin kaldırılması, üretim üzerinden alınan ağır bir Osmanlı vergisini ortadan kaldırarak çiftçinin ekonomik yükünü azaltmayı amaçlayan EKONOMİK bir inkılaptır (B doğru). A yanlıştır, bu bir toplumsal değil ekonomik inkılaptır. C yanlıştır, bu adım köylüyü/çiftçiyi rahatlatmıştır, zorlaştırmamıştır. D yanlıştır, kaldırılan bir üretim vergisidir, gümrük vergisi değildir. E yanlıştır, bu düzenleme Cumhuriyetin ilanından SONRA (1925) yapılmıştır, Kurtuluş Savaşı sırasında değil.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('258257dc-6234-4625-9aba-f3c6cdc5fa87', 'Bu, toplumsal alanda yapılan bir inkılaptır.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('258257dc-6234-4625-9aba-f3c6cdc5fa87', 'Bu, çiftçinin ekonomik yükünü azaltmayı amaçlayan ekonomik bir inkılaptır.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('258257dc-6234-4625-9aba-f3c6cdc5fa87', 'Bu düzenleme köylünün vergi yükünü artırmıştır.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('258257dc-6234-4625-9aba-f3c6cdc5fa87', 'Aşar, dış ticaretten alınan bir gümrük vergisidir.', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('258257dc-6234-4625-9aba-f3c6cdc5fa87', 'Bu düzenleme Kurtuluş Savaşı sırasında yapılmıştır.', false, 4);

insert into topics (id, subject_id, name, slug, kazanim_text, weight, order_index) values ('44672589-4a32-4299-951a-afa51d7c3099', '0074c5df-5b70-4274-9235-a8fcfb386791', 'İlk Türk-İslam Devletleri', 'ilk-turk-islam-devletleri', 'Türklerin İslamiyet''i kabul sürecini ve ilk Türk-İslam devletlerinin (Karahanlı, Gazneli, Büyük Selçuklu, Anadolu Selçuklu) özelliklerini bilir.', 1.0, 5);
insert into topic_contents (topic_id, summary, content_md, example_question) values ('44672589-4a32-4299-951a-afa51d7c3099', 'Talas Savaşı ile başlayan Türk-Arap yakınlaşması sonrası Türklerin kitleler hâlinde İslamiyet''i kabul etmesi, ardından kurulan Karahanlı Devleti (ilk Türk-İslam devleti), Gazneliler, Büyük Selçuklu Devleti (Malazgirt Zaferi ile Anadolu''nun kapılarının açılması) ve Anadolu Selçuklu Devleti bu konunun temel yapı taşlarıdır.', '## Talas Savaşı (751) ve İslamiyet''in Kabulü
Talas Savaşı, Türklerin (Karluklar) Çinlilere karşı Abbasilerin yanında yer almasıyla gerçekleşmiş ve Çin''in Orta Asya''daki ilerleyişi durdurulmuştur. Bu savaş sonrasında Türkler ile Müslüman Araplar arasındaki ilişkiler gelişmiş, Türkler arasında İslamiyet hızla ve kitleler hâlinde yayılmaya başlamıştır. Türklerin İslamiyet''i benimsemesinde askerlik geleneği (cihat-gaza anlayışı ile Türk savaşçılık kültürünün örtüşmesi), tek tanrı inancına (Gök Tanrı) zaten sahip olmaları gibi faktörler de etkili olmuştur.

## Karahanlı Devleti (İlk Türk-İslam Devleti)
Karahanlılar, İslamiyet''i resmî din olarak kabul eden İLK Türk-İslam devletidir (Satuk Buğra Han döneminde). Kaşgarlı Mahmud''un Divan-ı Lügati''t Türk''ü ve Yusuf Has Hacib''in Kutadgu Bilig''i bu dönemde yazılan, Türk-İslam kültürünü yansıtan en önemli eserlerdir.

## Gazneli Devleti
Gazneliler, Sultan Mahmud döneminde Hindistan''a düzenlediği seferlerle hem İslamiyet''i bu bölgede yaymış hem de "Sultan" unvanını halifeden alan İLK Türk-İslam hükümdarı olmuştur. Devlet, Dandanakan Savaşı''nda (1040) Büyük Selçuklulara yenilerek zayıflamıştır.

## Büyük Selçuklu Devleti
Tuğrul Bey tarafından kurulmuş, Bağdat''ı Büveyhoğullarının baskısından kurtararak halifeyi koruyan devlet konumuna gelmiş ve halife tarafından "Doğu''nun ve Batı''nın Sultanı" unvanı verilmiştir. Alparslan döneminde kazanılan Malazgirt Zaferi (1071), Anadolu''nun Türklere açılmasını sağlayan dönüm noktasıdır. Melikşah döneminde Nizamülmülk tarafından kurulan Nizamiye Medreseleri, İslam dünyasının ilk sistemli yükseköğretim kurumlarındandır.

## Anadolu (Türkiye) Selçuklu Devleti
Malazgirt sonrası Süleyman Şah tarafından kurulan bu devlet, Anadolu''nun Türkleşmesi ve İslamlaşması sürecinin öncüsüdür; I. Alaeddin Keykubad döneminde en parlak dönemini yaşamıştır. Moğol istilası sonucu 1243 Kösedağ Savaşı''nda alınan yenilgiyle devlet zayıflamış ve dağılma sürecine girmiştir; bu dağılma Anadolu''da beyliklerin (ve sonunda Osmanlı''nın) doğmasına zemin hazırlamıştır.

## Kritik Hap Notlar
- Talas Savaşı (751), Türklerin İslamiyet''i toplu olarak kabul etme SÜRECİNİ başlatan olaydır; savaşın kendisinde doğrudan din değiştirme olmamıştır, süreç zamana yayılmıştır.
- Karahanlılar İLK Türk-İslam devletidir (Satuk Buğra Han); Gazneliler ise "Sultan" unvanını halifeden alan İLK Türk-İslam hükümdarına (Sultan Mahmud) sahiptir — bu iki "ilk" birbirine karıştırılmamalıdır.
- Malazgirt Zaferi (1071, Alparslan), Anadolu''nun Türklere AÇILDIĞI, Anadolu''nun Türk yurdu hâline gelme sürecinin BAŞLANGICI olan dönüm noktasıdır.
- Nizamiye Medreseleri (Nizamülmülk, Melikşah dönemi) devlete bağlı memur yetiştirmeyi amaçlayan, İslam dünyasının ilk sistemli-planlı eğitim kurumlarıdır.
- Anadolu Selçuklu Devleti''nin Kösedağ Savaşı''nda (1243) Moğollara yenilmesi, devletin zayıflayıp dağılmasına ve Anadolu''da Türk beyliklerinin (dolayısıyla Osmanlı Beyliği''nin) ortaya çıkmasına zemin hazırlamıştır.

## Video Ders Takip Rehberi
- [00:00 - 05:00] Talas Savaşı ve Türklerin İslamiyet''i kabul süreci.
- [05:00 - 12:00] Karahanlı Devleti ve dönemin kültürel eserleri (Kutadgu Bilig, Divan-ı Lügati''t Türk).
- [12:00 - 20:00] Gazneli Devleti ve Büyük Selçuklu Devleti: Malazgirt Zaferi ve Nizamiye Medreseleri.
- [20:00 - Bitiş] Anadolu Selçuklu Devleti''nin yükselişi ve Kösedağ Savaşı sonrası dağılma süreci.', 'İslamiyet''i resmî din olarak kabul eden ilk Türk-İslam devleti aşağıdakilerden hangisidir?
A) Gazneli Devleti B) Karahanlı Devleti C) Büyük Selçuklu Devleti D) Anadolu Selçuklu Devleti E) Harzemşahlar
Doğru Cevap: B — Karahanlı Devleti, Satuk Buğra Han döneminde İslamiyet''i resmî din olarak kabul eden ilk Türk-İslam devletidir.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('a5262f9c-c4db-4566-a5aa-dcbdfc40efa4', '44672589-4a32-4299-951a-afa51d7c3099', 'kolay'::difficulty_level, 'Türklerin Çinlilere karşı Abbasilerin yanında yer alarak Çin''in Orta Asya''daki ilerleyişini durdurduğu ve İslamiyet''in Türkler arasında yayılma sürecini başlatan savaş aşağıdakilerden hangisidir?', 'Talas Savaşı''nın önemini bilir.', 'Talas Savaşı (751), Türklerin (Karluklar) Abbasiler safında Çinlilere karşı savaşmasıyla gerçekleşmiş ve Türk-Arap yakınlaşmasıyla İslamiyet''in Türkler arasında yayılma sürecini başlatmıştır (C doğru). Malazgirt (A) ve Dandanakan (B) daha sonraki Selçuklu dönemi savaşlarıdır. Kösedağ (D) Anadolu Selçuklularının Moğollara yenildiği savaştır. Miryokefalon (E) 1176''da gerçekleşmiş farklı bir savaştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a5262f9c-c4db-4566-a5aa-dcbdfc40efa4', 'Malazgirt Savaşı', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a5262f9c-c4db-4566-a5aa-dcbdfc40efa4', 'Dandanakan Savaşı', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a5262f9c-c4db-4566-a5aa-dcbdfc40efa4', 'Talas Savaşı', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a5262f9c-c4db-4566-a5aa-dcbdfc40efa4', 'Kösedağ Savaşı', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a5262f9c-c4db-4566-a5aa-dcbdfc40efa4', 'Miryokefalon Savaşı', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('00262069-ea1b-4cb7-91ed-f0bc05b6b443', '44672589-4a32-4299-951a-afa51d7c3099', 'orta'::difficulty_level, '''Sultan'' unvanını halifeden alan ilk Türk-İslam hükümdarı ve devleti aşağıdakilerden hangisinde doğru eşleştirilmiştir?', 'Gazneli Devleti''nin özelliklerini bilir.', 'Gazneli Sultan Mahmud, halifeden ''Sultan'' unvanını alan ilk Türk-İslam hükümdarıdır (B doğru). Satuk Buğra Han (A) Karahanlıların İslamiyet''i kabul eden hükümdarıdır ama sultan unvanı almamıştır. Tuğrul Bey (C) Büyük Selçuklu''nun kurucusudur ve ''sultan'' unvanını Sultan Mahmud''dan sonra almıştır. Alparslan (D) ve Melikşah (E) sonraki Selçuklu hükümdarlarıdır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('00262069-ea1b-4cb7-91ed-f0bc05b6b443', 'Satuk Buğra Han - Karahanlı Devleti', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('00262069-ea1b-4cb7-91ed-f0bc05b6b443', 'Sultan Mahmud - Gazneli Devleti', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('00262069-ea1b-4cb7-91ed-f0bc05b6b443', 'Tuğrul Bey - Büyük Selçuklu Devleti', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('00262069-ea1b-4cb7-91ed-f0bc05b6b443', 'Alparslan - Büyük Selçuklu Devleti', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('00262069-ea1b-4cb7-91ed-f0bc05b6b443', 'Melikşah - Büyük Selçuklu Devleti', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('3e5cc241-7d76-4c58-b432-e525e6bd282c', '44672589-4a32-4299-951a-afa51d7c3099', 'orta'::difficulty_level, 'Anadolu''nun Türklere açılmasını sağlayan dönüm noktası olan savaş ve hükümdarı aşağıdakilerden hangisinde doğru verilmiştir?', 'Malazgirt Zaferi''nin önemini bilir.', 'Malazgirt Zaferi (1071), Büyük Selçuklu hükümdarı Alparslan tarafından Bizans''a karşı kazanılmış ve Anadolu''nun Türklere açılmasını sağlayan dönüm noktası olmuştur (C doğru). Dandanakan (A, Tuğrul Bey döneminde Gaznelilere karşı kazanılmıştır) ve Talas (B) farklı savaşlardır. Kösedağ (D) ise Anadolu Selçuklularının Moğollara YENİLDİĞİ, gerileme sürecini başlatan bir savaştır. Miryokefalon (E) II. Kılıçarslan döneminde kazanılmış farklı bir zaferdir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3e5cc241-7d76-4c58-b432-e525e6bd282c', 'Dandanakan Savaşı - Tuğrul Bey', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3e5cc241-7d76-4c58-b432-e525e6bd282c', 'Talas Savaşı - Karluklar', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3e5cc241-7d76-4c58-b432-e525e6bd282c', 'Malazgirt Savaşı - Alparslan', true, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3e5cc241-7d76-4c58-b432-e525e6bd282c', 'Kösedağ Savaşı - II. Gıyaseddin Keyhüsrev', false, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3e5cc241-7d76-4c58-b432-e525e6bd282c', 'Miryokefalon Savaşı - II. Kılıçarslan', false, 4);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('37fb1c4a-74d0-4144-a4d6-4fe35a35bfb3', '44672589-4a32-4299-951a-afa51d7c3099', 'zor'::difficulty_level, 'Anadolu Selçuklu Devleti''nin 1243 Kösedağ Savaşı''nda yenilmesinin sonuçlarıyla ilgili aşağıdaki yargılardan hangisi doğrudur?', 'Kösedağ Savaşı''nın sonuçlarını değerlendirir.', 'Kösedağ Savaşı''nda Moğollara yenilen Anadolu Selçuklu Devleti büyük ölçüde zayıflamış, merkezi otoritesini kaybetmiş ve bu durum Anadolu''da çeşitli Türk beyliklerinin (bunlardan biri de daha sonra Osmanlı Devleti''ne dönüşecek olan Osmanlı Beyliği) ortaya çıkmasına zemin hazırlamıştır (D doğru). A yanlıştır, bu yenilgi devleti GÜÇLENDİRMEMİŞ, zayıflatmıştır. B yanlıştır, Nizamiye Medreseleri Büyük Selçuklu döneminde (Melikşah-Nizamülmülk) kurulmuştur, Kösedağ''ın sonucu değildir. C yanlıştır, bu savaş Malazgirt gibi Anadolu''nun Türklere AÇILMASINI değil devletin dağılmasını getirmiştir. E yanlıştır, bu savaş Bizans''a karşı değil Moğollara karşı kaybedilmiştir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('37fb1c4a-74d0-4144-a4d6-4fe35a35bfb3', 'Anadolu Selçuklu Devleti bu zaferle güçlenmiştir.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('37fb1c4a-74d0-4144-a4d6-4fe35a35bfb3', 'Bu savaş sonucunda Nizamiye Medreseleri kurulmuştur.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('37fb1c4a-74d0-4144-a4d6-4fe35a35bfb3', 'Bu savaş, Anadolu''nun Türklere açılmasını sağlamıştır.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('37fb1c4a-74d0-4144-a4d6-4fe35a35bfb3', 'Devlet zayıflamış, bu durum Anadolu''da Türk beyliklerinin doğmasına zemin hazırlamıştır.', true, 3);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('37fb1c4a-74d0-4144-a4d6-4fe35a35bfb3', 'Bu savaş Bizans İmparatorluğu''na karşı kazanılmıştır.', false, 4);

