begin;
-- ===== turkce =====
insert into topic_contents (topic_id, summary, content_md, example_question) values ('ffe5c195-5fea-45a3-9030-58f122e0e1ee', 'Ünlü ve ünsüz uyumu, ünsüz yumuşaması/sertleşmesi, ünlü düşmesi ve kaynaştırma ünsüzleri gibi ses olaylarını kapsayan bu konu, Türkçenin ses bilgisi kurallarını örneklerle açıklar.', '## Büyük Ünlü Uyumu (Kalınlık-İncelik Uyumu)
Türkçe kökenli bir kelimenin ilk hecesinde kalın ünlü (a, ı, o, u) varsa sonraki hecelerde de kalın ünlü bulunur; ilk hecede ince ünlü (e, i, ö, ü) varsa sonraki hecelerde de ince ünlü bulunur. Örneğin ''kalemlik'' kelimesindeki ''kalem'' kökü Arapça kökenli olduğu için bu kurala aykırıdır (a-e). ''Kalem, hangi, elma, anne'' gibi bazı yabancı kökenli ya da kalıplaşmış kelimeler bu kuralın istisnasıdır.

## Küçük Ünlü Uyumu (Düzlük-Yuvarlaklık Uyumu)
Düz ünlülerden (a, e, ı, i) sonra düz ünlü gelir. Yuvarlak ünlülerden (o, ö, u, ü) sonra ise ya düz-geniş (a, e) ya da dar-yuvarlak (u, ü) ünlü gelir. ''Doktor, otobüs, radyo'' gibi yabancı kökenli kelimeler bu kurala da aykırıdır çünkü yuvarlak bir ünlüden sonra yine geniş-yuvarlak (o, ö) bir ünlü gelmiştir.

## Ünsüz Benzeşmesi (Sertleşme)
Sert ünsüzle (ç, f, h, k, p, s, ş, t = ''fıstıkçı şahap'') biten bir kelimeye yumuşak ünsüzle başlayan bir ek gelirse, ekin başındaki ünsüz sertleşir: kitap+cı → kitapçı, ağaç+da → ağaçta, iş+ci → işçi.

## Ünsüz Yumuşaması
p, ç, t, k ile biten bir kelime ünlüyle başlayan bir ek aldığında bu ünsüzler yumuşayarak sırasıyla b, c, d, ğ/g''ye dönüşür: kitap→kitabı, ağaç→ağacı, at→adı, çocuk→çocuğu.

## Ünlü Düşmesi (Hece Düşmesi)
İkinci hecesinde dar ünlü (ı, i, u, ü) bulunan bazı iki heceli kelimeler ünlüyle başlayan bir ek aldığında bu dar ünlü düşer: burun→burnu, ağız→ağzı, akıl→aklı, oğul→oğlu, şehir→şehri.

## Kaynaştırma Ünsüzleri
Ünlüyle biten bir kelime ünlüyle başlayan bir ek aldığında, iki ünlünün yan yana gelmesini önlemek için araya ''y, ş, s, n'' kaynaştırma ünsüzlerinden biri girer: kapı+ı→kapıyı, iki+er→ikişer, araba+ın→arabasının, kapı+ın→kapının.', 'Örnek: ''Ağacın gölgesinde otururken kitabını okudu.'' cümlesinde hangi kelimede ünsüz yumuşaması görülür?') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('82c89bf9-b824-4eda-b869-c2179bf5e02f', 'ffe5c195-5fea-45a3-9030-58f122e0e1ee', 'kolay'::difficulty_level, 'Aşağıdaki kelimelerden hangisi büyük ünlü uyumuna (kalınlık-incelik uyumuna) aykırıdır?', 'Büyük ünlü uyumu kuralını kelimeler üzerinde uygular.', '''Kalem'' kökü Arapça kökenli olup ilk hecesinde kalın ünlü (a), ikinci hecesinde ince ünlü (e) bulunur; bu nedenle kelime büyük ünlü uyumuna aykırıdır. Diğer seçeneklerdeki kelimelerin tüm heceleri ya kalın ya da ince ünlülerden oluşur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('82c89bf9-b824-4eda-b869-c2179bf5e02f', 'kalemlik', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('82c89bf9-b824-4eda-b869-c2179bf5e02f', 'yapraklar', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('82c89bf9-b824-4eda-b869-c2179bf5e02f', 'sevgili', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('82c89bf9-b824-4eda-b869-c2179bf5e02f', 'doğrular', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('dcb84efc-8ed4-4ec8-8251-bb7979cfb0ad', 'ffe5c195-5fea-45a3-9030-58f122e0e1ee', 'kolay'::difficulty_level, 'Aşağıdaki kelimelerin hangisinde ünsüz yumuşaması (p, ç, t, k seslerinin yumuşaması) görülür?', 'Ünsüz yumuşaması kuralını örneklerde tespit eder.', '''Ağaç'' kökündeki sert ünsüz ''ç'', ünlüyle başlayan iyelik eki ''-ı'' aldığında yumuşayarak ''c''ye dönüşmüş ve ''ağacı'' biçimini almıştır. Diğer seçeneklerde ünsüzle başlayan ekler geldiği için yumuşama gerçekleşmez.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('dcb84efc-8ed4-4ec8-8251-bb7979cfb0ad', 'kitaptan', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('dcb84efc-8ed4-4ec8-8251-bb7979cfb0ad', 'ağacı', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('dcb84efc-8ed4-4ec8-8251-bb7979cfb0ad', 'sokakta', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('dcb84efc-8ed4-4ec8-8251-bb7979cfb0ad', 'çocuktan', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('183f9726-9198-460f-8319-f4a5bb5f1fe5', 'ffe5c195-5fea-45a3-9030-58f122e0e1ee', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde ünlü düşmesi (hece düşmesi) örneği vardır?', 'Ünlü düşmesi kuralının işlediği kelimeleri cümlede belirler.', '''Burun'' kelimesi ünlüyle başlayan iyelik eki ''-u'' aldığında ikinci hecesindeki dar ünlü ''u'' düşerek ''burnu'' biçimini almıştır. Diğer cümlelerdeki kelimelerde böyle bir ses düşmesi yoktur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('183f9726-9198-460f-8319-f4a5bb5f1fe5', 'Burnu kanayan çocuğu hemen hastaneye götürdüler.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('183f9726-9198-460f-8319-f4a5bb5f1fe5', 'Bahçedeki güller sabaha karşı açmıştı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('183f9726-9198-460f-8319-f4a5bb5f1fe5', 'Kitapları düzenli bir şekilde masaya bıraktı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('183f9726-9198-460f-8319-f4a5bb5f1fe5', 'Sınavdan beklediğinden yüksek bir not aldı.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('3ba99267-70c5-469b-ae8f-3ecb3d52cb99', 'ffe5c195-5fea-45a3-9030-58f122e0e1ee', 'orta'::difficulty_level, 'Aşağıdaki kelimelerin hangisinde kaynaştırma ünsüzü kullanılmıştır?', 'Kaynaştırma ünsüzlerinin kullanıldığı kelimeleri ayırt eder.', 'Ünlüyle biten ''kapı'' kelimesi ünlüyle başlayan ''-ı'' ekini aldığında iki ünlünün yan yana gelmesini önlemek için araya ''y'' kaynaştırma ünsüzü girmiş ve ''kapıyı'' biçimi oluşmuştur. Diğer seçeneklerdeki ekler ünsüzle başladığı için kaynaştırma ünsüzüne gerek yoktur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3ba99267-70c5-469b-ae8f-3ecb3d52cb99', 'kapıyı', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3ba99267-70c5-469b-ae8f-3ecb3d52cb99', 'evden', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3ba99267-70c5-469b-ae8f-3ecb3d52cb99', 'kitaplar', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('3ba99267-70c5-469b-ae8f-3ecb3d52cb99', 'sokakta', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('d46bd22e-5c11-486b-9f0c-5768bd9d69d4', 'ffe5c195-5fea-45a3-9030-58f122e0e1ee', 'zor'::difficulty_level, 'Aşağıdaki kelimelerden hangisi küçük ünlü uyumuna (düzlük-yuvarlaklık uyumuna) aykırıdır?', 'Küçük ünlü uyumu kuralını ileri düzeyde uygular.', 'Yuvarlak bir ünlüden (o) sonra ancak düz-geniş (a, e) ya da dar-yuvarlak (u, ü) bir ünlü gelebilir; ''doktor'' kelimesinde ise yuvarlak ''o'' ünlüsünden sonra yine geniş-yuvarlak ''o'' geldiği için kural bozulmuştur. Diğer kelimelerin tamamı küçük ünlü uyumuna uygundur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('d46bd22e-5c11-486b-9f0c-5768bd9d69d4', 'doktor', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('d46bd22e-5c11-486b-9f0c-5768bd9d69d4', 'kuzu', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('d46bd22e-5c11-486b-9f0c-5768bd9d69d4', 'çocuk', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('d46bd22e-5c11-486b-9f0c-5768bd9d69d4', 'balık', false, 3);
insert into topic_contents (topic_id, summary, content_md, example_question) values ('9683464a-e0ce-493b-ae60-58c924e2ae5c', 'Bu konu; ''de/da'' bağlacı ile hâl eki, ''ki'' bağlacı ile ''-ki'' eki, ''mi'' soru eki ve büyük harf kullanımı gibi en sık karıştırılan yazım kurallarını örneklerle ele alır.', '## ''de/da'' Bağlacı ve Hâl Eki
Bağlaç olan ''de/da'' her zaman ayrı yazılır ve sertleşerek ''te/ta'' biçimini almaz: ''O da bizimle geldi.'' Cümleden çıkarıldığında anlam bütünlüğü bozulmuyorsa bağlaçtır. Bulunma hâli eki olan ''-de/-da'' ise bitişik yazılır ve sert ünsüzden sonra ''-te/-ta'' biçimine sertleşebilir: ''Evde kimse yoktu.'', ''Kitapta ilginç bilgiler vardı.''

## ''mi'' Soru Eki
Soru eki ''mi/mı/mu/mü'' her zaman kendinden önceki kelimeden ayrı yazılır; kendisinden sonra gelen ekler ise bitişik yazılır: ''Geliyor musun?'', ''Bu doğru mudur?''

## ''ki'' Bağlacı ve ''-ki'' Eki
Bağlaç olan ''ki'' ayrı yazılır: ''Biliyordum ki bu iş kolay olmayacak.'' Sıfat yapan ilgi eki ''-ki'' ise bitişik yazılır: ''Sokaktaki çocuklar, benimki, yarınki toplantı.'' ''Hâlbuki, mademki, oysaki, sanki, belki'' gibi kalıplaşmış sözcükler bitişik yazılır; bunlar artık bağlaç ''ki'' olarak değil, tek bir kelime olarak kabul edilir.

## Büyük Harf Kullanımı
Özel adlar (kişi, yer, kurum adları), unvanlardan sonra veya önce gelen özel adlar (Ahmet Bey, Doktor Ayşe), belirli bir tarih bildiren gün ve ay adları (29 Ekim Cumhuriyet Bayramı) büyük harfle başlar. Ancak mevsim adları (ilkbahar, yaz, sonbahar, kış) hiçbir zaman büyük harfle yazılmaz; genel ifadelerde kullanılan gün ve ay adları da (''Her ay toplanırız.'') küçük harfle yazılır.

## Bitişik Yazılan Bazı Yapılar
Anlam kayması olan kalıcı birleşik kelimeler (gecekondu, hanımeli) bitişik yazılır. Yazım kuralları çoğunlukla bir ''çıkarma testi'' ile denetlenir: kelime cümleden çıkarıldığında anlam bozuluyorsa genellikle bir ektir ve bitişik yazılır; anlam bozulmuyorsa genellikle bir bağlaçtır ve ayrı yazılır.', 'Örnek: ''Sen de mi bu işe karıştın?'' cümlesindeki yazım kurallarını değerlendiriniz.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('d124c62a-8526-46e0-8e1e-e55f258ddd04', '9683464a-e0ce-493b-ae60-58c924e2ae5c', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde ''de'' bağlaç olarak kullanılmış, bu nedenle ayrı yazılmıştır?', 'Bağlaç olan ''de/da'' ile hâl eki olan ''-de/-da''yı ayırt eder.', 'İkinci cümledeki ''da'', ''O bizimle gelmek istedi.'' cümlesinden çıkarıldığında anlam bütünlüğü bozulmadığı için bağlaçtır ve ayrı yazılır. Diğer cümlelerdeki ''-de'' ekleri isme bulunma hâli katan bir ek olduğu için bitişik yazılmıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('d124c62a-8526-46e0-8e1e-e55f258ddd04', 'Sende kalan kitabımı getirir misin?', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('d124c62a-8526-46e0-8e1e-e55f258ddd04', 'O da bizimle gelmek istedi.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('d124c62a-8526-46e0-8e1e-e55f258ddd04', 'Evde kimse yoktu.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('d124c62a-8526-46e0-8e1e-e55f258ddd04', 'Bahçede oynayan çocukları gördüm.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('228ea299-39ec-435d-bbd2-e04e0d1ecca1', '9683464a-e0ce-493b-ae60-58c924e2ae5c', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde ''ki'' bağlaç olarak kullanılmış ve bu nedenle ayrı yazılmıştır?', 'Bağlaç ''ki'' ile sıfat yapan ''-ki'' ekini ayırt eder.', 'İkinci cümlede ''ki'', iki cümleyi birbirine bağlayan bir bağlaçtır ve ayrı yazılır. Diğer cümlelerde ''-ki'', isme sıfat ya da ilgi zamiri işlevi kazandıran bir ek olduğu için bitişik yazılmıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('228ea299-39ec-435d-bbd2-e04e0d1ecca1', 'Sokaktaki çocuklar top oynuyordu.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('228ea299-39ec-435d-bbd2-e04e0d1ecca1', 'Biliyordum ki bu iş kolay olmayacaktı.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('228ea299-39ec-435d-bbd2-e04e0d1ecca1', 'Benimki masanın üzerinde duruyor.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('228ea299-39ec-435d-bbd2-e04e0d1ecca1', 'Yarınki toplantıya katılamayacağım.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('da804d7f-9d9d-4054-976e-4d6c8b2b922c', '9683464a-e0ce-493b-ae60-58c924e2ae5c', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir yazım yanlışı vardır?', '''-ki'' ekinin bitişik yazılması gereken durumları fark eder.', '''Yarın'' kelimesine gelen sıfat yapan ''-ki'' eki bitişik yazılmalıdır; doğru yazım ''yarınki'' biçimindedir. Diğer cümlelerdeki yazımlar kurallara uygundur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('da804d7f-9d9d-4054-976e-4d6c8b2b922c', 'Yarın ki sınava çalışmalıyım.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('da804d7f-9d9d-4054-976e-4d6c8b2b922c', 'Sokaktaki köpek durmadan havlıyordu.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('da804d7f-9d9d-4054-976e-4d6c8b2b922c', 'O da toplantıya katılacağını söyledi.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('da804d7f-9d9d-4054-976e-4d6c8b2b922c', 'Kitaptaki resimleri çok beğendim.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('86d641d8-57e1-491f-af96-71f847be9af7', '9683464a-e0ce-493b-ae60-58c924e2ae5c', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde büyük harf kullanımıyla ilgili bir yanlışlık vardır?', 'Mevsim adlarının büyük harfle yazılmadığı kuralını uygular.', 'Mevsim adları hiçbir zaman büyük harfle başlamaz; bu nedenle ''ilkbahar'' kelimesi küçük harfle yazılmalıdır. Diğer cümlelerdeki büyük harf kullanımları (unvan, özel gün adı, dil adı) doğrudur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('86d641d8-57e1-491f-af96-71f847be9af7', 'Bu yıl İlkbahar çok erken geldi.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('86d641d8-57e1-491f-af96-71f847be9af7', 'Ahmet Bey toplantıya geç kaldı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('86d641d8-57e1-491f-af96-71f847be9af7', '29 Ekim Cumhuriyet Bayramı''nı coşkuyla kutladık.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('86d641d8-57e1-491f-af96-71f847be9af7', 'Türkçe dersinde güzel bir şiir okuduk.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('e4f17e50-babe-4eb4-99ca-71f63d1e37ed', '9683464a-e0ce-493b-ae60-58c924e2ae5c', 'zor'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir yazım yanlışı yoktur?', 'Birden fazla yazım kuralını bir arada değerlendirerek doğru cümleyi belirler.', 'İkinci cümlede bağlaç olan ''de'' doğru biçimde ayrı, soru eki ''mi'' de kurala uygun olarak ayrı yazılmıştır. Diğer cümlelerde sırasıyla ''kitapta'' yerine ''kitapda'', ''yarınki'' yerine ''yarın ki'' ve ''onunki'' yerine ''onun ki'' kullanılarak yazım yanlışı yapılmıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e4f17e50-babe-4eb4-99ca-71f63d1e37ed', 'Kitapda ne yazdığını çok merak ediyorum.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e4f17e50-babe-4eb4-99ca-71f63d1e37ed', 'Sen de mi bu işe karıştın?', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e4f17e50-babe-4eb4-99ca-71f63d1e37ed', 'Yarın ki toplantıyı sakın unutma.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('e4f17e50-babe-4eb4-99ca-71f63d1e37ed', 'Herkes onun ki kadar başarılı olamadı.', false, 3);
insert into topic_contents (topic_id, summary, content_md, example_question) values ('4d4e66fa-6b06-4194-a222-0ed30c0edd1b', 'Virgül, iki nokta, noktalı virgül, kesme işareti, üç nokta ve ünlem işaretinin doğru kullanım kurallarını örneklerle açıklayan bu konu, noktalama hatalarını ayırt etmeyi hedefler.', '## Virgül (,)
Eş görevli kelime veya kelime gruplarını sıralarken kullanılır: ''Çarşıdan elma, armut, muz ve şeftali aldı.'' Sıralı cümleleri, ara sözleri ve hitap sözlerini ayırmak için de virgül konur. ''Ve'' bağlacından hemen önce genellikle virgül kullanılmaz.

## İki Nokta (:)
Kendisinden sonra örnek verilecek, açıklama yapılacak ya da bir liste sıralanacak cümlenin sonuna konur: ''Kırtasiyeden şunları aldım: kalem, silgi, defter.'' Ayrıca alıntı sözlerden önce de kullanılır: ''Öğretmenimiz: ''Yarın sınav var.'' dedi.''

## Noktalı Virgül (;)
Virgüllerle ayrılmış öğe gruplarını birbirinden ayırmak için ya da bağlaç kullanılmadan birbirine bağlı cümleleri ayırmak için kullanılır: ''Sınıfta Ali, Veli, Ayşe; bahçede ise Mehmet, Fatma vardı.''

## Kesme İşareti ('')
Özel isimlere getirilen çekim eklerini ayırmak için kullanılır: ''İstanbul''da, Ahmet''in, Türkiye''ye.'' Cins (tür bildiren) isimlere gelen ekler kesme işaretiyle ayrılmaz: ''kalemi, öğretmene, kitabı'' gibi.

## Üç Nokta (...)
Tamamlanmamış cümlelerin sonuna, sözün bir yerde kesildiğini göstermek için ya da kaba sayılan sözlerin yerine kullanılır.

## Ünlem İşareti (!)
Sevinç, kızgınlık, korku, şaşkınlık gibi güçlü duyguları anlatan cümlelerin ve seslenme sözlerinin sonuna konur: ''Ne güzel bir manzara!''

Doğru noktalama, hem okunabilirliği artırır hem de cümlenin anlamını netleştirir; bu nedenle KPSS''de noktalama işaretlerinin yerinde kullanılıp kullanılmadığı sıkça sorulur.', 'Örnek: ''Öğretmenimiz Yarın sınav var dedi.'' cümlesinde hangi noktalama işaretleri eksiktir?') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('c909077e-57a7-4ad8-aeb0-3d91835038e9', '4d4e66fa-6b06-4194-a222-0ed30c0edd1b', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde kesme işareti ('') doğru kullanılmıştır?', 'Kesme işaretinin özel isimlere gelen eklerde kullanıldığını kavrar.', '''Ahmet'' bir özel isim olduğu için aldığı ''-in'' eki kesme işaretiyle ayrılmıştır. Diğer seçeneklerdeki ''kalem, öğretmen, kitap'' cins isim olduğundan aldıkları ekler kesme işaretiyle ayrılmaz.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c909077e-57a7-4ad8-aeb0-3d91835038e9', 'Ahmet''in kitabını dün akşam okudum.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c909077e-57a7-4ad8-aeb0-3d91835038e9', 'Kalem''imi masanın üstünde unuttum.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c909077e-57a7-4ad8-aeb0-3d91835038e9', 'Öğretmen''e ödevimi teslim ettim.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('c909077e-57a7-4ad8-aeb0-3d91835038e9', 'Kitab''ı çantama koydum.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('6997387f-b519-45e4-a884-9af9043a0134', '4d4e66fa-6b06-4194-a222-0ed30c0edd1b', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde virgül (,) doğru bir yerde kullanılmıştır?', 'Sıralama bildiren cümlelerde virgülün doğru kullanımını uygular.', 'Eş görevli kelimeler olan ''elma, armut, muz'' birbirinden virgülle ayrılmış, son öğeden önce ''ve'' bağlacı kullanıldığı için virgüle gerek duyulmamıştır. Diğer seçeneklerde virgüller anlamsız ya da gereksiz yerlere konmuştur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('6997387f-b519-45e4-a884-9af9043a0134', 'Çarşıdan elma, armut, muz ve şeftali aldı.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('6997387f-b519-45e4-a884-9af9043a0134', 'Çarşıdan, elma armut muz ve şeftali aldı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('6997387f-b519-45e4-a884-9af9043a0134', 'Çarşıdan elma armut, muz ve, şeftali aldı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('6997387f-b519-45e4-a884-9af9043a0134', 'Çarşıdan elma armut muz, ve şeftali, aldı.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('a3d2d354-0cda-4ef3-a8ac-886ccd4cbdfb', '4d4e66fa-6b06-4194-a222-0ed30c0edd1b', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde iki nokta (:) doğru kullanılmıştır?', 'İki noktanın örnek/liste verme işlevini kavrar.', 'Birinci cümlede iki nokta, kendisinden sonra bir liste (örnek) sıralanacağını haber verdiği için doğru kullanılmıştır. Diğer cümlelerde iki noktayı gerektiren bir açıklama ya da örnekleme durumu yoktur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a3d2d354-0cda-4ef3-a8ac-886ccd4cbdfb', 'Kırtasiyeden şunları aldım: kalem, silgi, defter.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a3d2d354-0cda-4ef3-a8ac-886ccd4cbdfb', 'Yarın: erken kalkıp işe gideceğim.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a3d2d354-0cda-4ef3-a8ac-886ccd4cbdfb', 'Bahçede: çiçekler yeni açmıştı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a3d2d354-0cda-4ef3-a8ac-886ccd4cbdfb', 'O gün: eve oldukça geç geldi.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('60118eaf-930e-41e5-851a-692adc7af501', '4d4e66fa-6b06-4194-a222-0ed30c0edd1b', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde noktalı virgül (;) doğru kullanılmıştır?', 'Noktalı virgülün virgüllerle ayrılmış öğe gruplarını ayırma işlevini uygular.', 'Birinci cümlede virgüllerle ayrılmış iki farklı kişi grubu (''Ali, Veli, Ayşe'' ve ''Mehmet, Fatma'') noktalı virgülle birbirinden ayrılmıştır. Diğer cümlelerde noktalı virgül gereksiz yere, herhangi bir öğe grubunu ayırmadan kullanılmıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('60118eaf-930e-41e5-851a-692adc7af501', 'Sınıfta Ali, Veli, Ayşe; bahçede ise Mehmet, Fatma vardı.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('60118eaf-930e-41e5-851a-692adc7af501', 'Bu kitabı; okuyup çok beğendim.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('60118eaf-930e-41e5-851a-692adc7af501', 'Yarın; erkenden okula gideceğim.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('60118eaf-930e-41e5-851a-692adc7af501', 'Akşam; ailecek yemek yedik.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('4b274b1d-ab39-4e7c-a6e1-e976a877170f', '4d4e66fa-6b06-4194-a222-0ed30c0edd1b', 'zor'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde noktalama işaretlerinin tamamı doğru kullanılmıştır?', 'Birden fazla noktalama kuralını bir arada değerlendirerek doğru cümleyi seçer.', 'İkinci cümlede iki nokta, kendisinden sonra gelen alıntı sözden önce doğru biçimde kullanılmış, tırnak içindeki alıntı da doğru noktalanmıştır. Diğer cümlelerde noktalı virgül gereksiz yere kullanılmış ya da ''masadaki'' kelimesine yanlışlıkla kesme işareti eklenmiştir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4b274b1d-ab39-4e7c-a6e1-e976a877170f', 'Ahmet''e, İstanbul''dan gelen; mektubu hemen verdim.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4b274b1d-ab39-4e7c-a6e1-e976a877170f', 'Öğretmenimiz: ''Yarın sınav var.'' dedi.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4b274b1d-ab39-4e7c-a6e1-e976a877170f', 'Masada''ki kitapları, düzenle dedi.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('4b274b1d-ab39-4e7c-a6e1-e976a877170f', 'Çarşıya gidip; elma, armut aldım.', false, 3);
insert into topic_contents (topic_id, summary, content_md, example_question) values ('d36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'Gerçek, mecaz, yan ve terim anlam ile eş anlam, zıt anlam, sesteşlik ve deyimlerin cümle içindeki kullanımını örneklerle işleyen sözcükte anlam konusu.', '## Gerçek (Temel) Anlam ve Mecaz Anlam
Bir kelimenin ilk akla gelen, sözlükteki asıl anlamına gerçek (temel) anlam denir: ''Bu çanta çok ağırdı.'' Kelimenin benzetme yoluyla kazandığı, gerçek anlamından uzaklaşmış anlamına ise mecaz anlam denir: ''Sınav soruları oldukça ağırdı.'' (zor anlamında)

## Yan Anlam ve Terim Anlam
Bir kelimenin temel anlamıyla ilgili fakat ondan biraz uzaklaşmış anlamına yan anlam denir: ''Masanın ayağı kırıldı.'' Bir bilim, sanat veya meslek dalına özgü kavramı karşılayan anlama ise terim anlam denir: ''Bu cümlenin öznesini bulun.'' veya ''Kelimenin kökünü belirleyin.''

## Eş Anlam (Anlamdaş) ve Zıt Anlam (Karşıt)
Yazılışları farklı, anlamları aynı veya çok yakın olan kelimelere eş anlamlı (anlamdaş) denir: ''kara-siyah, misafir-konuk.'' Birbirinin karşıtı olan kelimelere ise zıt anlamlı (karşıt) denir: ''büyük-küçük, sıcak-soğuk.''

## Eş Sesli (Sesteş) Kelimeler
Yazılışları aynı, anlamları farklı kelimelere sesteş (eş sesli) denir: ''Yüzünde bir gülümseme vardı.'' (yüz=çehre) ile ''Denizde saatlerce yüzdü.'' (yüz=yüzmek eylemi) cümlelerindeki ''yüz'' kelimeleri sesteştir.

## Deyimler
İki veya daha fazla kelimeden oluşan, çoğunlukla mecazlı anlam taşıyan kalıplaşmış söz gruplarına deyim denir: ''eli kulağında'' (bir işin bitmesine az kalmış olması), ''içi kararmak'' (çok üzülmek). Deyimler, cümle içinde kalıplaşmış anlamlarıyla ve bu anlama uygun bağlamda kullanılmalıdır; anlamına ters düşen bir bağlamda kullanılması anlatım bozukluğuna yol açar.', '''Eli kulağında'' deyimi aşağıdaki cümlelerin hangisinde doğru kullanılmıştır?') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('2e371e08-b413-476e-8711-7397a6c7bd1e', 'd36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde ''ağır'' sözcüğü mecaz anlamda kullanılmıştır?', 'Gerçek anlam ile mecaz anlamı ayırt eder.', 'İkinci cümlede ''ağır'' sözcüğü fiziksel bir ağırlığı değil, ''zor, çetin'' anlamını karşıladığı için mecaz anlamda kullanılmıştır. Diğer cümlelerde ''ağır'' sözcüğü nesnenin gerçek fiziksel ağırlığını belirtir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2e371e08-b413-476e-8711-7397a6c7bd1e', 'Bu çanta gerçekten çok ağırdı.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2e371e08-b413-476e-8711-7397a6c7bd1e', 'Sınav soruları oldukça ağırdı.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2e371e08-b413-476e-8711-7397a6c7bd1e', 'Valizi taşırken sırtım ağrıdı, çünkü çok ağırdı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2e371e08-b413-476e-8711-7397a6c7bd1e', 'Demir, ağır bir madendir.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('ce0cb19e-e44a-4e44-8dfc-2cca3e109540', 'd36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'kolay'::difficulty_level, 'Aşağıdaki kelime çiftlerinden hangisi eş anlamlıdır (anlamdaştır)?', 'Eş anlamlı (anlamdaş) kelimeleri tanır.', '''Kara'' ve ''siyah'' kelimeleri aynı rengi karşıladığı için eş anlamlıdır. Diğer seçeneklerdeki kelime çiftleri ise birbirinin zıt anlamlısıdır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ce0cb19e-e44a-4e44-8dfc-2cca3e109540', 'kara - siyah', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ce0cb19e-e44a-4e44-8dfc-2cca3e109540', 'büyük - küçük', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ce0cb19e-e44a-4e44-8dfc-2cca3e109540', 'sıcak - soğuk', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ce0cb19e-e44a-4e44-8dfc-2cca3e109540', 'ışık - karanlık', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('d4c27702-9c53-45a8-bb8e-04a927c936c9', 'd36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'orta'::difficulty_level, '''Eli kulağında'' deyimi aşağıdaki cümlelerin hangisinde doğru kullanılmıştır?', 'Deyimlerin cümle içindeki uygun kullanımını değerlendirir.', '''Eli kulağında'' deyimi bir işin bitmesine çok az kaldığını anlatır; birinci cümlede projenin yakında tamamlanacağı belirtildiği için deyim doğru bağlamda kullanılmıştır. Diğer cümlelerde deyimin anlamıyla cümlenin geri kalanı çelişmektedir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('d4c27702-9c53-45a8-bb8e-04a927c936c9', 'Proje eli kulağında, birkaç güne kadar tamamlanmış olacak.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('d4c27702-9c53-45a8-bb8e-04a927c936c9', 'Bu iş eli kulağında, çünkü daha yeni başladık.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('d4c27702-9c53-45a8-bb8e-04a927c936c9', 'O her zaman eli kulağında biriydi.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('d4c27702-9c53-45a8-bb8e-04a927c936c9', 'Param eli kulağında bittiği için borç almak zorunda kaldım.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('9b1ebe49-51f6-44fb-820a-759c2adf1930', 'd36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde ''yüz'' sözcüğü diğerlerinden farklı bir anlamda (sesteş olarak) kullanılmıştır?', 'Sesteş (eş sesli) kelimeleri cümle bağlamında ayırt eder.', 'İkinci cümlede ''yüzdü'', ''yüzmek'' eyleminden gelir ve suda hareket etmeyi ifade eder; diğer cümlelerdeki ''yüz'' ise ''çehre, surat'' anlamındaki isimdir. Yazılışları aynı fakat anlamları farklı olduğu için bu kelimeler sesteştir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9b1ebe49-51f6-44fb-820a-759c2adf1930', 'Yüzünde güzel bir gülümseme vardı.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9b1ebe49-51f6-44fb-820a-759c2adf1930', 'Denizde saatlerce yüzdü.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9b1ebe49-51f6-44fb-820a-759c2adf1930', 'Yüzü hafif kızarmıştı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('9b1ebe49-51f6-44fb-820a-759c2adf1930', 'Onun yüzüne bakamadım.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('fcbc6933-9234-47cc-ab40-28e2282bef73', 'd36b15a7-95b8-4c4e-bf33-8e2737e8099e', 'zor'::difficulty_level, '''Kök'' sözcüğü aşağıdaki cümlelerin hangisinde terim anlamda (dil bilgisi terimi olarak) kullanılmıştır?', 'Terim anlamı gerçek ve mecaz anlamdan ayırt eder.', 'İkinci cümlede ''kök'', bir kelimenin anlam taşıyan en küçük parçasını belirten dil bilgisi terimi olarak kullanılmıştır. Diğer cümlelerde ''kök'' sözcüğü sırasıyla gerçek anlamda (bitki kökü) ve mecaz anlamda (kaynak, köken) kullanılmıştır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('fcbc6933-9234-47cc-ab40-28e2282bef73', 'Bahçedeki ağacın kökü çok derinlere inmişti.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('fcbc6933-9234-47cc-ab40-28e2282bef73', 'Bu kelimenin kökü Arapçadır.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('fcbc6933-9234-47cc-ab40-28e2282bef73', 'Sorunun kökünü araştırmalıyız.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('fcbc6933-9234-47cc-ab40-28e2282bef73', 'Bu ailenin kökleri çok eskiye dayanıyor.', false, 3);
insert into topic_contents (topic_id, summary, content_md, example_question) values ('eb6df17f-05d4-49df-b626-ba5d585672a9', 'Anlatım bozukluğu türlerini (gereksiz sözcük, çelişki, mantık hatası, tamlama yanlışlığı), öznel-nesnel yargı ayrımını ve cümle tamamlamayı örneklerle açıklayan konu.', '## Anlatım Bozukluğu Türleri
Anlatım bozukluğu, bir cümlede anlam veya dil bilgisi açısından ortaya çıkan hatalardır. Başlıca türleri:
- **Gereksiz sözcük kullanımı:** Aynı anlama gelen iki kelimenin bir arada kullanılması. ''Bu haber beni hem çok sevindirdi hem de mutlu etti.'' (sevindirmek ve mutlu etmek eş anlamlıdır, biri gereksizdir.)
- **Çelişki:** Cümledeki iki ifadenin birbiriyle çelişmesi. ''Belki de bu sınavı kesinlikle kazanacak.'' (''belki'' ihtimal, ''kesinlikle'' kesinlik bildirir; bir arada kullanılamaz.)
- **Mantık (neden-sonuç) hatası:** Cümledeki neden ile sonucun birbiriyle uyuşmaması. ''Param olmadığı için kitabı alamadım ama yine de aldım.''
- **Tamlama yanlışlığı:** Ortak kullanılan bir öğeye ait ekin eksik bırakılması. ''Ali ve babasının arabası kaza yaptı.'' cümlesinde ''Ali'' kelimesinden sonra ''-nin'' tamlayan eki eksiktir; doğrusu ''Ali''nin ve babasının arabası'' olmalıdır.

## Öznel Yargı ve Nesnel Yargı
Nesnel yargı, kişiden kişiye değişmeyen, kanıtlanabilir, gözlemlenebilir bilgi içeren yargıdır: ''Roman 320 sayfadan oluşmaktadır.'' Öznel yargı ise kişisel görüş, beğeni ya da yorum içerir ve kişiden kişiye değişebilir: ''Bence bu roman çok sıkıcıydı.'' ''En, en güzel, bence, bana göre, sanırım'' gibi ifadeler genellikle öznelliğin işaretidir.

## Cümle Tamamlama
Bir cümlenin ya da paragrafın bağlamına en uygun ifadeyi seçmek, cümledeki anlam bütünlüğünü ve mantıksal akışı bozmayan seçeneği bulmayı gerektirir. Doğru seçenek, metinde verilen bilgilerle çelişmemeli ve konu dışına çıkmamalıdır.', '''Belki de bu sınavı kesinlikle kazanacak.'' cümlesindeki anlatım bozukluğunun türünü belirtiniz.') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('1e151cae-318c-461a-81de-a332701f381d', 'eb6df17f-05d4-49df-b626-ba5d585672a9', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisi nesnel bir yargı bildirmektedir?', 'Öznel yargı ile nesnel yargıyı ayırt eder.', 'Birinci cümlede sayfa sayısı, kişiden kişiye değişmeyen, kanıtlanabilir bir bilgi olduğu için nesneldir. Diğer cümleler kişisel görüş ve beğeni içerdiğinden özneldir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1e151cae-318c-461a-81de-a332701f381d', 'Roman, 320 sayfadan oluşmaktadır.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1e151cae-318c-461a-81de-a332701f381d', 'Bence bu roman çok sıkıcıydı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1e151cae-318c-461a-81de-a332701f381d', 'Yazarın en başarılı eseri budur.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('1e151cae-318c-461a-81de-a332701f381d', 'Bu film gelmiş geçmiş en iyi yapımdı.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('ffdf984d-5a4f-4101-a7c6-1ba250f8fd0e', 'eb6df17f-05d4-49df-b626-ba5d585672a9', 'kolay'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir anlatım bozukluğu vardır?', 'Gereksiz sözcük kullanımından kaynaklanan anlatım bozukluğunu fark eder.', '''Sevindirmek'' ve ''mutlu etmek'' aynı anlama geldiği için bu iki ifadenin bir arada kullanılması gereksiz tekrara, dolayısıyla anlatım bozukluğuna yol açmıştır. Diğer cümlelerde böyle bir tekrar yoktur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ffdf984d-5a4f-4101-a7c6-1ba250f8fd0e', 'Bu haber beni hem çok sevindirdi hem de mutlu etti.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ffdf984d-5a4f-4101-a7c6-1ba250f8fd0e', 'Öğrenciler sınava iyi hazırlandı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ffdf984d-5a4f-4101-a7c6-1ba250f8fd0e', 'Kitabı okuyup arkadaşına anlattı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('ffdf984d-5a4f-4101-a7c6-1ba250f8fd0e', 'Yağmur yağınca sokaklar ıslandı.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('0f90b77f-83f7-4e94-9c08-0d403dfe186b', 'eb6df17f-05d4-49df-b626-ba5d585672a9', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir anlatım bozukluğu vardır?', 'Çelişkiden kaynaklanan anlatım bozukluğunu tespit eder.', '''Belki'' ihtimal, ''kesinlikle'' ise kesinlik bildirir; bu iki ifade anlamca birbiriyle çeliştiği için cümlede anlatım bozukluğu vardır. Diğer cümlelerde böyle bir çelişki bulunmamaktadır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0f90b77f-83f7-4e94-9c08-0d403dfe186b', 'Belki de bu sınavı kesinlikle kazanacak.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0f90b77f-83f7-4e94-9c08-0d403dfe186b', 'Öğretmen konuyu tekrar anlattı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0f90b77f-83f7-4e94-9c08-0d403dfe186b', 'Sabah erkenden yola çıktık.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('0f90b77f-83f7-4e94-9c08-0d403dfe186b', 'Kitapları düzenli bir şekilde raflara yerleştirdi.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('b7738c1f-62c1-4ab2-8f3b-39a15cb0c318', 'eb6df17f-05d4-49df-b626-ba5d585672a9', 'orta'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir anlatım bozukluğu vardır?', 'Neden-sonuç ilişkisindeki mantık hatasını fark eder.', 'Cümlede önce parası olmadığı için kitabı alamadığı söylenmiş, ardından yine de aldığı belirtilerek çelişkili bir mantık hatası oluşturulmuştur. Diğer cümlelerde neden ile sonuç arasında tutarlı bir ilişki vardır.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b7738c1f-62c1-4ab2-8f3b-39a15cb0c318', 'Param olmadığı için kitabı alamadım ama yine de aldım.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b7738c1f-62c1-4ab2-8f3b-39a15cb0c318', 'Erken kalktığım için derse zamanında yetiştim.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b7738c1f-62c1-4ab2-8f3b-39a15cb0c318', 'Yorgun olduğu için erken yattı.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b7738c1f-62c1-4ab2-8f3b-39a15cb0c318', 'Kitabı bitirince bana geri verdi.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('638d438a-99e6-4fff-a344-0daff9a4bfb1', 'eb6df17f-05d4-49df-b626-ba5d585672a9', 'zor'::difficulty_level, 'Aşağıdaki cümlelerin hangisinde bir anlatım bozukluğu vardır?', 'Tamlama yanlışlığından kaynaklanan anlatım bozukluğunu ileri düzeyde tespit eder.', '''Ali'' kelimesinden sonra tamlayan eki ''-nin'' eksik bırakıldığı için cümlede tamlama yanlışlığı vardır; doğrusu ''Ali''nin ve babasının arabası'' biçiminde olmalıdır. Diğer cümlelerde böyle bir ek eksikliği yoktur.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('638d438a-99e6-4fff-a344-0daff9a4bfb1', 'Ali ve babasının arabası kaza yaptı.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('638d438a-99e6-4fff-a344-0daff9a4bfb1', 'Ali''nin ve babasının arabası kaza yaptı.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('638d438a-99e6-4fff-a344-0daff9a4bfb1', 'Öğrenciler sınıfa girdi ve yerlerine oturdu.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('638d438a-99e6-4fff-a344-0daff9a4bfb1', 'Yağmur dinince hep birlikte dışarı çıktık.', false, 3);
insert into topic_contents (topic_id, summary, content_md, example_question) values ('f884a167-9e40-4c5c-bc29-810eb13f200e', 'Paragrafta ana düşünce ve yardımcı düşünceyi ayırt etme, paragraf tamamlama ve metinden çıkarılabilecek/çıkarılamayacak yargıları belirleme becerilerini işleyen konu.', '## Konu ve Ana Düşünce
Bir paragrafın neyle ilgili olduğunu belirten kavrama konu denir; yazarın bu konu hakkında okura iletmek istediği asıl mesaja ise ana düşünce denir. Ana düşünce genellikle paragrafın son cümlesinde, bazen de ilk cümlesinde yer alır ve paragraftaki tüm cümleleri kapsayan bir yargı niteliğindedir.

## Yardımcı Düşünce
Ana düşünceyi destekleyen, açıklayan veya örnekleyen düşüncelere yardımcı düşünce denir. Bir paragrafta birden fazla yardımcı düşünce bulunabilir, ancak ana düşünce tektir.

## Paragraf Tamamlama
Paragrafın başına, ortasına ya da sonuna getirilecek cümle; paragrafın anlam bütünlüğünü, konu akışını ve mantık örgüsünü bozmamalıdır. Başa gelecek cümle genellikle konuyu tanıtır; sona gelecek cümle ise paragrafta anlatılanların bir sonucu, genellemesi ya da tamamlayıcısı niteliğinde olmalıdır. Doğru seçenek metindeki bilgilerle çelişmemeli ve konu dışına çıkmamalıdır.

## Metinden Çıkarılabilecek Yargılar
''Bu parçadan hangi yargıya ulaşılabilir/ulaşılamaz'' tipi sorularda, seçeneklerin metinde açıkça ifade edilen ya da metinden mantıksal olarak çıkarılabilen bilgilerle örtüşüp örtüşmediğine bakılır. Metinde yer almayan, aşırı genelleme içeren ya da metinle çelişen seçenekler yanlıştır.

## Anlatım Biçimleri
Paragraflarda yazarın öznel ya da nesnel bir bakış açısıyla yazıp yazmadığı; örnekleme, tanık gösterme, karşılaştırma gibi düşünceyi geliştirme yollarının kullanılıp kullanılmadığı da sıkça sorulur.', 'Aşağıdaki paragrafın ana düşüncesi ne olabilir? ''Kitap okumak, insanın hayal gücünü geliştirir, kelime dağarcığını zenginleştirir...''') on conflict (topic_id) do update set summary = excluded.summary, content_md = excluded.content_md, example_question = excluded.example_question;
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('62616390-4dc6-4f30-9bbc-8db33857f318', 'f884a167-9e40-4c5c-bc29-810eb13f200e', 'kolay'::difficulty_level, '''İnsanlar günlük hayatlarında birçok karar verir. Bu kararların bazıları küçük, bazıları ise hayatı derinden etkileyecek kadar büyüktür. Küçük kararlar genellikle anlık düşünülüp hızla alınırken büyük kararlar için uzun süre düşünülür, çevredeki insanların fikirleri alınır. Çünkü büyük kararların sonuçları, kişinin hayatını uzun yıllar etkileyebilir.'' Bu parçanın ana düşüncesi aşağıdakilerden hangisidir?', 'Paragrafın ana düşüncesini belirler.', 'Parça, büyük kararların uzun süre düşünülerek ve başkalarının görüşü alınarak verilmesi gerektiğini, çünkü sonuçlarının kalıcı olduğunu vurgulamaktadır. Diğer seçenekler ya parçanın yalnızca bir kısmını yansıtır ya da metinde yer almayan aşırı bir genelleme içerir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('62616390-4dc6-4f30-9bbc-8db33857f318', 'İnsanlar hayatları boyunca sürekli karar alma durumundadır.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('62616390-4dc6-4f30-9bbc-8db33857f318', 'Büyük kararlar, sonuçlarının kalıcı etkisi nedeniyle daha dikkatli ve uzun düşünülerek alınmalıdır.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('62616390-4dc6-4f30-9bbc-8db33857f318', 'Küçük kararlar hızlı alındığı için önemsizdir.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('62616390-4dc6-4f30-9bbc-8db33857f318', 'Çevredeki insanların fikirleri her zaman doğru kararlar verdirir.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('2b0d8812-b9a5-4275-ab68-6134f70bb77a', 'f884a167-9e40-4c5c-bc29-810eb13f200e', 'kolay'::difficulty_level, '''Kitap okumak, insanın hayal gücünü geliştirir, kelime dağarcığını zenginleştirir ve empati kurma becerisini artırır. Ayrıca düzenli kitap okuyan bireylerin analitik düşünme yetenekleri de gelişir. Bu nedenle ______'' Bu parçada boş bırakılan yere aşağıdakilerden hangisi getirilmelidir?', 'Paragrafın anlam akışına uygun tamamlama cümlesini seçer.', 'Parçada kitap okumanın sağladığı faydalar sıralandığı için mantıksal sonuç, bu alışkanlığın erken yaşta kazandırılması gerektiğidir. Diğer seçenekler parçanın konusuyla ilgisizdir ya da metinde değinilmeyen konulara değinir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2b0d8812-b9a5-4275-ab68-6134f70bb77a', 'televizyon izlemek de kitap okumak kadar faydalıdır.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2b0d8812-b9a5-4275-ab68-6134f70bb77a', 'çocuklara küçük yaştan itibaren kitap okuma alışkanlığı kazandırılmalıdır.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2b0d8812-b9a5-4275-ab68-6134f70bb77a', 'kitap okumanın hiçbir zararı yoktur.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('2b0d8812-b9a5-4275-ab68-6134f70bb77a', 'herkesin aynı türde kitap okuması gerekir.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('dd2e98ec-308f-494d-b871-90e53c6e6960', 'f884a167-9e40-4c5c-bc29-810eb13f200e', 'orta'::difficulty_level, '''Şehirlerin hızla büyümesiyle birlikte yeşil alanlar giderek azalmaktadır. Betonlaşan kentlerde hava kalitesi düşmekte, sıcaklık artışları daha belirgin hissedilmektedir. Bununla birlikte bazı belediyeler, çatı bahçeleri ve dikey ormanlar gibi projelerle bu soruna çözüm aramaktadır. Ancak bu çabalar, kaybedilen yeşil alanların yerini tam olarak dolduramamaktadır.'' Bu parçanın ana düşüncesi aşağıdakilerden hangisidir?', 'Paragrafta ana düşünce ile yardımcı düşünceleri ayırt eder.', 'Parça, kentleşmeyle azalan yeşil alanlar için belediyelerin çözüm aradığını ama bu çabaların yeterli olmadığını vurgulamaktadır. Diğer seçenekler metinle çelişir ya da metinde yapılmayan bir karşılaştırma veya aşırı genelleme içerir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('dd2e98ec-308f-494d-b871-90e53c6e6960', 'Belediyeler çevre sorunlarına duyarsız kalmaktadır.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('dd2e98ec-308f-494d-b871-90e53c6e6960', 'Kentleşmeyle azalan yeşil alanların yerini, alınan önlemler yeterince dolduramamaktadır.', true, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('dd2e98ec-308f-494d-b871-90e53c6e6960', 'Çatı bahçeleri, dikey ormanlardan daha etkilidir.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('dd2e98ec-308f-494d-b871-90e53c6e6960', 'Hava kalitesi yalnızca sıcaklıkla ilgilidir.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('a2d683d2-988e-4e05-9cd3-73af84e457fb', 'f884a167-9e40-4c5c-bc29-810eb13f200e', 'orta'::difficulty_level, '''______ Bu tür kitaplar, karmaşık bilimsel kavramları sade bir dille anlatarak okurun ilgisini çeker. Yazar, günlük hayattan örnekler kullanarak konuyu somutlaştırır. Böylece bilim, sadece uzmanların değil herkesin anlayabileceği bir alan hâline gelir.'' Bu parçanın başına aşağıdaki cümlelerden hangisi getirilmelidir?', 'Paragrafın başına gelecek en uygun giriş cümlesini belirler.', 'Parçanın devamında ''bu tür kitaplar'' ifadesiyle atıf yapılan konu, ancak popüler bilim kitaplarını tanıtan birinci seçenekle uyumludur. Diğer seçenekler parçanın konusuyla ilgisizdir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a2d683d2-988e-4e05-9cd3-73af84e457fb', 'Popüler bilim kitapları, bilimi geniş kitlelere ulaştırmayı amaçlayan eserlerdir.', true, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a2d683d2-988e-4e05-9cd3-73af84e457fb', 'Bilim insanları genellikle yalnız çalışmayı tercih eder.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a2d683d2-988e-4e05-9cd3-73af84e457fb', 'Roman yazarları hayal gücünü kullanarak eser üretir.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('a2d683d2-988e-4e05-9cd3-73af84e457fb', 'Her kitap mutlaka bir amaç taşımalıdır.', false, 3);
insert into questions (id, topic_id, difficulty, question_text, kazanim, explanation) values ('b28563ff-defe-40ec-8709-e8c117c20279', 'f884a167-9e40-4c5c-bc29-810eb13f200e', 'zor'::difficulty_level, '''Bir sanat eserinin değeri, yalnızca teknik ustalıkla ölçülemez. Tuval üzerine ustaca işlenmiş bir tablo, izleyicide hiçbir duygu uyandırmıyorsa amacına ulaşamamış demektir. Oysa bazen çok basit çizgilerle oluşturulmuş bir eser, izleyicisini derinden etkileyebilir, onu düşünmeye sevk edebilir. Bu nedenle sanatı değerlendirirken teknik beceri kadar, eserin izleyicide bıraktığı etkiye de bakmak gerekir.'' Bu parçadan aşağıdaki yargılardan hangisine ulaşılamaz?', 'Paragraftan çıkarılabilecek ve çıkarılamayacak yargıları ayırt eder.', 'Parçada sanatçının ününden hiç söz edilmediği için dördüncü seçenekteki yargıya metinden ulaşılamaz. Diğer seçenekler parçada doğrudan ya da dolaylı olarak ifade edilmiştir.');
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b28563ff-defe-40ec-8709-e8c117c20279', 'Teknik açıdan kusursuz bir eser, izleyicide duygu uyandırmayabilir.', false, 0);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b28563ff-defe-40ec-8709-e8c117c20279', 'Basit görünen eserler de izleyici üzerinde güçlü bir etki bırakabilir.', false, 1);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b28563ff-defe-40ec-8709-e8c117c20279', 'Bir sanat eserini değerlendirirken hem teknik beceri hem de duygusal etki göz önünde bulundurulmalıdır.', false, 2);
insert into question_choices (question_id, choice_text, is_correct, order_index) values ('b28563ff-defe-40ec-8709-e8c117c20279', 'Sanat eserlerinin değeri, yalnızca sanatçının ününe göre belirlenir.', true, 3);

commit;
